
{{ config(
    materialized="table",
    schema='SALES',
	post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (SBD_ENTY_NBR,PROD_KEY,REG_DATE,SRC_SYS_KEY,IR_DTL_SKU,
  REGN_KEY,TRTRY_KEY,FYR_ID,FMTH_ID,SERL_NBR,REG_KEY)"]
) }}

      WITH CAL
AS (
     SELECT DY_DTE,CLNDR_KEY,
        MONTH(DY_DTE),YEAR(DY_DTE),
                FYR_ID,
        FMTH_ID, 
        FWK_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN FYR_ID+1 ELSE FYR_ID END AS YEAR ,
       CASE WHEN AA >12 THEN ROUND(AA-12) else ROUND(LPAD(AA,2,0)) END AS MONTH   
FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}
),
 PL AS(
select DISTINCT a.PROD_KEY,A.PROD_HIER_LVL_5_DESC
FROM (SELECT DISTINCT PROD_KEY,SRC_SYS_KEY FROM {{source('FACTS','FACT_SALES_WARRANTY_REGISTRATION')}} WHERE UPPER(TRIM(SRC_SYS_KEY)) = 'INFORXA'
  ) PL
LEFT JOIN
  (SELECT DISTINCT 
   PROD_KEY,PROD_HIER_LVL_5_DESC
    FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}} where SRC_SYS_KEY  = 'MTD_IAMS') A
ON UPPER(TRIM(PL.PROD_KEY))= UPPER(TRIM(A.PROD_KEY)) --
WHERE PL.SRC_SYS_KEY = 'INFORXA'  
    ),
    CUST_SALESFORCE AS (
    SELECT
        CUST.PDM_ID,
        CUST.SLS_DEV_SPCL,
        CUST.DIST_ID,
        CUST.SBD_ENTY_NBR,
        CUST.SBD_PRNT_ENTY,
        CUST.HUSTLER_DLR_NBR,
        CUST.DLR_NAME,
        CUST.DLR_LNAME,
        CUST.SHIPPING_STATE_CD,
	    CUST.SLS_REGN_KEY,
        CUST.SLS_TRTRY_KEY,
        CUST.ACC_OWNER_NM,
        CUST.CNTRY_KEY
       FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}} CUST
       WHERE CUST.SRC_SYS_KEY='MTD_SALESFORCE' 
       )

SELECT 
'REGISTRATIONS' AS CTGY_ID,
'REGISTRATION' AS CTGY_TYP,
'SALES_REGISTRATIONS & REGISTRED SETTELMENTS' AS CTGY_SHORT_NAME,
A.SRC_SYS_KEY,
P.GPP_CATEGORY_DESC  AS PROD_CTGY,
CAL.FYR_ID,
-- CAL.FMTH_ID,
  LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
CAL.FWK_ID,
CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
CAL.MONTH AS PROG_MTH_ID,
YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID, 
 SF.SLS_REGN_KEY AS REGN_KEY,
SF.SLS_TRTRY_KEY AS TRTRY_KEY,
SF.ACC_OWNER_NM AS DLR_SLS_MGR,
SF.PDM_ID,
SF.SLS_DEV_SPCL,
SF.DIST_ID AS DIST_ID,
SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
SHIP.DIV_ID AS DIV_ID,
SF.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
SF.DLR_NAME AS DLR_NAME,
SF.DLR_LNAME AS DLR_LNAME,
SF.SHIPPING_STATE_CD AS DLR_STATE,
CASE WHEN UPPER(SF.CNTRY_KEY) IN ('UNITED STATES','US','U.S.A.','U.S.','USA','COLUMBIANA','DELAWARE') THEN 'US'
       ELSE NULL
     END AS DLR_CNTRY,
 CASE WHEN A.PROD_KEY = '181SAAY2739' THEN 'DEWALT' ELSE P.Final_Brand  END AS BRAND,
P.PROD_FAMILY_LKEY AS PROD_LN_KEY,
A.PROD_KEY,
REGEXP_REPLACE(P.PROD_DESC, '~~EXCEL', '') AS PROD_DESC,  
1 AS PROD_QTY,
TO_DECIMAL(A.NET_AMT_USD,30,2) AS AMOUNT,
TO_DECIMAL(A.NET_AMT_USD,30,2) AS AMOUNT_USD,
TO_DECIMAL(1 * AMOUNT_USD) AS EXTND_AMT,
DATE(A.REG_DATE) AS REG_DATE,
 CASE 
        WHEN (P.PROD_STAT_TYP) = 'ACT' THEN 'ACT'
        ELSE 'INACT' 
    END AS PROD_STAT,
CASE WHEN SUBSTR(P.PROD_DESC,6,1)='R'
THEN CONCAT(P.PROD_FAMILY_NAME,' ',SUBSTR(P.PROD_DESC,6,1),' ',SUBSTR(P.PROD_DESC,8,2),' ',SUBSTR(P.PROD_DESC,10,8))
ELSE CONCAT(P.PROD_FAMILY_NAME,' ',SUBSTR(P.PROD_DESC,8,2),' ',SUBSTR(P.PROD_DESC,10,8))
END AS IR_DTL_SKU,
SHIP.PO_NBR AS PO_NBR,
SHIP.ORD_NBR AS ORD_NBR,
SHIP.INVC_NBR AS INVC_NBR,
A.SERIAL_NBR AS SERL_NBR,
A.REG_KEY,
EDW_PROD.PRODTN_LN_NBR,
NULL AS LOAN_ID,
B.DLR_NBR,
NULL AS BRAND_UU40,
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE	
FROM
 {{source('FACTS','FACT_SALES_WARRANTY_REGISTRATION')}} A
LEFT JOIN ( SELECT DISTINCT  SERL_NBR,PROD_KEY,SRC_SYS_KEY,DLR_NBR FROM {{source('SALES_BRZ','BRZ_SALES_SETTLEMENT_INDEPENDENT_RETAIL')}}
QUALIFY  ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY)), UPPER(TRIM(SERL_NBR)) ORDER BY SERL_NBR ,PROD_KEY DESC ) = 1) B
 ON UPPER(TRIM(B.SERL_NBR))=UPPER(TRIM(A.SERIAL_NBR))
 AND UPPER(TRIM(A.PROD_KEY))=UPPER(TRIM(B.PROD_KEY))
AND B.SRC_SYS_KEY='EXCEL_QADDB'
LEFT JOIN CUST_SALESFORCE SF
ON TRIM(B.DLR_NBR)= TRIM(SF.HUSTLER_DLR_NBR)
LEFT JOIN (SELECT DISTINCT * FROM
{{source('DIMENSIONS', 'DIM_PRODUCT')}}) P
ON CONCAT('EXCEL_QADDB','~',UPPER(A.PROD_KEY)) = UPPER(P.PROD_KEY)
AND P.SRC_SYS_KEY='EXCEL_QADDB' 
LEFT JOIN CAL
  ON TO_CHAR(TO_DATE(REG_DATE, 'YYYY-MM-DD'), 'YYYYMMDD')= CAL.CLNDR_KEY 
LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
ON A.PROD_KEY = EDW_PROD.PROD_KEY
    AND EDW_PROD.SRC_SYS_KEY = 'EXCEL_QADDB' --988440
    AND EDW_PROD.CURR_RCRD_FLAG='Y'
    LEFT JOIN (SELECT DISTINCT SERL_NBR,PROD_KEY,DIV_ID,INVC_NBR,PO_NBR,ORD_NBR FROM {{source('SALES_BRZ','BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL')}}  WHERE SRC_SYS_KEY='EXCEL_QADDB'
 QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY)), UPPER(TRIM(SERL_NBR)) ORDER BY SERL_NBR ,PROD_KEY DESC ) = 1) SHIP
ON SHIP.SERL_NBR=A.SERIAL_NBR
AND SHIP.PROD_KEY=A.PROD_KEY
WHERE A.SRC_SYS_KEY = 'EXCEL_QADDB'


UNION ALL

SELECT 
'REGISTRATIONS' AS CTGY_ID,
'REGISTRATION' AS CTGY_TYP,
'SALES_REGISTRATIONS & REGISTRED SETTELMENTS' AS CTGY_SHORT_NAME,
A.SRC_SYS_KEY,
P.GPP_CATEGORY_DESC  AS PROD_CTGY,
CAL.FYR_ID,
-- CAL.FMTH_ID,
LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
CAL.FWK_ID,
CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
CAL.MONTH AS PROG_MTH_ID,
YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
-- SLS_REGN_KEY, SLS_TRTRY_KEY 
SF.SLS_REGN_KEY AS REGN_KEY,
SF.SLS_TRTRY_KEY AS TRTRY_KEY,
SF.ACC_OWNER_NM AS DLR_SLS_MGR,
SF.PDM_ID,
SF.SLS_DEV_SPCL,
SF.DIST_ID AS DIST_ID,
SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
SF.SBD_PRNT_ENTY  AS SBD_PRNT_ENTY,
SHIP.DIV_ID AS DIV_ID,
SF.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
SF.DLR_NAME AS DLR_NAME,
SF.DLR_LNAME AS DLR_LNAME,
SF.SHIPPING_STATE_CD AS DLR_STATE,
---CUST.CNTRY_KEY AS DLR_CNTRY,
CASE WHEN UPPER(SF.CNTRY_KEY) IN ('UNITED STATES','US','U.S.A.','U.S.','USA','COLUMBIANA','DELAWARE') THEN 'US'
       ELSE NULL
     END AS DLR_CNTRY,
-- NULL AS PRODTN_LN_NBR,
P.FINAL_BRAND AS BRAND,
 PL.PROD_HIER_LVL_5_DESC  AS PROD_LN_KEY,
--PROD_1.PROD_FAMILY_NAME AS PROD_LN_DESC,
A.PROD_KEY,
P.PROD_DESC AS PROD_DESC,
A.PROD_QTY,
TO_DECIMAL(SHIP.AMOUNT,30,2) AS AMOUNT,	
TO_DECIMAL(SHIP.AMOUNT,30,2) AS AMOUNT_USD,	
TO_DECIMAL(A.PROD_QTY * AMOUNT_USD) AS EXTND_AMT,
COALESCE(TRY_TO_DATE(A.REG_DATE, 'YYYYMMDD'), DATE '1900-01-01') AS REG_DATE,
-- PRD_LOC.PROD_STAT_DESC AS PROD_STAT,
CASE 
    WHEN TRIM(UPPER(PRD_LOC.PROD_STAT_DESC )) = 'ACTIVE' THEN 'ACT'
    WHEN TRIM(UPPER(PRD_LOC.PROD_STAT_DESC )) = 'SUPPRESSED (INACTIVE)' THEN 'INACT'
    ELSE  PRD_LOC.PROD_STAT_DESC 
  END AS PROD_STAT,
PRDH.PROD_HIER_LVL_7_KEY AS IR_DTL_SKU,
SHIP.PO_NBR AS PO_NBR,
SHIP.ORD_NBR AS ORD_NBR,
SHIP.INVC_NBR AS INVC_NBR,
A.SERIAL_NBR AS SERL_NBR,
A.REG_KEY,
EDW_PROD.PRODTN_LN_NBR,
NULL AS LOAN_ID,
A.CUST_NBR AS DLR_NBR,
PRDLKP.PROD_BRAND AS BRAND_UU40,
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
FROM {{source('FACTS','FACT_SALES_WARRANTY_REGISTRATION')}} A   --9968601
LEFT JOIN
-- (SELECT DISTINCT * FROM
-- PROD_EDW.DIMENSIONS.DIM_PRODUCT) P
 (SELECT DISTINCT * FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} ) P
ON CONCAT('INFORXA','~',UPPER(A.PROD_KEY)) = UPPER(P.PROD_KEY)
AND P.SRC_SYS_KEY='INFORXA'
 LEFT JOIN CAL
  --ON CAST(CLNDR_YR_ID AS VARCHAR)=  TRY_TO_NUMBER(SUBSTR(A.REG_DATE,1,4))
   --AND CAST(CLNDR_MTH_ID AS VARCHAR)= TRY_TO_NUMBER(SUBSTR(A.REG_DATE,5,2))
  ON  A.REG_DATE=CAL.CLNDR_KEY
LEFT JOIN CUST_SALESFORCE SF
	ON TRIM(A.CUST_NBR)= TRIM(SF.SBD_ENTY_NBR)
LEFT JOIN (
SELECT DISTINCT PROD_KEY,PROD_STAT_LKEY,PROD_STAT_DESC,PROD_LOC_LOV.PROD_LOC_KEY FROM 
-- (Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,SRC_SYS_KEY from PROD_EDW.DIMENSIONS.DIM_PRODUCT_LOCATION WHERE SRC_SYS_KEY='INFORXA'
(Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,SRC_SYS_KEY FROM {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}} WHERE SRC_SYS_KEY='INFORXA'
QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY))  ORDER BY PROD_KEY DESC) =1
    ) PROD_LOC
	 -- LEFT JOIN PROD_EDW.DIMENSIONS.DIM_PRODUCT_LOCATION_LOV PROD_LOC_LOV
	 LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION_LOV')}} PROD_LOC_LOV
on CONCAT(PROD_LOC.PROD_LOC_KEY,'~','E') = PROD_LOC_LOV.PROD_LOC_KEY
    ) PRD_LOC
ON PRD_LOC.PROD_KEY=A.PROD_KEY
  LEFT JOIN (SELECT DISTINCT PROD_KEY,PROD_HIER_LVL_7_KEY,BUS_DIV_ID,SRC_SYS_KEY,CURR_RCRD_FLAG,PROD_HIER_LVL_4_DESC,PROD_HIER_LVL_5_KEY
	FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}} WHERE SRC_SYS_KEY='INFORXA')  PRDH
ON A.PROD_KEY = PRDH.PROD_KEY 
AND  PRDH.CURR_RCRD_FLAG = 'Y' 
AND PRDH.BUS_DIV_ID = '1' 
LEFT JOIN (SELECT DISTINCT PROD_FAMILY_NAME,PROD_FAMILY_LKEY,PROD_KEY,PROD_ID,SRC_SYS_KEY FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='BLUEYONDER') PROD_1
    ON a.PROD_KEY=PROD_1.PROD_ID
LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
ON A.PROD_KEY = EDW_PROD.PROD_KEY
    AND EDW_PROD.SRC_SYS_KEY = 'INFORXA'
    AND EDW_PROD.CURR_RCRD_FLAG='Y'
LEFT JOIN (SELECT DISTINCT PROD_KEY,SERL_NBR,AMOUNT,SBD_ENTY_NBR,DIV_ID,INVC_NBR,PO_NBR,ORD_NBR FROM {{source('SALES_BRZ','BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL')}} WHERE 
        SRC_SYS_KEY = 'INFORXA'
    QUALIFY  ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY)), UPPER(TRIM(SERL_NBR)) ORDER BY SERL_NBR ,PROD_KEY DESC ) = 1) SHIP
    ON UPPER(TRIM(A.SERIAL_NBR)) = UPPER(TRIM(SHIP.SERL_NBR))
   AND UPPER(TRIM(A.PROD_KEY)) = UPPER(TRIM(SHIP.PROD_KEY))
LEFT JOIN  PROD_EDW.CONSOLIDATED.VW_EDW_PRODUCT_LOOKUP PRDLKP
    ON UPPER(TRIM(A.PROD_KEY))=UPPER(TRIM(PRDLKP.PROD_LKP_KEY))
    AND PRDLKP.SRC_SYS_KEY='INFORXA'
 LEFT JOIN PL
    ON UPPER(TRIM(PL.PROD_KEY))=UPPER(TRIM(A.PROD_KEY))
 WHERE A.SRC_SYS_KEY = 'INFORXA'


   


      



	

  
