{{ config(
    materialized="table",
    schema='SALES',
    post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (TXN_DTE,PROD_KEY,DLR_NAME,IR_DTL_SKU,PRODTN_LN_NBR,SERL_NBR,LOC_ID,INV_DTE,SBD_ENTY_NBR,DIST_ID,REGN_KEY,INVC_NBR,INTEREST_START_DTE)"]
) }}
WITH CAL AS (
    SELECT DY_DTE,
        MONTH(DY_DTE),YEAR(DY_DTE),
        FYR_ID,
        FMTH_ID, 
        FWK_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN FYR_ID+1 ELSE FYR_ID END AS YEAR ,
       CASE WHEN AA >12 THEN ROUND(AA-12) else ROUND(LPAD(AA,2,0)) END AS MONTH   
    FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}
),
	CUST_SALESFORCE AS (
    SELECT
        CUST.PDM_ID,
        CUST.SLS_DEV_SPCL,
        CUST.DIST_ID,
        CUST.SBD_ENTY_NBR,
        CUST.SBD_PRNT_ENTY,
        CUST.HUSTLER_DLR_NBR,
        CUST.DLR_NAME,
        CUST.DLR_LNAME,
        CUST.BILLING_STATE_CD,
	SRC_SYS_KEY,
        CUST.SLS_REGN_KEY,
        CUST.SLS_TRTRY_KEY,
        CUST.ACC_OWNER_NM,
	CUST.CNTRY_KEY,
	SHIPPING_STATE_CD
        FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}} CUST
       WHERE CUST.SRC_SYS_KEY='MTD_SALESFORCE' 
       ),

  PL AS(
select DISTINCT FLR.PROD_NUM,A.PROD_HIER_LVL_5_DESC
FROM (
    SELECT *
    FROM {{source('SALES_SOURCE','VW_BRZ_DEALER_SETTLEMENTS')}} FLR
     -- LEFT JOIN (SELECT DISTINCT FYR_ID,FMTH_ID,DY_DTE FROM PROD_EDW.DIMENSIONS.DIM_FISCAL_CALENDAR) CAL
     LEFT JOIN (SELECT DISTINCT FYR_ID,FMTH_ID,DY_DTE FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}) CAL
    ON FLR.GENERATION_DTE = CAL.DY_DTE
    WHERE FLR.SRC_SYS_KEY = 'INFORXA' 
      AND UPPER(SRC_IDENTIFIER) = 'DEALER_FLOOR_PLAN'
    QUALIFY ROW_NUMBER() OVER (
    PARTITION BY FYR_ID, FMTH_ID,SERIAL_NBR
    ---PARTITION BY YEAR(INV_DTE), MONTH(INV_DTE),SERIAL_NBR
    ORDER BY GENERATION_DTE DESC
--ORDER BY INV_DTE DESC
    ) = 1
) FLR 
LEFT JOIN
  (SELECT DISTINCT 
   PROD_KEY,PROD_HIER_LVL_5_DESC FROM
    {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}} where SRC_SYS_KEY  = 'MTD_IAMS') A
ON UPPER(TRIM(FLR.PROD_NUM))= UPPER(TRIM(A.PROD_KEY)) --
WHERE FLR.SRC_SYS_KEY = 'INFORXA'  
    )
    SELECT 
    'RETAIL' AS CTGY_ID,
    'FLOORPLAN' AS CTGY_TYP,
    'SALES_FLOORPLAN' AS CTGY_SHORT_NAME,
    FLR.SRC_SYS_KEY AS SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC  AS PROD_CTGY,
    CAL.FYR_ID AS FYR_ID,
    -- CAL.FMTH_ID AS FMTH_ID,
   LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
   CAL.FWK_ID AS FWK_ID,
   CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
    CAL.MONTH AS PROG_MTH_ID,
    YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
    MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
    SF.SLS_REGN_KEY AS REGN_KEY,
    SF.SLS_TRTRY_KEY AS TRTRY_KEY,
    SF.ACC_OWNER_NM AS DLR_SLS_MGR,
    SF.PDM_ID AS PDM_ID,
    SF.SLS_DEV_SPCL AS SLS_DEV_SPCL,
    SF.DIST_ID AS DIST_ID,
    SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
    SF.SBD_PRNT_ENTY  AS SBD_PRNT_ENTY,
    SHIP.DIV_ID AS DIV_ID,
    SF.HUSTLER_DLR_NBR  AS HUSTLER_DLR_NBR,
    SF.DLR_NAME  AS DLR_NAME,
    SF.DLR_LNAME  AS DLR_LNAME,
   FLR.SHIPPING_STATE_CD AS DLR_STATE,
    FLR.COUNTRY AS DLR_CNTRY,
    -- CUST.CNTRY_KEY AS DLR_CNTRY,
    PROD_EDW.PRODTN_LN_NBR AS PRODTN_LN_NBR,
    --FLR.BRAND_UU40 AS BRAND,
    PROD.FINAL_BRAND AS BRAND,
    PL.PROD_HIER_LVL_5_DESC AS PROD_LN_KEY,
    --PROD_1.PROD_FAMILY_NAME AS PROD_LN_DESC,
    FLR.PROD_NUM AS PROD_KEY,
    PROD.PROD_DESC AS PROD_DESC,
    PRDH.PROD_HIER_LVL_7_KEY AS IR_DTL_SKU,
    CASE WHEN UPPER(PROD_LOC.PROD_STAT_LKEY)='A' THEN 'ACT'
    ELSE 'INACT'
    END AS PROD_STAT,
    NULL AS SHIP_FROM,
    NULL AS ORD_TYP,
    -- POS.QTY_ON_HAND AS QTY_ON_HAND,
    -- POS.QTY_SOLD AS QTY_SOLD,
    -- POS.QTY_ORD AS QTY_ORD,
    CASE WHEN FLR.SETTLEMENT_DTE IS NULL THEN '1' ELSE NULL END AS PROD_QTY,
    TO_DECIMAL(FLR.OUTSTANDING_AMT,30,2)AS AMOUNT,
  TO_DECIMAL (FLR.OUTSTANDING_AMT,30,2) AS AMOUNT_USD,
  TO_DECIMAL (( PROD_QTY* AMOUNT ),30,2)AS EXTND_AMT,
    --FLR.LOAN_ID AS TXN_ID,
    DATE(FLR.GENERATION_DTE) AS TXN_DTE,
  (FLR.GENERATION_DTE) AS TXN_TM,
    NULL AS TXN_EFF_DTE,
    NULL AS TXN_GL_DTE,
    NULL AS TXN_TYP,
    SHIP.PO_NBR AS PO_NBR,
    SHIP.ORD_NBR AS ORD_NBR,
   CASE WHEN TRIM(INV_NBR)='' THEN SHIP.INVC_NBR ELSE INV_NBR END AS INVC_NBR,
    --SHIP.INVC_NBR,
    FLR.SERIAL_NBR AS SERL_NBR,
    NULL AS SITE_ID,
    NULL AS LOC_ID,
    NULL AS ORD_DTE,
    NULL AS ORD_DUE_DTE,
    DATE(FLR.INV_DTE) AS INV_DTE,
    NULL AS INV_PO_DTE,
    NULL AS FULL_DUE_DTE,
    NULL AS SHIP_QTY,
    NULL AS SLS_ORD_QTY,
    --DATE(FLR.AS_OF_DTE) AS FL_PLN_AG,
    DATE(FLR.INTEREST_START_DTE) AS INTEREST_START_DTE,
    FLR.LOAN_ID AS LOAN_ID,
	FLR.CUST_NBR AS DLR_NBR,
	DATE(FLR.INTEREST_START_DTE) as FREE_FLOORPLAN_END_DTE,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
    
    FROM
    (SELECT  *
    FROM {{source('SALES_SOURCE','VW_BRZ_DEALER_SETTLEMENTS')}} FLR
    LEFT JOIN (SELECT DISTINCT FYR_ID,FMTH_ID,DY_DTE FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}) CAL
ON FLR.GENERATION_DTE = CAL.DY_DTE
    WHERE FLR.SRC_SYS_KEY = 'INFORXA' 
      AND UPPER(SRC_IDENTIFIER) = 'DEALER_FLOOR_PLAN'
    QUALIFY ROW_NUMBER() OVER (
    PARTITION BY FYR_ID, FMTH_ID,SERIAL_NBR
    ORDER BY GENERATION_DTE DESC
--ORDER BY INV_DTE DESC
    ) = 1
    ) FLR

-- LEFT JOIN (SELECT DISTINCT ITEM_DESC,PROD_DESC,GPP_DIVISION_DESC,PROD_HIER_LVL_4_ID,PROD_FAMILY_LKEY,PROD_FAMILY_NAME,PROD_KEY,SRC_SYS_KEY,FINAL_BRAND,GPP_CATEGORY_DESC,PROD_HIER_LVL_4_DESC,GPP_DIVISION_ID   FROM TEST_EDW.DIMENSIONS.DIM_PRODUCT) PROD
LEFT JOIN (SELECT DISTINCT ITEM_DESC,PROD_DESC,GPP_DIVISION_DESC,PROD_HIER_LVL_4_ID,PROD_FAMILY_LKEY,PROD_FAMILY_NAME,PROD_KEY,SRC_SYS_KEY,FINAL_BRAND,GPP_CATEGORY_DESC,PROD_HIER_LVL_4_DESC,GPP_DIVISION_ID   FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}}) PROD
   ON UPPER(TRIM(CONCAT('INFORXA', '~', FLR.PROD_NUM))) = UPPER(TRIM(PROD.PROD_KEY))
    AND UPPER(TRIM(PROD.SRC_SYS_KEY)) = 'INFORXA'
-- LEFT JOIN (SELECT DISTINCT CUST_NBR,CNTRY_SUBDIV_KEY,CUST_KEY,SLS_DEV_SPCL,SVC_PARTS_SLS_MGR_NM,PDM_ID,SLS_TRTRY_KEY,SRC_SYS_KEY,SBD_ENTY_NBR,HUSTLER_DLR_NBR,SBD_PRNT_ENTY,DLR_NAME,DLR_LNAME,ACC_OWNER_NM,SLS_REGN_KEY  FROM TEST_EDW.DIMENSIONS.DIM_CUSTOMER WHERE SRC_SYS_KEY='INFORXA' and SHIPTO_CUST_FLAG='N'
-- LEFT JOIN (SELECT DISTINCT CUST_NBR,CNTRY_SUBDIV_KEY,CUST_KEY,SLS_DEV_SPCL,SVC_PARTS_SLS_MGR_NM,PDM_ID,SLS_TRTRY_KEY,SRC_SYS_KEY,SBD_ENTY_NBR,HUSTLER_DLR_NBR,SBD_PRNT_ENTY,DLR_NAME,DLR_LNAME,ACC_OWNER_NM,SLS_REGN_KEY,CNTRY_KEY,DIST_ID  FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}} WHERE SRC_SYS_KEY= 'INFORXA' and SHIPTO_CUST_FLAG='N'
-- QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(CUST_NBR))  ORDER BY CUST_KEY DESC) =1) CUST
-- ON TRIM(CUST.CUST_NBR)=TRIM(FLR.CUST_NBR)
-- AND UPPER(TRIM(CUST.SRC_SYS_KEY)) = 'INFORXA'
LEFT JOIN CUST_SALESFORCE SF
ON UPPER(TRIM(SF.SBD_ENTY_NBR))=UPPER(TRIM(FLR.CUST_NBR))
LEFT JOIN
-- ( Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,SRC_SYS_KEY from PROD_EDW.DIMENSIONS.DIM_PRODUCT_LOCATION WHERE SRC_SYS_KEY='INFORXA'
( Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,SRC_SYS_KEY FROM {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}} WHERE SRC_SYS_KEY='INFORXA'
QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY))  ORDER BY PROD_KEY DESC) =1) PROD_LOC
ON UPPER(TRIM(FLR.PROD_NUM)) = UPPER(TRIM(PROD_LOC.PROD_KEY))
and PROD_LOC.SRC_SYS_KEY = 'INFORXA'
---WHERE FLR.SRC_SYS_KEY = 'INFORXA'
---AND FLR.SRC_IDENTIFIER = 'Dealer_Floor_Plan'
LEFT JOIN 
(SELECT DISTINCT PROD_KEY,PROD_HIER_LVL_7_KEY,SRC_SYS_KEY,BUS_DIV_ID,CURR_RCRD_FLAG
-- FROM PROD_EDW.CONSOLIDATED.VW_EDW_IR_PRODUCT_HIERARCHY 
FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}} 
WHERE SRC_SYS_KEY='INFORXA') PRDH
ON FLR.PROD_NUM = PRDH.PROD_KEY
AND  PRDH.CURR_RCRD_FLAG = 'Y' 
AND PRDH.BUS_DIV_ID = '1'
-- LEFT JOIN (SELECT DISTINCT PROD_FAMILY_NAME,PROD_FAMILY_LKEY,PROD_KEY,PROD_ID,SRC_SYS_KEY FROM PROD_EDW.DIMENSIONS.DIM_PRODUCT WHERE SRC_SYS_KEY='BLUEYONDER') PROD_1
   LEFT JOIN (SELECT DISTINCT PROD_FAMILY_NAME,PROD_FAMILY_LKEY,PROD_KEY,PROD_ID,SRC_SYS_KEY FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='BLUEYONDER') PROD_1

    -- ON (BILL.SRC_SYS_KEY || '~' || BILL.PROD_KEY) = PROD.PROD_KEY
    ON FLR.PROD_NUM=PROD_1.PROD_ID
 -- LEFT JOIN (SELECT DISTINCT  PROD_KEY,PRODTN_LN_NBR,SRC_SYS_KEY,CURR_RCRD_FLAG FROM TEST_EDW.CONSOLIDATED.EDW_PRODUCT )  PROD_EDW
   LEFT JOIN (SELECT DISTINCT  PROD_KEY,PRODTN_LN_NBR,SRC_SYS_KEY,CURR_RCRD_FLAG FROM {{source('CONSOLIDATED', 'EDW_PRODUCT')}})  PROD_EDW
ON FLR.PROD_NUM = PROD_EDW.PROD_KEY
    AND PROD_EDW.SRC_SYS_KEY = 'INFORXA'
    AND PROD_EDW.CURR_RCRD_FLAG='Y'
 LEFT JOIN CAL
    ON FLR.GENERATION_DTE = CAL.DY_DTE
    --ON FLR.INV_DTE = CAL.DY_DTE
    LEFT JOIN PL
    ON UPPER(TRIM(PL.PROD_NUM))=UPPER(TRIM(FLR.PROD_NUM))   
 LEFT JOIN (SELECT DISTINCT SERL_NBR,PROD_KEY,DIV_ID,INVC_NBR,PO_NBR,ORD_NBR FROM {{source('SALES_BRZ', 'BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL')}} WHERE SRC_SYS_KEY='INFORXA'
QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY)),UPPER(TRIM(SERL_NBR))  ORDER BY PROD_KEY,SERL_NBR DESC) =1)SHIP
ON UPPER(TRIM(SHIP.SERL_NBR))=UPPER(TRIM(FLR.SERIAL_NBR))
AND UPPER(TRIM(SHIP.PROD_KEY))=UPPER(TRIM(FLR.PROD_NUM))   
WHERE UPPER(TRIM(FLR.SRC_SYS_KEY)) = 'INFORXA'
AND UPPER(FLR.SRC_IDENTIFIER)= UPPER('DEALER_FLOOR_PLAN')
AND  UPPER(FLR.COUNTRY)='US'




UNION ALL


SELECT 
    'RETAIL' AS CTGY_ID,
    'FLOORPLAN' AS CTGY_TYP,
    'SALES_FLOORPLAN' AS CTGY_SHORT_NAME,
    FLR.SRC_SYS_KEY AS SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC AS PROD_CTGY,
    CAL.FYR_ID AS FYR_ID,
    -- CAL.FMTH_ID AS FMTH_ID,
    LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
    CAL.FWK_ID AS FWK_ID,
    CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
    CAL.MONTH AS PROG_MTH_ID,
    YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
    MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
	-- CASE 
 --        WHEN UPPER(CUST_EXCEL.SLS_REGN_KEY) LIKE 'S%' 
 --        THEN SUBSTR(CUST_EXCEL.SLS_REGN_KEY, 2, 1) 
 --        ELSE SUBSTR(CUST_EXCEL.SLS_REGN_KEY, 1, 1) 
 --    END AS REGN_KEY,
 --         CASE 
 --        WHEN UPPER(CUST_EXCEL.SLS_REGN_KEY) LIKE 'S%' 
 --        THEN SUBSTR(CUST_EXCEL.SLS_REGN_KEY, 2) 
 --        ELSE UPPER(CUST_EXCEL.SLS_REGN_KEY) 
 --    END AS TRTRY_KEY,
    SF.SLS_REGN_KEY AS REGN_KEY,
    SF.SLS_TRTRY_KEY AS TRTRY_KEY,
    SF.ACC_OWNER_NM AS DLR_SLS_MGR,
    SF.PDM_ID AS PDM_ID,
    SF.SLS_DEV_SPCL AS SLS_DEV_SPCL ,
    SF.DIST_ID AS DIST_ID,
    --CUST.SBD_ENTY_NBR AS SBD_ENTY_NBR,
	 -- CASE 
  --       WHEN CUST.SBD_ENTY_NBR IS NULL THEN CUST.CUST_NBR 
  --       ELSE CUST.SBD_ENTY_NBR 
  --   END AS SBD_ENTY_NBR,
    SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
    SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
    SHIP.DIV_ID AS DIV_ID,
    SF.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
    SF.DLR_NAME AS DLR_NAME,
    SF.DLR_LNAME AS DLR_LNAME,
    SF.SHIPPING_STATE_CD AS DLR_STATE,
--FLR.SHIPPING_STATE_CD AS DLR_STATE,
    FLR.COUNTRY AS DLR_CNTRY,
--    CUST.CNTRY_KEY AS DLR_CNTRY,
    PROD_EDW.PRODTN_LN_NBR AS PRODTN_LN_NBR,
    --FLR.BRAND_UU40 AS BRAND,
    PROD.Final_Brand AS BRAND,
    --CASE WHEN FLR.PROD_NUM = '181SAAY2739' THEN 'DEWALT' ELSE PROD.Final_Brand  END AS BRAND,
    PROD.PROD_FAMILY_LKEY AS PROD_LN_KEY,
    --PROD.PROD_FAMILY_NAME AS PROD_LN_DESC,
    FLR.PROD_NUM AS PROD_KEY,
    -- PROD.PROD_DESC AS PROD_DESC,
   REGEXP_REPLACE(PROD.PROD_DESC, '~*EXCEL$', '') AS PROD_DESC,  
   -- CONCAT(PROD.PROD_FAMILY_NAME,substr( PROD.PROD_DESC,8,2) ,'    ',substr( PROD.PROD_DESC,10,9)) IR_DTL_SKU,
    CASE WHEN SUBSTR(PROD.PROD_DESC,6,1)='R'
   THEN CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,6,1),' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
   ELSE CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
    END AS IR_DTL_SKU,
    CASE 
        WHEN UPPER(PROD.PROD_STAT_TYP) = 'ACT' THEN 'ACT' 
        ELSE 'INACT' 
    END AS PROD_STAT,
    NULL AS SHIP_FROM,
    NULL AS ORD_TYP,
    -- POS.QTY_ON_HAND AS QTY_ON_HAND,
    -- POS.QTY_SOLD AS QTY_SOLD,
    -- POS.QTY_ORD AS QTY_ORD,
    CASE WHEN FLR.SETTLEMENT_DTE IS NULL THEN '1' ELSE NULL END AS PROD_QTY,
   TO_DECIMAL(FLR.OUTSTANDING_AMT,30,2)AS AMOUNT,
  TO_DECIMAL (FLR.OUTSTANDING_AMT,30,2) AS AMOUNT_USD,
  TO_DECIMAL (( PROD_QTY* AMOUNT ),30,2)AS EXTND_AMT,
    --FLR.LOAN_ID AS TXN_ID,
    DATE(FLR.GENERATION_DTE) AS TXN_DTE,
  (FLR.GENERATION_DTE) AS TXN_TM,
    NULL AS TXN_EFF_DTE,
    NULL AS TXN_GL_DTE,
    NULL AS TXN_TYP,
    SHIP.PO_NBR AS PO_NBR,
    SHIP.ORD_NBR AS ORD_NBR,
    CASE WHEN TRIM(INV_NBR)='' THEN SHIP.INVC_NBR ELSE INV_NBR END AS INVC_NBR,
    FLR.SERIAL_NBR AS SERL_NBR,
    NULL AS SITE_ID,
    NULL AS LOC_ID,
    NULL AS ORD_DTE,
    NULL AS ORD_DUE_DTE,
    DATE(FLR.INV_DTE) AS INV_DTE,
    NULL AS INV_PO_DTE,
    NULL AS FULL_DUE_DTE,
    NULL AS SHIP_QTY,
    NULL AS SLS_ORD_QTY,
    --DATE(FLR.AS_OF_DTE) AS FL_PLN_AG,
    DATE(FLR.INTEREST_START_DTE) AS INTEREST_START_DTE,
     FLR.LOAN_ID AS LOAN_ID,
	FLR.CUST_NBR AS DLR_NBR,
	FLR.INTEREST_START_DTE as FREE_FLOORPLAN_END_DTE,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
 
FROM (
       SELECT *
    FROM {{source('SALES_SOURCE','VW_BRZ_DEALER_SETTLEMENTS')}} FLR
    LEFT JOIN (SELECT DISTINCT FYR_ID,FMTH_ID,DY_DTE FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}) CAL
    ON FLR.GENERATION_DTE = CAL.DY_DTE
    WHERE FLR.SRC_SYS_KEY = 'EXCEL_QADDB' 
      AND UPPER(SRC_IDENTIFIER) = 'DEALER_FLOOR_PLAN'
    QUALIFY ROW_NUMBER() OVER (
    PARTITION BY FYR_ID, FMTH_ID,SERIAL_NBR

    ORDER BY GENERATION_DTE DESC
--ORDER BY INV_DTE DESC
    ) = 1
) FLR
LEFT JOIN (
    SELECT DISTINCT PROD_KEY, SRC_SYS_KEY, ITEM_DESC,PROD_FAMILY_LKEY,PROD_FAMILY_NAME, PROD_STAT_TYP,PROD_DESC, GPP_DIVISION_DESC, PROD_HIER_LVL_4_ID,FINAL_BRAND,
    GPP_CATEGORY_DESC,GPP_DIVISION_ID FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}}
) PROD
ON UPPER(CONCAT('EXCEL_QADDB', '~', FLR.PROD_NUM)) = UPPER(TRIM(PROD.PROD_KEY))
AND UPPER(PROD.SRC_SYS_KEY) = 'EXCEL_QADDB'
-- LEFT JOIN (SELECT DISTINCT CUST_NBR,CUST_KEY,CNTRY_SUBDIV_KEY,SLS_DEV_SPCL,DLR_SLS_MGR,PDM_ID,SLS_TRTRY_KEY,SBD_PRNT_ENTY,SBD_ENTY_NBR,HUSTLER_DLR_NBR,DLR_LNAME,DLR_NAME,SRC_SYS_KEY,SLS_REGN_KEY,CNTRY_KEY,DIST_ID FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}}) CUST
--    ON UPPER(FLR.CUST_NBR) = UPPER(CUST.CUST_NBR)
--     AND UPPER(CUST.SRC_SYS_KEY) = 'EXCEL_QADDB'
LEFT JOIN CUST_SALESFORCE SF
ON UPPER(TRIM(SF.HUSTLER_DLR_NBR))=UPPER(TRIM(FLR.CUST_NBR))
  LEFT JOIN (SELECT DISTINCT PROD_KEY,PRODTN_LN_NBR,SRC_SYS_KEY,CURR_RCRD_FLAG  FROM {{source('CONSOLIDATED', 'EDW_PRODUCT')}}) AS PROD_EDW
    ON FLR.PROD_NUM = PROD_EDW.PROD_KEY
    AND PROD_EDW.SRC_SYS_KEY = 'EXCEL_QADDB'
    AND PROD_EDW.CURR_RCRD_FLAG='Y'
-- LEFT JOIN (SELECT DISTINCT * FROM PROD_EDW.DIMENSIONS.DIM_CUSTOMER) CUST_EXCEL
--    ON UPPER(FLR.CUST_NBR) = UPPER(CUST_EXCEL.CUST_NBR)
--     AND UPPER(CUST_EXCEL.SRC_SYS_KEY) = 'EXCEL_QADDB'
-- WHERE UPPER(FLR.SRC_SYS_KEY) = 'EXCEL_QADDB'
LEFT JOIN CAL
   ON FLR.GENERATION_DTE = CAL.DY_DTE
LEFT JOIN (SELECT DISTINCT SERL_NBR,PROD_KEY,DIV_ID,INVC_NBR,PO_NBR,ORD_NBR FROM {{source('SALES_BRZ', 'BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL')}} WHERE SRC_SYS_KEY='EXCEL_QADDB'
 QUALIFY  ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY)), UPPER(TRIM(SERL_NBR)) ORDER BY SERL_NBR ,PROD_KEY DESC ) = 1) SHIP
ON SHIP.SERL_NBR=FLR.SERIAL_NBR
AND SHIP.PROD_KEY=FLR.PROD_NUM
WHERE UPPER(FLR.SRC_SYS_KEY) = 'EXCEL_QADDB'
AND UPPER(FLR.SRC_IDENTIFIER) = UPPER('DEALER_FLOOR_PLAN')
AND  UPPER(FLR.COUNTRY)='US' --COMMIT
