 {{ config(
    materialized="table",
    schema='SALES',
    post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (PROD_KEY,IR_DTL_SKU,PROD_LN_KEY ,CTGY_ID, FYR_ID,FMTH_ID,BRAND,SITE_ID,LOC_KEY,PROG_MTH_ID,SUPPLY_PLND_ORD_KEY)"]	 
) }}

WITH CAL
AS (
     SELECT DY_DTE,
        MONTH(DY_DTE),YEAR(DY_DTE),
                FYR_ID,
        FMTH_ID, 
        FWK_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN FYR_ID+1 ELSE FYR_ID END AS YEAR ,
       CASE WHEN AA >12 THEN ROUND(AA-12) else ROUND(LPAD(AA,2,0)) END AS MONTH   
FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}
),
 PL AS(
select DISTINCT PLAN.PROD_KEY,A.PROD_HIER_LVL_5_DESC,
FROM (SELECT DISTINCT PROD_KEY,SRC_SYS_KEY FROM {{source('SUPPLY', 'BRZ_GLOBAL_PRODUCTION_PLAN_SCHEDULE')}} WHERE SRC_SYS_KEY='INFORXA') PLAN
LEFT JOIN
  (SELECT DISTINCT 
   PROD_KEY,PROD_HIER_LVL_5_DESC
   FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}} where SRC_SYS_KEY  = 'MTD_IAMS') A
   ON UPPER(TRIM(PLAN.PROD_KEY))= UPPER(TRIM(A.PROD_KEY)) 
WHERE PLAN.SRC_SYS_KEY = 'INFORXA'  
    )
    
    SELECT 
'PLAN' AS CTGY_ID,
'PRODUCTION' AS CTGY_TYP,
'SALES_PRODUCTION_PLAN' AS CTGY_SHORT_NAME,
PLAN.SRC_SYS_KEY AS SRC_SYS_KEY,
PROD.GPP_CATEGORY_DESC  AS PROD_CTGY,
CAL.FYR_ID AS FYR_ID,
-- CAL.FMTH_ID AS FMTH_ID,
LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
CAL.FWK_ID AS FWK_ID,
CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
CAL.MONTH AS PROG_MTH_ID,
YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
NULL AS DIV_ID,
--PROD.PRODTN_LN_NBR AS PRODTN_LN_NBR,
--PROD.BRAND_LKEY AS BRAND,
PROD.Final_Brand AS BRAND,
 PL.PROD_HIER_LVL_5_DESC AS PROD_LN_KEY,
 --PRD.PROD_FAMILY_NAME AS PROD_LN_DESC,
PLAN.PROD_KEY AS PROD_KEY,
PROD.PROD_DESC AS PROD_DESC,
PRDH.PROD_HIER_LVL_7_KEY AS IR_DTL_SKU,
--PRD_LOC.PROD_STAT_DESC as PROD_STAT,
	 CASE 
    WHEN TRIM(UPPER(PRD_LOC.PROD_STAT_DESC )) = 'ACTIVE' THEN 'ACT'
    WHEN TRIM(UPPER(PRD_LOC.PROD_STAT_DESC )) = 'SUPPRESSED (INACTIVE)' THEN 'INACT'
    ELSE  PRD_LOC.PROD_STAT_DESC 
  END AS PROD_STAT,
TO_DECIMAL(PLAN.PLND_ORD_QTY ,30,2)AS PROD_QTY,
   TO_DECIMAL(PRD_CST.TOT_COST_AMT,30,2) AS AMOUNT_USD,
 TO_DECIMAL((PROD_QTY * AMOUNT_USD ),30,2)AS EXTND_AMT,
-- NET_AMT_USDNET_AMT_USD --( Currency conversion required)
-- NET_DCRNCY_AMT
-- EXTND_AMT
-- TXN_DTE
-- TXN_TM
-- TXN_EFF_DTE
-- TXN_GL_DTE
-- TXN_TYP
PLAN.LOC_KEY AS SITE_ID,
LOC.LOC_KEY AS LOC_KEY,
PLAN.SUPPLY_PLND_ORD_KEY AS SUPPLY_PLND_ORD_KEY,
PROD_EDW.PRODTN_LN_NBR,
NULL AS LOAN_ID,
PRDLKP.PROD_BRAND  AS BRAND_UU40,
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
FROM -- DISTINCT PLAN.SRC_SYS_KEY,PROD.SRC_SYS_KEY FROM
( SELECT * FROM  {{source('SUPPLY', 'BRZ_GLOBAL_PRODUCTION_PLAN_SCHEDULE')}} WHERE SRC_SYS_KEY='INFORXA') PLAN  --359140
LEFT JOIN ( SELECT * FROM  {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='INFORXA') PROD
ON PROD.PROD_KEY=CONCAT(PLAN.SRC_SYS_KEY,'~',UPPER(TRIM(PLAN.PROD_KEY)))
LEFT JOIN CAL
ON PLAN.DMD_FULFIL_DTE=CAL.DY_DTE 
LEFT JOIN (SELECT LOC_KEY,PROD_KEY,TOT_COST_AMT FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_COST')}}
WHERE UPPER(TRIM(SRC_SYS_KEY))='INFORXA' AND COST_TYP = 'Plant Costing') PRD_CST
ON PLAN.PROD_KEY=PRD_CST.prod_key
AND PLAN.LOC_KEY=PRD_CST.LOC_KEY
LEFT JOIN (SELECT DISTINCT PROD_KEY,PROD_HIER_LVL_7_KEY,BUS_DIV_ID,SRC_SYS_KEY,CURR_RCRD_FLAG,PROD_HIER_LVL_4_DESC,PROD_HIER_LVL_5_KEY
  FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}} WHERE SRC_SYS_KEY='INFORXA')  PRDH
ON PLAN.PROD_KEY = PRDH.PROD_KEY 
AND  PRDH.CURR_RCRD_FLAG = 'Y' 
AND PRDH.BUS_DIV_ID = '1' 
LEFT JOIN (
SELECT DISTINCT PROD_KEY,PROD_STAT_LKEY,PROD_STAT_DESC,PROD_LOC_LOV.PROD_LOC_KEY FROM 
(Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,SRC_SYS_KEY from {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}} WHERE SRC_SYS_KEY='INFORXA'
	QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY))  ORDER BY PROD_KEY DESC) =1) PROD_LOC
	 LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION_LOV')}} PROD_LOC_LOV
	 on CONCAT(PROD_LOC.PROD_LOC_KEY,'~','E') = PROD_LOC_LOV.PROD_LOC_KEY
    ) PRD_LOC
 ON PRD_LOC.PROD_KEY=PLAN.PROD_KEY
LEFT JOIN  
{{source('CONSOLIDATED_PROD', 'VW_EDW_LOCATION')}} LOC
ON UPPER(LOC.LOC_KEY)=UPPER(PLAN.LOC_KEY)
AND LOC.SRC_SYS_KEY='INFORXA'
LEFT JOIN ( SELECT * FROM  {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='BLUEYONDER') PRD
ON UPPER(TRIM(PRD.PROD_ID))=UPPER(TRIM(PLAN.PROD_KEY))
LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} PROD_EDW
    ON PLAN.PROD_KEY = PROD_EDW.PROD_KEY
    AND PROD_EDW.SRC_SYS_KEY = 'INFORXA'
    AND PROD_EDW.CURR_RCRD_FLAG='Y'
LEFT JOIN PROD_EDW.CONSOLIDATED.VW_EDW_PRODUCT_LOOKUP PRDLKP
    ON UPPER(TRIM(PLAN.PROD_KEY))=UPPER(TRIM(PRDLKP.PROD_LKP_KEY))
    AND PRDLKP.SRC_SYS_KEY='INFORXA'
    LEFT JOIN PL
    ON UPPER(TRIM(PL.PROD_KEY))=UPPER(TRIM(PLAN.PROD_KEY))
AND  PLAN.SRC_SYS_KEY='INFORXA'
    

UNION ALL

    SELECT
'PLAN' AS CTGY_ID,
'PRODUCTION' AS CTGY_TYP,
'SALES_PRODUCTION_PLAN' AS CTGY_SHORT_NAME,
PLAN.SRC_SYS_KEY AS SRC_SYS_KEY,
PROD.GPP_CATEGORY_DESC  AS PROD_CTGY,
CAL.FYR_ID AS FYR_ID,
-- CAL.FMTH_ID AS FMTH_ID,
LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
CAL.FWK_ID AS FWK_ID,
CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
CAL.MONTH AS PROG_MTH_ID,
YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
NULL AS DIV_ID,
--PROD.PRODTN_LN_NBR AS PRODTN_LN_NBR,
--PROD.BRAND_LKEY AS BRAND,
 PROD.Final_Brand  AS BRAND,
 --CASE WHEN PLAN.PROD_KEY = '181SAAY2739' THEN 'DEWALT' ELSE PROD.Final_Brand  END AS BRAND,
PROD.PROD_FAMILY_LKEY AS PROD_LN_KEY,
--PROD.PROD_FAMILY_NAME AS PROD_LN_DESC,
PLAN.PROD_KEY AS PROD_KEY,
-- PROD.PROD_DESC AS PROD_DESC,
REGEXP_REPLACE(PROD.PROD_DESC, '~*EXCEL$', '') AS PROD_DESC,  
-- CONCAT(PROD.PROD_FAMILY_NAME,substr( PROD.PROD_DESC,8,2) ,'    ',substr( PROD.PROD_DESC,10,9)) IR_DTL_SKU,
CASE WHEN SUBSTR(PROD.PROD_DESC,6,1)='R'
THEN CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,6,1),' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
ELSE CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
END AS IR_DTL_SKU,
CASE 
        WHEN (PROD.PROD_STAT_TYP) = 'ACT' THEN 'ACT'
        ELSE 'INACT' 
    END AS PROD_STAT,
TO_DECIMAL(PLAN.PLND_ORD_QTY,30,2) AS PROD_QTY,
TO_DECIMAL(PRD_CST.CURR_STD_COST,30,2) AS AMOUNT_USD, 
-- NET_DCRNCY_AMT
 TO_DECIMAL((PROD_QTY * AMOUNT_USD),30,2) AS EXTND_AMT,
-- TXN_DTE
-- TXN_TM
-- TXN_EFF_DTE
-- TXN_GL_DTE
-- TXN_TYP
PLAN.LOC_KEY AS SITE_ID,
LOC.LOC_NAME AS LOC_KEY,
PLAN.SUPPLY_PLND_ORD_KEY AS SUPPLY_PLND_ORD_KEY,
PROD_EDW.PRODTN_LN_NBR,
NULL AS LOAN_ID,
NULL AS BRAND_UU40,
CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
from 
( SELECT * FROM {{source('SUPPLY', 'BRZ_GLOBAL_PRODUCTION_PLAN_SCHEDULE')}} WHERE SRC_SYS_KEY='EXCEL_QADDB') PLAN 
LEFT JOIN ( SELECT * FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='EXCEL_QADDB') PROD
ON TRIM(PROD.PROD_ID)=TRIM(PLAN.PROD_KEY)
LEFT JOIN CAL
ON PLAN.DMD_FULFIL_DTE=CAL.DY_DTE
LEFT JOIN (SELECT LOC_KEY,PROD_KEY,CURR_STD_COST FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_COST')}}
WHERE UPPER(TRIM(SRC_SYS_KEY))='EXCEL_QADDB' AND SUBSTR(prod_cost_key,1,7) ='CURRENT') PRD_CST
ON TRIM(PLAN.PROD_KEY)=TRIM(PRD_CST.prod_key)
AND TRIM(PLAN.LOC_KEY)=TRIM(PRD_CST.LOC_KEY)
LEFT JOIN  
{{source('CONSOLIDATED_PROD', 'VW_EDW_LOCATION')}} LOC
ON UPPER(LOC.LOC_KEY)=UPPER(PLAN.LOC_KEY)
AND LOC.SRC_SYS_KEY='EXCEL_QADDB'
LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} PROD_EDW
    ON TRIM(PLAN.PROD_KEY) = TRIM(PROD_EDW.PROD_KEY)
    AND TRIM(PROD_EDW.SRC_SYS_KEY) = 'EXCEL_QADDB'
    AND TRIM(PROD_EDW.CURR_RCRD_FLAG)='Y'
WHERE PLAN.SRC_SYS_KEY='EXCEL_QADDB'
