{{ config(
    materialized="table",
    schema='SALES',
    post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (INVC_NBR,LOC_ID,INV_DTE,SERL_NBR,DIV_ID,DIST_ID,TRTRY_KEY,REGN_KEY,SBD_ENTY_NBR,PROD_KEY,PROD_DESC,INVC_LN_KEY)"]
) }}

WITH CAL
AS (
     SELECT DY_DTE,
        MONTH(DY_DTE),YEAR(DY_DTE),
                FYR_ID,
        FMTH_ID, 
        FWK_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN FYR_ID+1 ELSE FYR_ID END AS YEAR ,
       CASE WHEN AA >12 THEN ROUND(AA-12) else ROUND(LPAD(AA,2,0)) END AS MONTH   
 FROM PROD_EDW.DIMENSIONS.DIM_FISCAL_CALENDAR
),

CUST_SALESFORCE AS (
    SELECT
        CUST.PDM_ID,
        CUST.SLS_DEV_SPCL,
        CUST.DIST_ID,
        CUST.SBD_ENTY_NBR,
        CUST.SBD_PRNT_ENTY,
        CUST.HUSTLER_DLR_NBR,
        CUST.DLR_NAME,
        CUST.DLR_LNAME,
        CUST.SHIPPING_STATE_CD,
	        CUST.SLS_REGN_KEY,
        CUST.SLS_TRTRY_KEY,
        CUST.ACC_OWNER_NM,
        CUST.CNTRY_KEY
       FROM TEST_EDW.DIMENSIONS.DIM_CUSTOMER CUST
       WHERE CUST.SRC_SYS_KEY='MTD_SALESFORCE' 
       ),
        CUST AS(
SELECT DISTINCT
        SPLIT_PART(CUST.CUST_KEY,'~',3) AS DIV_ID,
        CUST.CUST_NBR,
        CUST.SLS_REGN_KEY,
        CUST.SLS_TRTRY_KEY,
        CUST.ACC_OWNER_NM,
        CUST.CNTRY_KEY,
        UPPER(TRIM(CUST_LOV.CUST_ACCT_GRP_DESC)) AS CUST_ACCT_GRP_DESC
FROM TEST_EDW.DIMENSIONS.DIM_CUSTOMER  CUST
LEFT JOIN PROD_EDW.DIMENSIONS.DIM_CUSTOMER_LOV CUST_LOV 
      ON CUST.CUST_KEY || '~' || 'E' = CUST_LOV.CUST_KEY
WHERE CUST.SRC_SYS_KEY='INFORXA' 
AND LENGTH(CUST.CUST_KEY) - LENGTH(REPLACE(CUST.CUST_KEY, '~', '')) = 2
--AND SUBSTR(CUST.CUST_KEY, 16, 2) = '36'
--AND UPPER(TRIM(CUST_LOV.CUST_ACCT_GRP_DESC))='CENTRAL DISTRIBUTORS'
),


SERIAL AS(
SELECT DISTINCT CASE 
        WHEN TRIM(L.value) IS NULL OR TRIM(L.value) = '' THEN '#'
        ELSE TRIM(L.value)
        END AS SERL_NBR,
	--TRIM(L.value) AS SERL_NBR,
	PROD_KEY,INVC_NBR,INVC_DOC_LN_NBR
FROM  PROD_MARTS.SALES.BRZ_SALES_BILLING_AMERICAS2_OUTDOOR BILL,
LATERAL FLATTEN(input => 
    CASE 
      WHEN TRIM(BILL.LOT_SERL_NBR) = ',' THEN ARRAY_CONSTRUCT('#')  -- SKS
      WHEN BILL.LOT_SERL_NBR IS NULL THEN ARRAY_CONSTRUCT('#') 
      ELSE SPLIT(BILL.LOT_SERL_NBR, ',')
    END 
) L
WHERE BILL.SRC_SYS_KEY = 'EXCEL_QADDB'
 -- AND BILL.SLS_ORD_TYP_CD IN ('WD', 'WG', 'WB', 'XB', 'WV', 'RG', 'ST', 'SP') 
 AND BILL.SLS_ORD_TYP_CD IN ('WD', 'WG', 'WB', 'XB', 'WV') 
  ),
  RAM AS (
    SELECT DISTINCT 
        BILL.PROD_KEY,
        A.PROD_HIER_LVL_5_DESC
    FROM (
        SELECT DISTINCT 
            PROD_KEY, DIV_ID, SRC_SYS_KEY 
        FROM PROD_MARTS.SALES.BRZ_SALES_BILLING_AMERICAS2_OUTDOOR
    ) BILL
    LEFT JOIN (
        SELECT DISTINCT 
            PROD_KEY, PROD_HIER_LVL_5_DESC
        FROM PROD_EDW.CONSOLIDATED.VW_EDW_PRODUCT_HIERARCHY
        WHERE SRC_SYS_KEY = 'MTD_IAMS'
    ) A 
        ON BILL.PROD_KEY = A.PROD_KEY
    WHERE BILL.SRC_SYS_KEY = 'INFORXA'
      AND BILL.DIV_ID IN ('36','39','52','38')
)
,
SHIP_INFORXA AS(
SELECT
    'SALES' AS CTGY_ID,
    'SHIPMENT' AS CTGY_TYP,
    'SALES_SHIPMENT' AS CTGY_SHORT_NAME,
    SHIP.SRC_SYS_KEY  AS SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC  AS PROD_CTGY,
    CAL.FYR_ID AS FYR_ID,
    LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
  CAL.FWK_ID AS FWK_ID,
  CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
  CAL.MONTH AS PROG_MTH_ID,
  YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
  MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,  
 SF.SLS_REGN_KEY  AS REGN_KEY,
 SF.SLS_TRTRY_KEY  AS TRTRY_KEY,
    SF.ACC_OWNER_NM  AS DLR_SLS_MGR,
    SF.PDM_ID AS PDM_ID,
    SF.SLS_DEV_SPCL AS SLS_DEV_SPCL,
    SF.DIST_ID AS DIST_ID,
	 -- CASE 
  --       WHEN SF.SBD_ENTY_NBR IS NULL THEN CUST.CUST_NBR 
  --       ELSE SF.SBD_ENTY_NBR 
  --   END AS SBD_ENTY_NBR,
	SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
    SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
    CAST(SHIP.DIVISION AS VARCHAR) AS DIV_ID,
    --PROD.GPP_DIVISION_ID AS DIV_ID,
    SF.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
    SF.DLR_NAME AS DLR_NAME,
    SF.DLR_LNAME AS DLR_LNAME,
    SF.SHIPPING_STATE_CD AS DLR_STATE,
    --SF.CNTRY_KEY AS DLR_CNTRY,
CASE WHEN UPPER(SF.CNTRY_KEY) IN ('UNITED STATES','US','U.S.A.','U.S.','USA','COLUMBIANA','DELAWARE') THEN 'US'
ELSE NULL
END AS DLR_CNTRY,
    EDW_PROD.PRODTN_LN_NBR AS PRODTN_LN_NBR,
    --SHIP.PRODUCTION_LINE AS PRODTN_LN_NBR,
    PROD.Final_Brand AS BRAND,
    SHIP.SERIES AS PROD_LN_KEY,
    --PROD_1.PROD_FAMILY_NAME AS PROD_LN_DESC,
    CAST(SHIP.MODEL_NUMBER AS VARCHAR(256)) AS PROD_KEY,
    SHIP.PROD_DESC,
    PRDH.PROD_HIER_LVL_7_KEY AS IR_DTL_SKU,
    CASE WHEN PROD_LOC.PROD_STAT_LKEY='A' THEN 'ACT' ELSE 'INACT' END AS PROD_STAT,
    SHIP.LOCAL_WAREHOUSE AS SHIP_FROM,
    NULL AS ORD_TYP,
    SHIP.SERIAL_NUMBER AS SERL_NBR,
    CASE WHEN SHIP.SERIAL_NUMBER IS NOT NULL THEN '1' ELSE '0' END AS INV_QTY,
    TO_DECIMAL(SHIP.UNIT_PRC,30,2) AS AMOUNT,
    -- NULL AS NET_AMT_USD,
   CASE WHEN SHIP.SERIAL_NUMBER IS NOT NULL THEN  TO_DECIMAL(AMOUNT,30,2) ELSE 0 END AS AMOUNT_USD,
    TO_DECIMAL ((INV_QTY * AMOUNT_USD),30,2 ) AS EXTND_AMT,
    --NULL AS TXN_ID,
    DATE(SHIP.GL_POST_DTE) AS TXN_DTE,
    NULL AS TXN_TM,
    NULL AS TXN_EFF_DTE,
    DATE(SHIP.GL_POST_DTE) AS TXN_GL_DTE,
    NULL AS TXN_TYP,
    NULL AS PO_NBR,
    TRIM(SHIP.INVC_NBR) AS INVC_NBR,
    SHIP.LOCAL_WAREHOUSE AS SITE_ID,
    NULL AS LOC_ID,
    NULL AS ORD_DTE,
    NULL AS INV_DTE,
    NULL AS INV_PO_DTE,
    NULL AS FULL_DUE_DTE,
    NULL AS SHIP_QTY,
    NULL AS SLS_ORD_QTY,
    NULL AS CAL_ON_TIME_FULL,
    NULL  AS INVC_LN_NBR,
    SHIP.SHIP_LOCATION_IDENTIFER AS SHIP_LOC_ID,
    SHIP.CARTON_NBR AS CARTON_NBR,
	NULL AS INVC_LN_KEY,
	NULL AS  SHIPPED_USD,
	SHIP.QUOTE_ORDER_NUMBER AS ORD_NBR,
	NULL  AS ORD_LN_NBR,
	NULL AS LOAN_ID,
    CUST.CUST_ACCT_GRP_DESC,
     NULL AS FINANCE_TERMS_CD,
	SHIP.CUST_NBR AS DLR_NBR,
	PRDLKP.PROD_BRAND  AS BRAND_UU40,
        SLS_ORD_FROM_WHSE_KEY,
    CREDIT_RESN_LN,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE 

FROM (SELECT DISTINCT 'INFORXA' AS SRC_SYS_KEY,* FROM  TEST_MARTS.PRODUCT.VW_BRZ_PRODUCT_SERIAL_NUMBER_PKMS_SHIPMENT_DETAILS
--TEST_MARTS.PRODUCT.VW_BRZ_PRODUCT_SERIAL_NUMBER_PKMS_SHIPMENT_DETAILS  
WHERE (DIVISION IN ('36', '39', '38') 
 OR (DIVISION ='52' AND CUST_NBR NOT IN ('8033', '16386', '13931')))
  ) SHIP --2840548

       LEFT JOIN CUST_SALESFORCE SF
ON SF.SBD_ENTY_NBR=SHIP.CUST_NBR

LEFT JOIN CUST 
ON UPPER(TRIM(SHIP.CUST_NBR)) = UPPER(TRIM(CUST.CUST_NBR)) 
AND UPPER(TRIM(SHIP.DIVISION))=UPPER(TRIM(CUST.DIV_ID))

LEFT JOIN PROD_EDW.DIMENSIONS.DIM_PRODUCT PROD
    ON SHIP.SRC_SYS_KEY = PROD.SRC_SYS_KEY
    AND SHIP.MODEL_NUMBER = SPLIT_PART(PROD.PROD_KEY, '~', 2)

    LEFT JOIN PROD_EDW.CONSOLIDATED.VW_EDW_IR_PRODUCT_HIERARCHY PRDH
    ON SHIP.MODEL_NUMBER = PRDH.PROD_KEY
    AND PRDH.SRC_SYS_KEY = 'INFORXA'
    AND PRDH.BUS_DIV_ID = '1'

    LEFT JOIN (
    SELECT DISTINCT 
        PROD_STAT_LKEY,
        PROD_LOC_KEY,
        CNTRY_OF_ORIG_KEY,
        PROD_KEY,
        SRC_SYS_KEY
    FROM PROD_EDW.DIMENSIONS.DIM_PRODUCT_LOCATION
    WHERE SRC_SYS_KEY = 'INFORXA'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY)) ORDER BY PROD_KEY DESC) = 1
) PROD_LOC
    ON UPPER(TRIM(SHIP.MODEL_NUMBER)) = UPPER(TRIM(PROD_LOC.PROD_KEY))
    AND PROD_LOC.SRC_SYS_KEY = 'INFORXA'
LEFT JOIN  PROD_EDW.CONSOLIDATED.VW_EDW_PRODUCT_LOOKUP PRDLKP
    ON UPPER(TRIM(SHIP.MODEL_NUMBER))=UPPER(TRIM(PRDLKP.PROD_LKP_KEY))
    AND PRDLKP.SRC_SYS_KEY='INFORXA'

    LEFT JOIN (
    SELECT DISTINCT 
        PROD_FAMILY_NAME,
        PROD_FAMILY_LKEY,
        PROD_KEY, 
        PROD_ID, 
        SRC_SYS_KEY 
    FROM PROD_EDW.DIMENSIONS.DIM_PRODUCT
    WHERE SRC_SYS_KEY = 'BLUEYONDER'
) PROD_1
    ON SHIP.MODEL_NUMBER = PROD_1.PROD_ID

LEFT JOIN CAL
    ON SHIP.GL_POST_DTE = CAL.DY_DTE

LEFT JOIN TEST_EDW.CONSOLIDATED.VW_EDW_PRODUCT AS EDW_PROD
    ON UPPER(TRIM(SHIP.MODEL_NUMBER)) = UPPER(TRIM(EDW_PROD.PROD_KEY))
    AND EDW_PROD.SRC_SYS_KEY = 'INFORXA' 
    AND EDW_PROD.CURR_RCRD_FLAG = 'Y'

LEFT JOIN 
(SELECT DISTINCT SLS_ORD_FROM_WHSE_KEY,CREDIT_RESN_LN,INVC_NBR,ORD_NBR,PROD_KEY FROM TEST_MARTS.SALES.BRZ_SALES_BILLING_INDEPENDENT_RETAIL WHERE SRC_SYS_KEY='INFORXA') BILL
ON TRIM(SHIP.INVC_NBR)=TRIM(BILL.INVC_NBR)
AND TRIM(SHIP.QUOTE_ORDER_NUMBER)=TRIM(BILL.ORD_NBR)
AND TRIM(MODEL_NUMBER) = TRIM(BILL.PROD_KEY) 
)

,
BILLING_INFORXA AS (
SELECT
'SALES' AS CTGY_ID,
'SHIPMENT' AS CTGY_TYP,
'SALES_SHIPMENT' AS CTGY_SHORT_NAME,
SRC_SYS_KEY,
PROD_CTGY,
FYR_ID,
FMTH_ID,
FWK_ID,
PROG_YR_ID,
PROG_MTH_ID,
CLNDR_YR_ID,
CLNDR_MTH_ID,
REGN_KEY,
TRTRY_KEY,
DLR_SLS_MGR,
PDM_ID,
SLS_DEV_SPCL,
DIST_ID,
SBD_ENTY_NBR,
SBD_PRNT_ENTY,
DIV_ID,
HUSTLER_DLR_NBR,
DLR_NAME,
DLR_LNAME,
DLR_STATE,
DLR_CNTRY,
PRODTN_LN_NBR,
BRAND,
PROD_LN_KEY,
PROD_KEY,
PROD_DESC,
IR_DTL_SKU,
PROD_STAT,
SHIP_FROM,
ORD_TYP,
SERL_NBR,
INV_QTY,
AMOUNT,
AMOUNT_USD,
EXTND_AMT,
TXN_DTE,
TXN_TM,
TXN_EFF_DTE,
TXN_GL_DTE,
TXN_TYP,
PO_NBR,
INVC_NBR,
SITE_ID,
LOC_ID,
ORD_DTE,
INV_DTE,
INV_PO_DTE,
FULL_DUE_DTE,
SHIP_QTY,
SLS_ORD_QTY,
CAL_ON_TIME_FULL,
INVC_LN_NBR,
NULL AS SHIP_LOC_ID,
NULL AS CARTON_NBR,
INVC_LN_KEY,
NULL AS SHIPPED_USD,
ORD_NBR,
ORD_LN_NBR,
LOAN_ID,
NULL AS CUST_ACCT_GRP_DESC,
NULL AS FINANCE_TERMS_CD,
DLR_NBR,
BRAND_UU40,
        SLS_ORD_FROM_WHSE_KEY,
    CREDIT_RESN_LN,
BRZ_REF_DTE
FROM (
    SELECT 
    *
    FROM TEST_MARTS.SALES.BRZ_SALES_BILLING_INDEPENDENT_RETAIL 
    WHERE SRC_SYS_KEY = 'INFORXA'
) BILL
WHERE NOT EXISTS (
    SELECT 1
    FROM TEST_MARTS.PRODUCT.VW_BRZ_PRODUCT_SERIAL_NUMBER_PKMS_SHIPMENT_DETAILS SHIP
    WHERE TRIM(SHIP.INVC_NBR) = TRIM(BILL.INVC_NBR)
      AND TRIM(SHIP.QUOTE_ORDER_NUMBER) = TRIM(BILL.ORD_NBR)
      AND TRIM(SHIP.MODEL_NUMBER) = TRIM(BILL.PROD_KEY)
)
),
FINAL_INFORXA AS(
select * from SHIP_INFORXA
UNION ALL
select * from BILLING_INFORXA)

,EXCEL_BILLING AS(
SELECT
    'SALES' AS CTGY_ID,
    'SHIPMENT' AS CTGY_TYP,
    'SALES_SHIPMENT' AS CTGY_SHORT_NAME,
    BILL.SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC  AS PROD_CTGY,
  CAL.FYR_ID AS FYR_ID,
 LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
  CAL.FWK_ID AS FWK_ID,
  CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
  CAL.MONTH AS PROG_MTH_ID,
  YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
  MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
--  CASE
--    WHEN UPPER(BILL.SOLDTO_CUST_SLS_REGN_KEY) LIKE 'S%' THEN SUBSTR(BILL.SOLDTO_CUST_SLS_REGN_KEY, 2, 1)
--          ELSE SUBSTR(BILL.SOLDTO_CUST_SLS_REGN_KEY, 1, 1)
--         END AS REGN_KEY,
-- CASE
--         WHEN UPPER(BILL.SOLDTO_CUST_SLS_REGN_KEY) LIKE 'S%' THEN SUBSTR(BILL.SOLDTO_CUST_SLS_REGN_KEY, 2)
--         ELSE BILL.SOLDTO_CUST_SLS_REGN_KEY
--         END  AS TRTRY_KEY,
	SF.SLS_REGN_KEY AS REGN_KEY,
	SF.SLS_TRTRY_KEY AS TRTRY_KEY,
    SF.ACC_OWNER_NM AS DLR_SLS_MGR,
    SF.PDM_ID AS PDM_ID,
    SF.SLS_DEV_SPCL AS SLS_DEV_SPCL,
    SF.DIST_ID AS DIST_ID,
   SF.SBD_ENTY_NBR  AS SBD_ENTY_NBR,
	 -- CASE 
  --       WHEN CUST.SBD_ENTY_NBR IS NULL THEN CUST_EXCEL.CUST_NBR 
  --       ELSE CUST.SBD_ENTY_NBR 
  --   END AS SBD_ENTY_NBR,
    SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
     NULL   AS DIV_ID,
    SF.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
    SF.DLR_NAME AS DLR_NAME,
    SF.DLR_LNAME AS DLR_LNAME,
    SF.SHIPPING_STATE_CD AS DLR_STATE,
   CASE WHEN UPPER(SF.CNTRY_KEY) IN ('UNITED STATES','US','U.S.A.','U.S.','USA','COLUMBIANA','DELAWARE') THEN 'US'
       ELSE NULL
     END AS DLR_CNTRY,
    EDW_PROD.PRODTN_LN_NBR AS PRODTN_LN_NBR,
    PROD.Final_Brand  AS BRAND,
     --CASE WHEN BILL.PROD_KEY = '181SAAY2739' THEN 'DEWALT' ELSE PROD.Final_Brand  END AS BRAND,
    PROD.PROD_FAMILY_LKEY AS PROD_LN_KEY,
    --PROD.PROD_FAMILY_NAME AS PROD_LN_DESC,
    CAST(BILL.PROD_KEY AS VARCHAR(256)) AS PROD_KEY,
    -- PROD.PROD_DESC AS PROD_DESC,
   REGEXP_REPLACE(PROD.PROD_DESC, '~*EXCEL$', '') AS PROD_DESC,  
   --CONCAT(PROD.PROD_FAMILY_NAME,substr( PROD.PROD_DESC,8,2) ,'    ',substr( PROD.PROD_DESC,10,9)) IR_DTL_SKU,
CASE WHEN SUBSTR(PROD.PROD_DESC,6,1)='R'
THEN CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,6,1),' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
ELSE CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
END AS IR_DTL_SKU,
      CASE 
        WHEN (PROD.PROD_STAT_TYP) = 'ACT' THEN 'ACT'
        ELSE 'INACT' 
    END AS PROD_STAT,
    BILL.SLS_ORD_FROM_WHSE_NAME AS SHIP_FROM,
    BILL.SLS_ORD_TYP_CD AS ORD_TYP,
    BILL.SERL_NBR,
     1 AS  INV_QTY,
    --TO_DECIMAL(BILL.SLS_INVC_ACT_QTY) AS INV_QTY,
    --TO_DECIMAL(BILL.NET_DCRNCY_AMT) AS AMOUNT,
    TO_DECIMAL(CASE WHEN BILL.SLS_INVC_ACT_QTY ='0' OR BILL.SLS_INVC_ACT_QTY IS NULL THEN NULL
    ELSE (TO_DECIMAL(BILL.NET_DCRNCY_AMT)/TO_DECIMAL(BILL.SLS_INVC_ACT_QTY))
    END,30,2) AS AMOUNT,
    TO_DECIMAL(CASE WHEN BILL.SLS_INVC_ACT_QTY ='0' OR BILL.SLS_INVC_ACT_QTY IS NULL THEN NULL
    ELSE (TO_DECIMAL(BILL.NET_DCRNCY_AMT_USD)/TO_DECIMAL(BILL.SLS_INVC_ACT_QTY))
    END,30,2) AS AMOUNT_USD,
  -- CASE WHEN SHIP.SERIAL_NUMBER IS NOT NULL THEN TO_DECIMAL(AMOUNT,30,2) ELSE 0 END AS AMOUNT_USD,
    --CAST(BILL.SLS_INVC_ACT_QTY * BILL.NET_DCRNCY_AMT AS VARCHAR) AS EXTND_AMT,
    -- 1 * (CASE WHEN BILL.SLS_INVC_ACT_QTY ='0' OR BILL.SLS_INVC_ACT_QTY IS NULL THEN NULL
    -- ELSE (TO_DECIMAL(BILL.NET_DCRNCY_AMT)/TO_DECIMAL(BILL.SLS_INVC_ACT_QTY))
    -- END,30,2) AS EXTND_AMT,
    TO_DECIMAL((INV_QTY*AMOUNT),30,2) AS EXTND_AMT,
    --BILL.SLS_ORD_NBR AS TXN_ID,
    BILL.SLS_ORD_CREATE_DTE AS TXN_DTE,
    BILL.SLS_ORD_CREATE_DTE AS TXN_TM,
    NULL AS TXN_EFF_DTE,
    NULL AS TXN_GL_DTE,
    NULL AS TXN_TYP,
    BILL.CUST_PO_NBR AS PO_NBR,
    TRIM(BILL.INVC_NBR) AS INVC_NBR,
    BILL.SHIP_LOC_KEY AS SITE_ID,
    BILL.SHIP_LOC_ID AS LOC_ID,
    DATE(BILL.SLS_ORD_CREATE_DTE) AS ORD_DTE,
    DATE(BILL.SLS_INVC_BILL_DTE) AS INV_DTE,
    DATE(BILL.CUST_PO_DTE) AS INV_PO_DTE,
    DATE(BILL.SVC_LVL_DLV_DTE) AS FULL_DUE_DTE,
    BILL.SHIP_QTY AS SHIP_QTY,
    BILL.SLS_ORD_QTY AS SLS_ORD_QTY,
    CASE
        WHEN BILL.SLS_DLV_DTE >= BILL.SLS_ORD_CREATE_DTE AND BILL.SHIP_QTY <= BILL.SLS_ORD_QTY THEN 'IN_FULL'
        ELSE 'NOT_IN_FULL'
    END AS CAL_ON_TIME_FULL,
    BILL.INVC_DOC_LN_NBR AS INVC_LN_NBR,
    NULL AS SHIP_LOC_ID,
    NULL AS CARTON_NBR,
    BILL.SLS_INVC_LN_KEY  AS INVC_LN_KEY,
    BILL.SHIPED_DCRNCY_AMT_USD AS  SHIPPED_USD ,
	BILL.SLS_ORD_NBR AS ORD_NBR,
	BILL.SLS_ORD_LN_NBR AS ORD_LN_NBR,
	NULL AS LOAN_ID,
    NULL AS CUST_ACCT_GRP_DESC,
    BILL.FINANCE_TERMS_CD,
	BILL.SOLDTO_CUST_NBR AS DLR_NBR,
	NULL AS BRAND_UU40,
            SLS_ORD_FROM_WHSE_KEY,
    CREDIT_RESN_LN,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
    FROM (
      SELECT BILL.*,S.SERL_NBR 
      FROM PROD_MARTS.SALES.BRZ_SALES_BILLING_AMERICAS2_OUTDOOR  BILL
      LEFT JOIN SERIAL S
      ON S.PROD_KEY=BILL.PROD_KEY
      AND S.INVC_NBR=BILL.INVC_NBR
      AND S.INVC_DOC_LN_NBR=BILL.INVC_DOC_LN_NBR
      WHERE BILL.SRC_SYS_KEY = 'EXCEL_QADDB'
      AND BILL.SLS_ORD_TYP_CD IN ('WD', 'WG', 'WB', 'XB', 'WV', 'RG', 'ST', 'SP') ) BILL
      LEFT JOIN PROD_EDW.DIMENSIONS.DIM_PRODUCT  PROD
    ON (BILL.SRC_SYS_KEY || '~' || BILL.PROD_KEY) = PROD.PROD_KEY
    AND PROD.SRC_SYS_KEY='EXCEL_QADDB'
-- LEFT JOIN TEST_EDW.DIMENSIONS.DIM_CUSTOMER CUST
--     ON (BILL.SRC_SYS_KEY || '~' || BILL.SOLDTO_CUST_KEY) = CUST.CUST_KEY
-- 	LEFT JOIN (
--     SELECT DISTINCT HUSTLER_DLR_NBR,PDM_ID,SLS_DEV_SPCL,SBD_ENTY_NBR,SBD_PRNT_ENTY,DLR_NAME,DLR_LNAME,
-- 	CNTRY_KEY,DLR_SLS_MGR,ACC_OWNER_NM,CUST_NBR,CNTRY_SUBDIV_KEY,DIST_ID 
--     FROM TEST_EDW.DIMENSIONS.DIM_CUSTOMER 
--     WHERE SRC_SYS_KEY = 'MTD_SALESFORCE'
-- ) CUST
	LEFT JOIN CUST_SALESFORCE SF
	ON BILL.SOLDTO_CUST_KEY = SF.HUSTLER_DLR_NBR
LEFT JOIN CAL
    ON BILL.SLS_INVC_BILL_DTE = CAL.DY_DTE

 LEFT JOIN TEST_EDW.CONSOLIDATED.VW_EDW_PRODUCT AS EDW_PROD
 ON BILL.PROD_KEY = EDW_PROD.PROD_KEY
   AND EDW_PROD.SRC_SYS_KEY = 'EXCEL_QADDB'
    AND EDW_PROD.CURR_RCRD_FLAG='Y')
,FINAL AS(  
SELECT * FROM FINAL_INFORXA
UNION ALL
SELECT * FROM EXCEL_BILLING )   
SELECT * FROM FINAL
 
