{{ config(
    materialized="table",
    schema='SALES',
    post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (PROD_KEY,PROD_LN_KEY,INVC_NBR,INV_DTE,REGN_KEY,INVC_LN_KEY)"]
) }}
  WITH CAL
AS (
     SELECT DY_DTE,
        MONTH(DY_DTE),YEAR(DY_DTE),
                FYR_ID,
        FMTH_ID, 
        FWK_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN FYR_ID+1 ELSE FYR_ID END AS YEAR ,
       CASE WHEN AA >12 THEN ROUND(AA-12) else ROUND(LPAD(AA,2,0)) END AS MONTH   
FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}
),

RAM AS (
    SELECT DISTINCT 
        BILL.PROD_KEY,
        A.PROD_HIER_LVL_5_DESC
    FROM (
        SELECT DISTINCT 
            PROD_KEY, DIV_ID, SRC_SYS_KEY 
        FROM {{source('SALES_SOURCE', 'BRZ_SALES_BILLING_AMERICAS2_OUTDOOR')}}
    ) BILL
    LEFT JOIN (
        SELECT DISTINCT 
            PROD_KEY, PROD_HIER_LVL_5_DESC
        FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}}
        WHERE SRC_SYS_KEY = 'MTD_IAMS'
    ) A 
        ON BILL.PROD_KEY = A.PROD_KEY
    WHERE BILL.SRC_SYS_KEY = 'INFORXA'
      AND BILL.DIV_ID IN ('36','39','52','38')
),

  CUST_SALESFORCE AS (
    SELECT 
        CUST.PDM_ID,
        CUST.SLS_DEV_SPCL,
        CUST.DIST_ID,
        CUST.SBD_ENTY_NBR,
        CUST.SBD_PRNT_ENTY,
        CUST.HUSTLER_DLR_NBR,
        CUST.DLR_NAME,
        CUST.DLR_LNAME,
        CUST.SHIPPING_STATE_CD,
        CUST.CNTRY_SUBDIV_KEY,
	    CUST.CNTRY_KEY,
	    CUST.SLS_REGN_KEY,
        CUST.SLS_TRTRY_KEY,
	    CUST.ACC_OWNER_NM,
       FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}}  CUST
       WHERE CUST.SRC_SYS_KEY='MTD_SALESFORCE' 
       ),
CUST AS(
SELECT 
        CUST.CUST_NBR,
        CUST.SLS_REGN_KEY,
        CUST.SLS_TRTRY_KEY,
        CUST.ACC_OWNER_NM,
        CUST.CNTRY_KEY,
        CUST.CNTRY_SUBDIV_KEY,
        CUST.CUST_KEY,
        CUST.SRC_SYS_KEY
        FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}}  CUST
        WHERE CUST.SRC_SYS_KEY IN ('EXCEL_QADDB','INFORXA')
        )

SELECT 
    'SALES' AS CTGY_ID,
    'BILLING' AS CTGY_TYP,
    'SALES_BILLING' AS CTGY_SHORT_NAME,
    BILL.SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC AS PROD_CTGY,
    CAL.FYR_ID AS FYR_ID,
    --CAL.FMTH_ID AS FMTH_ID,
    LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
    CAL.FWK_ID AS FWK_ID,
    CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
    CAL.MONTH AS PROG_MTH_ID,
    YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
    MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
    -- BILL.SOLDTO_CUST_SLS_REGN_KEY AS REGN_KEY,
    -- CAST(BILL.SLSREP_TRTRY_KEY AS VARCHAR) AS TRTRY_KEY,
    SF.SLS_REGN_KEY AS REGN_KEY,
    SF.SLS_TRTRY_KEY AS TRTRY_KEY,
    SF.ACC_OWNER_NM AS DLR_SLS_MGR,
    SF.PDM_ID AS PDM_ID,
    SF.SLS_DEV_SPCL AS SLS_DEV_SPCL, 
    SF.DIST_ID AS DIST_ID,
    SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
    SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
    BILL.DIV_ID,
    SF. HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
    SF.DLR_NAME AS DLR_NAME,
    SF.DLR_LNAME AS DLR_LNAME,
    SF.SHIPPING_STATE_CD AS DLR_STATE,
   -- SF.CNTRY_KEY AS DLR_CNTRY,
	CASE WHEN UPPER(SF.CNTRY_KEY) IN ('UNITED STATES','US','U.S.A.','U.S.','USA','COLUMBIANA','DELAWARE') THEN 'US'
       ELSE NULL
     END AS DLR_CNTRY,
    -- NULL AS PRODTN_LN_NBR,
    PROD.Final_Brand AS BRAND,
    RAM.PROD_HIER_LVL_5_DESC AS PROD_LN_KEY,
    --PROD_1.PROD_FAMILY_NAME AS PROD_LN_DESC,
    BILL.PROD_KEY,
    PROD.PROD_DESC,
    PRDH. PROD_HIER_LVL_7_KEY AS IR_DTL_SKU,
    --PRD_LOC.PROD_STAT_DESC  AS PROD_STAT,
	CASE 
    WHEN TRIM(UPPER(PRD_LOC.PROD_STAT_DESC )) = 'ACTIVE' THEN 'ACT'
    WHEN TRIM(UPPER(PRD_LOC.PROD_STAT_DESC )) = 'SUPPRESSED (INACTIVE)' THEN 'INACT'
    ELSE  PRD_LOC.PROD_STAT_DESC 
    END AS PROD_STAT,
    BILL.SLS_ORD_FROM_WHSE_NAME AS SHIP_FROM,
    BILL.SLS_ORD_TYP_CD AS ORD_TYP,
    TO_DECIMAL(BILL.SLS_INVC_ACT_QTY,30,2) AS INV_QTY,
    TO_DECIMAL(BILL.NET_DCRNCY_AMT,30,2)AS AMOUNT,
    TO_DECIMAL(BILL.NET_DCRNCY_AMT_USD,30,2) AS AMOUNT_USD,
    TO_DECIMAL((BILL.SLS_INVC_ACT_QTY * BILL.NET_DCRNCY_AMT_USD),30,2) AS EXTND_AMT,
    --BILL.SLS_ORD_NBR AS TXN_ID,
    BILL.SLS_ORD_LN_NBR AS ORD_LN_NBR,
    DATE(BILL.SLS_ORD_CREATE_DTE) AS TXN_DTE,
    BILL.SLS_ORD_CREATE_DTE AS TXN_TM,
    NULL AS TXN_EFF_DTE,
    NULL AS TXN_GL_DTE,
    NULL AS TXN_TYP,
    BILL.CUST_PO_NBR AS PO_NBR,
    BILL.INVC_NBR,
    BILL.INVC_DOC_LN_NBR AS INVC_LN_NBR,
    BILL.LOT_SERL_NBR AS SERL_NBR,
    BILL.SHIP_LOC_KEY AS SITE_ID,
    BILL.SHIP_LOC_ID AS LOC_ID,
    DATE(BILL.SLS_ORD_CREATE_DTE) AS ORD_DTE,
    DATE(BILL.SLS_DLV_DTE) AS ORD_DUE_DTE,
    DATE(BILL.SLS_INVC_BILL_DTE) AS INV_DTE,
    DATE(BILL.CUST_PO_DTE) AS INV_PO_DTE,
    DATE(BILL.SVC_LVL_DLV_DTE) AS FULL_DUE_DTE,
    TO_DECIMAL(BILL.SLS_ORD_QTY,30,2) AS SLS_ORD_QTY,
    TO_DECIMAL(BILL.SHIP_QTY,30,2) AS SHIP_QTY,
    CASE 
        WHEN BILL.SLS_DLV_DTE >= BILL.SLS_ORD_CREATE_DTE AND BILL.SHIP_QTY <= BILL.SLS_ORD_QTY THEN 'IN_FULL'
        ELSE 'NOT_IN_FULL'
    END AS CAL_ON_TIME_FULL,
   EDW_PROD.PRODTN_LN_NBR,
   BILL.SLS_INVC_LN_KEY AS INVC_LN_KEY,
   BILL.SLS_ORD_NBR AS ORD_NBR,
   BILL.BCRNCY_KEY AS CRNCY_KEY,
   NULL AS LOAN_ID,
   BILL.SOLDTO_CUST_NBR AS DLR_NBR,
   BILL.SLS_ORD_FROM_WHSE_KEY,
   TRIM(SPLIT_PART(BILL.CREDIT_RESN_LN,'~',2)) AS CREDIT_RESN_LN,
   PRDLKP.PROD_BRAND AS BRAND_UU40,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
   FROM {{source('SALES_SOURCE', 'BRZ_SALES_BILLING_AMERICAS2_OUTDOOR')}} AS BILL
   LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT')}} AS PROD
    ON (BILL.SRC_SYS_KEY || '~' || BILL.PROD_KEY) = PROD.PROD_KEY
    AND PROD.SRC_SYS_KEY = 'INFORXA'
LEFT JOIN CAL
    ON BILL.SLS_INVC_CREATE_DTE = CAL.DY_DTE
LEFT JOIN CUST_SALESFORCE SF
 ON UPPER(TRIM(SF.SBD_ENTY_NBR))=UPPER(TRIM(BILL.SOLDTO_CUST_NBR))
 --  LEFT JOIN CUST CF
 --   ON (BILL.SRC_SYS_KEY || '~' || BILL.SOLDTO_CUST_KEY) = CF.CUST_KEY
 -- AND CF.SRC_SYS_KEY='INFORXA'
LEFT JOIN (
    SELECT DISTINCT 
        PROD_KEY, PROD_HIER_LVL_7_KEY, BUS_DIV_ID, SRC_SYS_KEY, CURR_RCRD_FLAG
    FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}}
    WHERE SRC_SYS_KEY = 'INFORXA'
) PRDH 
    ON BILL.PROD_KEY = PRDH.PROD_KEY 
    AND PRDH.CURR_RCRD_FLAG = 'Y' 
    AND PRDH.BUS_DIV_ID = '1'
LEFT JOIN (
    SELECT DISTINCT 
        PROD_KEY, PROD_STAT_LKEY, PROD_STAT_DESC, PROD_LOC.PROD_LOC_KEY, LOC_KEY 
    FROM (
        SELECT DISTINCT 
            PROD_STAT_LKEY, PROD_LOC_KEY, CNTRY_OF_ORIG_KEY, PROD_KEY, LOC_KEY 
        FROM {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}}
        WHERE SRC_SYS_KEY = 'INFORXA'
    ) PROD_LOC
    LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION_LOV')}} AS PROD_LOC_LOV
        ON CONCAT(PROD_LOC.PROD_LOC_KEY, '~', 'E') = PROD_LOC_LOV.PROD_LOC_KEY
) PRD_LOC 
    ON BILL.PROD_KEY = PRD_LOC.PROD_KEY
    AND BILL.SHIP_LOC_KEY = PRD_LOC.LOC_KEY
LEFT JOIN (
    SELECT DISTINCT 
        PROD_FAMILY_NAME, PROD_FAMILY_LKEY, PROD_KEY, PROD_ID, SRC_SYS_KEY 
    FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}}
    WHERE SRC_SYS_KEY = 'BLUEYONDER'
) PROD_1 
    ON BILL.PROD_KEY = PROD_1.PROD_ID
LEFT JOIN  {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
    ON BILL.PROD_KEY = EDW_PROD.PROD_KEY
    AND EDW_PROD.SRC_SYS_KEY = 'INFORXA'
    AND EDW_PROD.CURR_RCRD_FLAG = 'Y'
	LEFT JOIN  PROD_EDW.CONSOLIDATED.VW_EDW_PRODUCT_LOOKUP PRDLKP
    ON UPPER(TRIM(BILL.PROD_KEY))=UPPER(TRIM(PRDLKP.PROD_LKP_KEY))
    AND PRDLKP.SRC_SYS_KEY='INFORXA'
LEFT JOIN RAM 
    ON UPPER(TRIM(RAM.PROD_KEY)) = UPPER(TRIM(BILL.PROD_KEY))
WHERE 
    BILL.SRC_SYS_KEY = 'INFORXA'
    AND BILL.DIV_ID IN ('36','39','52','38')

    UNION ALL  
SELECT 
    'SALES' AS CTGY_ID,
    'BILLING' AS CTGY_TYP,
    'SALES_BILLING' AS CTGY_SHORT_NAME,
    BILL.SRC_SYS_KEY AS SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC  AS PROD_CTGY,
    CAL.FYR_ID AS FYR_ID,
  -- CAL.FMTH_ID AS FMTH_ID,
    LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
    CAL.FWK_ID AS FWK_ID,
    CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
    CAL.MONTH AS PROG_MTH_ID,
    YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
    MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
-- CASE
--         WHEN UPPER(SF.SOLDTO_CUST_SLS_REGN_KEY) LIKE 'S%' THEN SUBSTR(BILL.SOLDTO_CUST_SLS_REGN_KEY, 2, 1)
--         ELSE SUBSTR(BILL.SOLDTO_CUST_SLS_REGN_KEY, 1, 1)
--         END  AS REGN_KEY,
--  CASE
--     WHEN UPPER(BILL.SOLDTO_CUST_SLS_REGN_KEY) LIKE 'S%' THEN SUBSTR(BILL.SOLDTO_CUST_SLS_REGN_KEY, 2)
--         ELSE BILL.SOLDTO_CUST_SLS_REGN_KEY
--      END AS TRTRY_KEY,
    SF.SLS_REGN_KEY AS REGN_KEY,
    SF.SLS_TRTRY_KEY AS TRTRY_KEY,
    SF.ACC_OWNER_NM AS DLR_SLS_MGR,
    SF.PDM_ID AS PDM_ID,
    SF.SLS_DEV_SPCL AS SLS_DEV_SPCL, 
    SF.DIST_ID AS DIST_ID,
    SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
    SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
    --BILL.GPP_DIVISION_ID AS DIV_ID,
	NULL AS DIV_ID,
    SF.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
    SF.DLR_NAME AS DLR_NAME,
    SF.DLR_LNAME AS DLR_LNAME,
    SF.SHIPPING_STATE_CD AS DLR_STATE,
    --SF.CNTRY_KEY AS DLR_CNTRY,
CASE WHEN UPPER(SF.CNTRY_KEY) IN ('UNITED STATES','US','U.S.A.','U.S.','USA','COLUMBIANA','DELAWARE') THEN 'US'
       ELSE NULL
     END AS DLR_CNTRY,
    -- NULL AS PRODTN_LN_NBR,
    --PROD.BRAND_LKEY AS BRAND,
    PROD.Final_Brand  AS BRAND,
    --CASE WHEN BILL.PROD_KEY = '181SAAY2739' THEN 'DEWALT' ELSE PROD.Final_Brand  END AS BRAND,
    PROD.PROD_FAMILY_LKEY AS PROD_LN_KEY,
    --PROD.PROD_FAMILY_NAME AS PROD_LN_DESC,
    BILL.PROD_KEY AS PROD_KEY,
   -- PROD.PROD_DESC AS PROD_DESC,
	REGEXP_REPLACE(PROD.PROD_DESC, '~*EXCEL$', '') AS PROD_DESC,  
--CONCAT(PROD.PROD_FAMILY_NAME,substr( PROD.PROD_DESC,8,2) ,'    ',substr( PROD.PROD_DESC,10,9)) IR_DTL_SKU,
	CASE WHEN SUBSTR(PROD.PROD_DESC,6,1)='R'
THEN CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,6,1),' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
ELSE CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
END AS IR_DTL_SKU,
      CASE 
        WHEN (PROD.PROD_STAT_TYP) = 'ACT' THEN 'ACT'
        ELSE 'INACT' 
    END AS PROD_STAT,
    BILL.SLS_ORD_FROM_WHSE_NAME AS SHIP_FROM,
    BILL.SLS_ORD_TYP_CD AS ORD_TYP,
   TO_DECIMAL(BILL.SLS_INVC_ACT_QTY,30,2) AS INV_QTY,
   TO_DECIMAL(BILL.NET_BCRNCY_AMT,30,2)AS AMOUNT,
   TO_DECIMAL (BILL.NET_BCRNCY_AMT_USD,30,2) AS AMOUNT_USD,
   TO_DECIMAL((BILL.SLS_INVC_ACT_QTY * BILL.NET_BCRNCY_AMT_USD),30,2) AS EXTND_AMT,
    --BILL.SLS_ORD_NBR AS TXN_ID,
    BILL.SLS_ORD_LN_NBR AS ORD_LN_NBR,
    DATE(BILL.SLS_ORD_CREATE_DTE) AS TXN_DTE,
    BILL.SLS_ORD_CREATE_DTE AS TXN_TM,
    NULL AS TXN_EFF_DTE,
    NULL AS TXN_GL_DTE,
    NULL AS TXN_TYP,
    BILL.CUST_PO_NBR AS PO_NBR,
    BILL.INVC_NBR AS INVC_NBR,
    BILL.INVC_DOC_LN_NBR AS INVC_LN_NBR,
    BILL.LOT_SERL_NBR AS SERL_NBR,
    BILL.SHIP_LOC_KEY AS SITE_ID,
    BILL.SHIP_LOC_ID AS LOC_ID,
    DATE(BILL.SLS_ORD_CREATE_DTE) AS ORD_DTE,
    DATE(BILL.SLS_DLV_DTE) AS ORD_DUE_DTE,
    DATE(BILL.SLS_INVC_BILL_DTE) AS INV_DTE,
    DATE(BILL.CUST_PO_DTE) AS INV_PO_DTE,
    DATE(BILL.SVC_LVL_DLV_DTE) AS FULL_DUE_DTE,  
   TO_DECIMAL( BILL.SLS_ORD_QTY,30,2)AS SLS_ORD_QTY,
    TO_DECIMAL(BILL.SHIP_QTY,30,2) AS SHIP_QTY,
    CASE 
        WHEN BILL.SLS_DLV_DTE >= BILL.SLS_ORD_CREATE_DTE 
             AND BILL.SHIP_QTY <= BILL.SLS_ORD_QTY 
        THEN 'IN_FULL' 
        ELSE 'NOT_IN_FULL' 
    END AS CAL_ON_TIME_FULL,
    EDW_PROD.PRODTN_LN_NBR,
     BILL.SLS_INVC_LN_KEY AS INVC_LN_KEY,
     BILL.SLS_ORD_NBR AS ORD_NBR,
     BILL.BCRNCY_KEY AS CRNCY_KEY,
     NULL AS LOAN_ID,
    BILL.SOLDTO_CUST_NBR AS DLR_NBR,
   NULL AS SLS_ORD_FROM_WHSE_KEY,
   NULL AS CREDIT_RESN_LN,
   NULL AS BRAND_UU40,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
FROM {{source('SALES_SOURCE', 'BRZ_SALES_BILLING_AMERICAS2_OUTDOOR')}} AS BILL
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT')}} AS PROD
    ON (BILL.SRC_SYS_KEY || '~' || BILL.PROD_KEY) = PROD.PROD_KEY
LEFT JOIN CAL
    ON BILL.SLS_INVC_BILL_DTE = CAL.DY_DTE
 LEFT JOIN 
    CUST_SALESFORCE SF
	ON UPPER(TRIM(SF.HUSTLER_DLR_NBR))=UPPER(TRIM(BILL.SOLDTO_CUST_NBR))
        LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
    ON BILL.PROD_KEY = EDW_PROD.PROD_KEY
    AND EDW_PROD.SRC_SYS_KEY = 'EXCEL_QADDB'
    AND EDW_PROD.CURR_RCRD_FLAG='Y'
	-- LEFT JOIN CUST AS CF
 --        ON (BILL.SRC_SYS_KEY || '~' || BILL.SOLDTO_CUST_KEY) = CF.CUST_KEY
 -- AND CF.SRC_SYS_KEY='EXCEL_QADDB'
WHERE BILL.SRC_SYS_KEY = 'EXCEL_QADDB'
  --AND BILL.SLS_ORD_TYP_CD IN ('WD','WG','WB','XB','WV','RG','ST','SP')
  AND BILL.SLS_ORD_TYP_CD IN ('WD','WG','WB','XB','WV')

   
  
   
  

   
   
 
