{{ config(
    materialized="table",
    schema='SALES',
   post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (ORD_LN_NBR,PROD_KEY,ORD_DTE,ORD_LN_KEY)"]
) }}

WITH CAL AS (
    SELECT DY_DTE,
        MONTH(DY_DTE),YEAR(DY_DTE),
        FYR_ID,
        FMTH_ID, 
        FWK_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN FYR_ID+1 ELSE FYR_ID END AS YEAR ,
       CASE WHEN AA >12 THEN ROUND(AA-12) else ROUND(LPAD(AA,2,0)) END AS MONTH   
    FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}} 
),
RAM AS (
    SELECT DISTINCT 
        ORD.PROD_KEY,
        A.PROD_HIER_LVL_5_DESC
    FROM (
        SELECT DISTINCT PROD_KEY, DIV_ID, SRC_SYS_KEY 
        FROM {{source('SALES_SOURCE', 'BRZ_SALES_ORDERS_AMERICAS2_OUTDOOR')}}
    ) ORD
    LEFT JOIN (
        SELECT DISTINCT PROD_KEY, PROD_HIER_LVL_5_DESC
        FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}}
        WHERE SRC_SYS_KEY = 'MTD_IAMS'
    ) A ON ORD.PROD_KEY = A.PROD_KEY
    WHERE ORD.SRC_SYS_KEY = 'INFORXA'
      AND ORD.DIV_ID IN ('36', '39', '52', '38')
),

	CUST_SALESFORCE AS (
    SELECT 
        CUST.PDM_ID,
        CUST.SLS_DEV_SPCL,
        CUST.DIST_ID,
        CUST.SBD_ENTY_NBR,
        CUST.SBD_PRNT_ENTY,
        CUST.HUSTLER_DLR_NBR,
        CUST.DLR_NAME,
        CUST.DLR_LNAME,
        CUST.SRC_SYS_KEY,
        CUST.CUST_NBR,
	CUST.CNTRY_SUBDIV_KEY, 
        CUST.CNTRY_KEY,
	CUST.ACC_OWNER_NM,
	CUST.SHIPPING_STATE_CD,
	SLS_REGN_KEY,SLS_TRTRY_KEY
    FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}} CUST
    WHERE CUST.SRC_SYS_KEY='MTD_SALESFORCE' 
),
	CUST AS(
SELECT 
                CUST.CUST_KEY,
                CUST.CUST_NBR,
                CUST.ACC_OWNER_NM,
                CUST.CNTRY_SUBDIV_KEY, 
                CUST.CNTRY_KEY,
                CUST.SRC_SYS_KEY
FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}} CUST
WHERE CUST.SRC_SYS_KEY IN ('INFORXA' ,'EXCEL_QADDB')
)
SELECT 
  'SALES' AS CTGY_ID,
  'ORDERS' AS CTGY_TYP,
  'SALES_ORDERS' AS CTGY_SHORT_NAME,
    ORD.SRC_SYS_KEY AS SRC_SYS_KEY,
    PD.GPP_CATEGORY_DESC   AS PROD_CTGY,
  CAL.FYR_ID AS FYR_ID,
  -- CAL.FMTH_ID AS FMTH_ID,
 LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
  CAL.FWK_ID AS FWK_ID,
  CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
  CAL.MONTH AS PROG_MTH_ID,
  YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
  MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
  -- ORD.SOLDTO_CUST_SLS_REGN_KEY AS REGN_KEY,
  -- ORD.SLSREP_TRTRY_KEY AS TRTRY_KEY,
  SF.SLS_REGN_KEY AS REGN_KEY,
  SF.SLS_TRTRY_KEY AS TRTRY_KEY,
  SF.ACC_OWNER_NM AS DLR_SLS_MGR,
  SF.PDM_ID AS PDM_ID,
  SF.SLS_DEV_SPCL AS SLS_DEV_SPCL, 
  SF.DIST_ID AS DIST_ID,
  SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
  SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
  ORD.DIV_ID AS DIV_ID,
  SF.HUSTLER_DLR_NBR  AS HUSTLER_DLR_NBR,
  SF.DLR_NAME AS DLR_NAME,
  SF.DLR_LNAME AS DLR_LNAME,
 -- ORD.SOLDTO_CUST_STATE_CD AS DLR_STATE,
  SF.SHIPPING_STATE_CD AS DLR_STATE,	
  ---SF.CNTRY_KEY AS DLR_CNTRY,
CASE WHEN UPPER(SF.CNTRY_KEY) IN ('UNITED STATES','US','U.S.A.','U.S.','USA','COLUMBIANA','DELAWARE') THEN 'US'
ELSE NULL
END AS DLR_CNTRY,
  PROD_EDW.PRODTN_LN_NBR,
  PD.FINAL_BRAND  AS BRAND,
  RAM.PROD_HIER_LVL_5_DESC AS PROD_LN_KEY,
  --PROD_1.PROD_FAMILY_NAME AS PROD_LN_DESC,
  ORD.PROD_KEY AS PROD_KEY,
  PD.PROD_DESC AS PROD_DESC,
  PRDH.PROD_HIER_LVL_7_KEY AS IR_DTL_SKU,
  -- PRD_LOC.PROD_STAT_DESC AS PROD_STAT,
CASE 
    WHEN TRIM(UPPER(PRD_LOC.PROD_STAT_DESC )) = 'ACTIVE' THEN 'ACT'
    WHEN TRIM(UPPER(PRD_LOC.PROD_STAT_DESC )) = 'SUPPRESSED (INACTIVE)' THEN 'INACT'
    ELSE  PRD_LOC.PROD_STAT_DESC 
  END AS PROD_STAT,
  ORD.SLS_ORD_FROM_WHSE_NAME AS SHIP_FROM,
  --ORD.SLS_ORD_TYP_CD AS ORD_TYP,
Case WHEN SLS_ORD_TYP_CD= 'WD' THEN 'BOOKING ORDER'
WHEN SLS_ORD_TYP_CD='WV' THEN 'MDV INTIAL ORDERS'
WHEN SLS_ORD_TYP_CD='WG' THEN 'WHOLE GOODS ORDER'
WHEN SLS_ORD_TYP_CD='XB' THEN 'BIGDOG WG ORDERS - US'
ELSE 'NULL'
END AS ORD_TYP,
TO_DECIMAL(ORD.SLS_ORD_QTY,30,2) AS ORD_QTY,
  --TO_DECIMAL(ORD.NET_BCRNCY_AMT,30,2) AS AMOUNT,
  --TO_DECIMAL(ORD.NET_BCRNCY_AMT_USD,30,2) AS AMOUNT_USD,
 -- TO_DECIMAL((ORD.SLS_ORD_QTY * ORD.NET_BCRNCY_AMT),30,2) AS EXTND_AMT,
  TO_DECIMAL(ORD.GRS_DCRNCY_AMT,30,2) AS AMOUNT,
  TO_DECIMAL(ORD.GRS_BCRNCY_AMT,30,2) AS AMOUNT_USD,
  TO_DECIMAL((ORD.SLS_ORD_QTY * ORD.GRS_BCRNCY_AMT),30,2) AS EXTND_AMT,
  --ORD.SLS_ORD_NBR AS TXN_ID,
  ORD.SLS_ORD_LN_NBR AS ORD_LN_NBR,
  DATE(ORD.SLS_ORD_CREATE_DTE) AS TXN_DTE,
  DATE(ORD.SLS_ORD_CREATE_DTE) AS TXN_TM,
  NULL AS TXN_GL_DTE,-- Mapping required
  NULL AS TXN_EFF_DTE,-- Mapping required
  NULL AS TXN_TYP,-- Mapping required
  ORD.CUST_PO_NBR AS PO_NBR,
  NULL AS INVC_NBR,---N/R
  NULL AS SERL_NBR,----N/R
  NULL AS SITE_ID,---N/R
  NULL AS LOC_ID,---N/R
  DATE(ORD.SLS_ORD_CREATE_DTE) AS ORD_DTE,
  -- ORD.SLS_ORD_REQ_DTE AS ORD_DUE_DATE,
  DATE(ORD.MFG_DUE_DATE) AS ORD_DUE_DATE,
  NULL AS INV_DTE,---N/R
  NULL AS INV_PO_DTE,---N/R
  NULL AS FULL_DUE_DTE,----N/R
  TO_DECIMAL(ORD.SLS_ORD_QTY,30,2) AS SLS_ORD_QTY,
 TO_DECIMAL(ORD.SLS_ORD_SHIPPED_QTY,30,2) AS SHIP_QTY,
  NULL AS FL_PLN_AG,---N/R
  NULL AS CAL_ON_TIME_FULL,--N/R
  ORD.ORD_STAT_FLAG AS ORD_STAT_FLAG,
  ORD.OPN_ORD_LN_FLAG AS OPEN_ORDER_FLAG,
  ORD.SLS_ORD_LN_KEY AS ORD_LN_KEY,
 ORD.SLS_ORD_NBR AS ORD_NBR,
 PRDLKP.PROD_BRAND  AS BRAND_UU40,
 ORD.BCRNCY_KEY AS CRNCY_KEY,
ORD.SLS_ORD_HOLD_FLAG AS ORD_HOLD_FLAG,
DATE(ORD.MFG_DUE_DATE) AS MFG_DUE_DATE,
NULL AS ORD_APRV_STAT,
ORD.SLS_ORD_CREATE_DTE AS QUOTE_ORDER_DATE,
 CASE 
    WHEN TRIM(ORD.OPN_ORD_LN_FLAG) = 'Y' THEN (ORD.SLS_ORD_OPN_QTY)
    ELSE '0'
  END AS OPEN_UNITS_TEMP,
  TO_DECIMAL(OPEN_UNITS_TEMP,30,2) AS OPEN_UNITS,
 NULL AS LOAN_ID,
ORD.SOLDTO_CUST_NBR AS DLR_NBR,
 CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
FROM {{source('SALES_SOURCE', 'BRZ_SALES_ORDERS_AMERICAS2_OUTDOOR')}} ORD
LEFT JOIN (SELECT DISTINCT PROD_FAMILY_LKEY,GPP_CATEGORY_DESC,PROD_FAMILY_NAME,ITEM_DESC,Final_Brand,PROD_KEY,BRAND_LKEY,PROD_DESC,PROD_HIER_LVL_4_DESC  FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='INFORXA') PD
  ON (ORD.SRC_SYS_KEY || '~' || ORD.PROD_KEY) = PD.PROD_KEY
LEFT JOIN CUST_SALESFORCE SF
ON UPPER(TRIM(SF.SBD_ENTY_NBR)) = UPPER(TRIM(ORD.SOLDTO_CUST_NBR))
-- LEFT JOIN CUST CF
-- ON (ORD.SRC_SYS_KEY || '~' || ORD.SOLDTO_CUST_KEY) = CF.CUST_KEY
-- WHERE CF.SRC_SYS_KEY='INFORXA'
LEFT JOIN (SELECT DISTINCT PROD_KEY,PROD_HIER_LVL_7_KEY ,BUS_DIV_ID,SRC_SYS_KEY,CURR_RCRD_FLAG FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}} WHERE SRC_SYS_KEY='INFORXA')  PRDH 
ON ORD.PROD_KEY = PRDH.PROD_KEY 
AND PRDH. CURR_RCRD_FLAG = 'Y' 
AND PRDH.BUS_DIV_ID = '1'
LEFT JOIN (
SELECT DISTINCT PROD_KEY,PROD_STAT_LKEY,PROD_STAT_DESC,PROD_LOC_LOV.PROD_LOC_KEY,LOC_KEY FROM 
(Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,LOC_KEY from {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}}
	where src_sys_key = 'INFORXA') PROD_LOC
	 LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION_LOV')}} PROD_LOC_LOV
	 on CONCAT(PROD_LOC.PROD_LOC_KEY,'~','E') = PROD_LOC_LOV.PROD_LOC_KEY
     ) PRD_LOC
ON ORD.PROD_KEY=PRD_LOC.PROD_KEY
AND ORD.SHIP_LOC_KEY=PRD_LOC.LOC_KEY
LEFT JOIN (SELECT DISTINCT PROD_FAMILY_NAME,GPP_CATEGORY_DESC,PROD_FAMILY_LKEY,PROD_KEY,PROD_ID,SRC_SYS_KEY FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='BLUEYONDER') PROD_1
ON ORD.PROD_KEY=PROD_1.PROD_ID
LEFT JOIN  {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS PROD_EDW
    ON ORD.PROD_KEY = PROD_EDW.PROD_KEY
    AND PROD_EDW.SRC_SYS_KEY = 'INFORXA'
    AND PROD_EDW.CURR_RCRD_FLAG='Y'
LEFT JOIN  {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_LOOKUP')}} PRDLKP
	ON UPPER(TRIM(ORD.PROD_KEY))=UPPER(TRIM(PRDLKP.PROD_LKP_KEY))
	AND PRDLKP.SRC_SYS_KEY='INFORXA'
LEFT JOIN CAL ON ORD.SLS_ORD_CREATE_DTE = CAL.DY_DTE
LEFT JOIN RAM ON UPPER(TRIM(RAM.PROD_KEY)) = UPPER(TRIM(ORD.PROD_KEY))
WHERE ORD.SRC_SYS_KEY = 'INFORXA'
AND ORD.DIV_ID IN ('36', '39', '52', '38')

UNION ALL 
SELECT 
  'SALES' AS CTGY_ID,
  'ORDERS' AS CTGY_TYP,
  'SALES_ORDERS' AS CTGY_SHORT_NAME,
    ORD.SRC_SYS_KEY AS SRC_SYS_KEY,
  ---PD.GPP_CATEGORY_DESC AS PROD_CTGY,
CASE WHEN PD.GPP_CATEGORY_DESC IS NULL THEN'NA' ELSE PD.GPP_CATEGORY_DESC END AS PROD_CTGY,
   CAL.FYR_ID AS FYR_ID,
   -- CAL.FMTH_ID AS FMTH_ID,
    LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
  CAL.FWK_ID AS FWK_ID,
  CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
  CAL.MONTH AS PROG_MTH_ID,
   YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
   --  CASE 
   --      WHEN UPPER(ORD.SOLDTO_CUST_SLS_REGN_KEY) LIKE 'S%' 
   --      THEN SUBSTR(ORD.SOLDTO_CUST_SLS_REGN_KEY, 2, 1) 
   --      ELSE SUBSTR(ORD.SOLDTO_CUST_SLS_REGN_KEY, 1, 1) 
   --  END AS REGN_KEY,
	  -- CASE 
   --      WHEN UPPER(ORD.SOLDTO_CUST_SLS_REGN_KEY) LIKE 'S%' 
   --      THEN SUBSTR(ORD.SOLDTO_CUST_SLS_REGN_KEY, 2) 
   --      ELSE UPPER(ORD.SOLDTO_CUST_SLS_REGN_KEY) 
   --  END AS TRTRY_KEY,
	SF.SLS_REGN_KEY AS REGN_KEY,
	SF.SLS_TRTRY_KEY AS TRTRY_KEY,
  SF.ACC_OWNER_NM AS DLR_SLS_MGR,
  SF.PDM_ID AS PDM_ID,
  SF.SLS_DEV_SPCL AS SLS_DEV_SPCL, 
  SF.DIST_ID AS DIST_ID,
  SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
  SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
	NULL AS DIV_ID,
  SF.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
  SF.DLR_NAME AS DLR_NAME,
  SF.DLR_LNAME AS DLR_LNAME,
  --ORD.SOLDTO_CUST_STATE_CD AS DLR_STATE,
  SF.SHIPPING_STATE_CD AS DLR_STATE,
  --SF.CNTRY_KEY AS DLR_CNTRY, 
CASE WHEN UPPER(SF.CNTRY_KEY) IN ('UNITED STATES','US','U.S.A.','U.S.','USA','COLUMBIANA','DELAWARE') THEN 'US'
       ELSE NULL
     END AS DLR_CNTRY,
PROD_EDW.PRODTN_LN_NBR,
  --PD.BRAND_LKEY AS BRAND,
  PD.Final_Brand   AS BRAND,
 --CASE WHEN ORD.PROD_KEY = '181SAAY2739' THEN 'DEWALT' ELSE PD.Final_Brand  END AS BRAND,
  PD.PROD_FAMILY_LKEY AS PROD_LN_KEY,
  --PD.PROD_FAMILY_NAME AS PROD_LN_DESC,
  ORD.PROD_KEY  AS PROD_KEY,
  -- PD.PROD_DESC AS PROD_DESC,
 REGEXP_REPLACE(PD.PROD_DESC, '~*EXCEL$', '') AS PROD_DESC,  
  --CONCAT(PD.PROD_FAMILY_NAME,substr(PD.PROD_DESC,8,2) ,'    ',substr(PD.PROD_DESC,10,9)) IR_DTL_SKU,
 CASE WHEN SUBSTR(PD.PROD_DESC,6,1)='R'
THEN CONCAT(PD.PROD_FAMILY_NAME,' ',SUBSTR(PD.PROD_DESC,6,1),' ',SUBSTR(PD.PROD_DESC,8,2),' ',SUBSTR(PD.PROD_DESC,10,8))
ELSE CONCAT(PD.PROD_FAMILY_NAME,' ',SUBSTR(PD.PROD_DESC,8,2),' ',SUBSTR(PD.PROD_DESC,10,8))
END AS IR_DTL_SKU,
  CASE 
        WHEN (PD.PROD_STAT_TYP) = 'ACT' THEN 'ACT'
        ELSE 'INACT' 
    END AS PROD_STAT,
  ORD.SLS_ORD_FROM_WHSE_NAME AS SHIP_FROM,
  --ORD.SLS_ORD_TYP_CD AS ORD_TYP,
  Case 
WHEN SLS_ORD_TYP_CD= 'WD' THEN 'BOOKING ORDER'
WHEN SLS_ORD_TYP_CD='WV' THEN 'MDV INTIAL ORDERS'
WHEN SLS_ORD_TYP_CD='WG' THEN 'WHOLE GOODS ORDER'
WHEN SLS_ORD_TYP_CD='XB' THEN 'BIGDOG WG ORDERS - US'
ELSE 'NULL'
END AS ORD_TYP,
TO_DECIMAL(ORD.SLS_ORD_QTY,30,2) AS ORD_QTY,
   TO_DECIMAL(ORD.GRS_DCRNCY_AMT,30,2) AS AMOUNT,
  TO_DECIMAL(ORD.GRS_BCRNCY_AMT,30,2) AS AMOUNT_USD,
  TO_DECIMAL((ORD.SLS_ORD_QTY * ORD.GRS_BCRNCY_AMT),30,2) AS EXTND_AMT,
  --ORD.SLS_ORD_NBR AS TXN_ID,
  ORD.SLS_ORD_LN_NBR AS ORD_LN_NBR,
  DATE(ORD.SLS_ORD_CREATE_DTE) AS TXN_DTE,
  DATE(ORD.SLS_ORD_CREATE_DTE) AS TXN_TM,
  NULL AS TXN_GL_DTE,-- Mapping required
  NULL AS TXN_EFF_DTE,-- Mapping required
  NULL AS TXN_TYP,-- Mapping required
  ORD.CUST_PO_NBR AS PO_NBR,
  NULL AS INVC_NBR,---N/R
  NULL AS SERL_NBR,----N/R
  NULL AS SITE_ID,---N/R
  NULL AS LOC_ID,---N/R
  DATE(ORD.SLS_ORD_CREATE_DTE) AS ORD_DTE,
  -- ORD.SLS_ORD_REQ_DTE AS ORD_DUE_DATE,
  DATE(ORD.SLS_ORD_LN_DTE) AS ORD_DUE_DATE,
   NULL AS INV_DTE,---N/R
  NULL AS INV_PO_DTE,---N/R
  NULL AS FULL_DUE_DTE,----N/R
  TO_DECIMAL(ORD.SLS_ORD_QTY,30,2)AS SLS_ORD_QTY,
  TO_DECIMAL(ORD.SLS_ORD_SHIPPED_QTY,30,2) AS SHIP_QTY,
  NULL AS FL_PLN_AG, ----N/R,
  NULL AS CAL_ON_TIME_FULL, ----N/R,
  ORD.ORD_STAT_FLAG AS ORD_STAT_FLAG,
  ORD.OPN_ORD_LN_FLAG AS OPEN_ORDER_FLAG, 
  ORD.SLS_ORD_LN_KEY AS ORD_LN_KEY,
  ORD.SLS_ORD_NBR AS ORD_NBR,
  NULL AS BRAND_UU40,
  ORD.BCRNCY_KEY AS CRNCY_KEY,
  NULL AS ORD_HOLD_FLAG,
  DATE(ORD.SLS_ORD_LN_DTE ) AS  MFG_DUE_DATE,
  ORD.SLS_ORD_APRV_STAT AS ORD_APRV_STAT,
  ORD.SLS_ORD_CREATE_DTE AS QUOTE_ORDER_DATE,
 CASE 
    WHEN TRIM(ORD.OPN_ORD_LN_FLAG) = 'Y' THEN (ORD.SLS_ORD_OPN_QTY)
    ELSE '0'
  END AS OPEN_UNITS_TEMP,
  TO_DECIMAL(OPEN_UNITS_TEMP,30,2) AS OPEN_UNITS,
   NULL AS LOAN_ID,
   ORD.SOLDTO_CUST_NBR AS DLR_NBR,
  CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE --COMMIT
FROM {{source('SALES_SOURCE', 'BRZ_SALES_ORDERS_AMERICAS2_OUTDOOR')}} ORD
LEFT JOIN (SELECT DISTINCT GPP_CATEGORY_DESC,PROD_FAMILY_LKEY,PROD_FAMILY_NAME,ITEM_DESC,Final_Brand,PROD_KEY,PROD_STAT_TYP,BRAND_LKEY,PROD_DESC,GPP_DIVISION_ID  FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='EXCEL_QADDB') PD
  ON (ORD.SRC_SYS_KEY || '~' || ORD.PROD_KEY) = PD.PROD_KEY 
LEFT JOIN CAL
  ON ORD.SLS_ORD_CREATE_DTE = CAL.DY_DTE
LEFT JOIN CUST_SALESFORCE SF
ON UPPER(TRIM(SF.HUSTLER_DLR_NBR))=UPPER(TRIM(ORD.SOLDTO_CUST_KEY))
LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS PROD_EDW
    ON ORD.PROD_KEY = PROD_EDW.PROD_KEY
    AND PROD_EDW.SRC_SYS_KEY = 'EXCEL_QADDB'
    AND PROD_EDW.CURR_RCRD_FLAG='Y'
-- LEFT JOIN CUST CF
-- ON (ORD.SRC_SYS_KEY || '~' || ORD.SOLDTO_CUST_KEY) = CF.CUST_KEY
-- AND CF.SRC_SYS_KEY='EXCEL_QADDB'
  WHERE ORD.SRC_SYS_KEY ='EXCEL_QADDB' 
AND ORD.SLS_ORD_TYP_CD IN ('WD','WG','WB','XB','WV')
AND  ORD.OPN_ORD_LN_FLAG ='Y'

