{{ config(
    materialized="table",
    schema='SALES',
     post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY ( SRC_SYS_KEY,PROD_KEY,SITE_ID,LOC_ID,ETL_INS_DTE,CLNDR_YR_ID,CLNDR_MTH_ID)"]
) }}

WITH PROG 
AS (
 SELECT DY_DTE,
        MONTH(DY_DTE),YEAR(DY_DTE),
                FYR_ID,
        FMTH_ID, 
        FWK_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN FYR_ID+1 ELSE FYR_ID END AS YEAR ,
       CASE WHEN AA >12 THEN ROUND(AA-12) else ROUND(LPAD(AA,2,0)) END AS MONTH   
FROM {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}
),
	PL AS(
select DISTINCT   INV.PROD_KEY,A.PROD_HIER_LVL_5_DESC
FROM {{source('INVENTORY', 'VW_BRZ_INVENTORY_ONHAND')}} INV
 
LEFT JOIN
  (SELECT DISTINCT 
   PROD_KEY,PROD_HIER_LVL_5_DESC
   FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}} where SRC_SYS_KEY  = 'MTD_IAMS') A
   ON UPPER(TRIM(INV.PROD_KEY))= UPPER(TRIM(A.PROD_KEY)) --
WHERE INV.SRC_SYS_KEY IN ('INFORXA')
    )

   
SELECT 
    'INFORXA'                 AS SRC_SYS_KEY,
    'SALES'               AS CTGY_ID,
    'INVENTORY'                  AS CTGY_TYP,
    'SALES_INVENTORY'           AS CTGY_SHORT_NAME,
    PRD.GPP_CATEGORY_DESC       AS PROD_CTGY,
    PROG.FYR_ID               AS FYR_ID,
    -- PROG.FMTH_ID              AS FMTH_ID,
   LTRIM(SUBSTR(PROG.FMTH_ID, 5, 2),'0') AS FMTH_ID,
    PROG.FWK_ID               AS FWK_ID,
    CAST(PROG.YEAR AS INTEGER) AS PROG_YR_ID,
    PROG.MONTH                AS PROG_MTH_ID,
    YEAR(PROG.DY_DTE)         AS CLNDR_YR_ID,
    MONTH(PROG.DY_DTE)        AS CLNDR_MTH_ID,
    NULL                       AS   DIV_ID,
    EDW_PROD.PRODTN_LN_NBR       AS PRODTN_LN_NBR,
    PRD.FINAL_BRAND           AS BRAND,
     PL.PROD_HIER_LVL_5_DESC     AS PROD_LN_KEY,
    --PROD_1.PROD_FAMILY_NAME      AS PROD_LN_DESC,
    INV.PROD_KEY              AS PROD_KEY,
    INV.PROD_DESC             AS PROD_DESC,
    PRDH.PROD_HIER_LVL_7_KEY  AS IR_DTL_SKU,
    -- UPPER(PROD_LOC_LOV.PROD_STAT_DESC) AS PROD_STAT,
    CASE 
    WHEN TRIM(UPPER(PROD_LOC_LOV.PROD_STAT_DESC)) = 'ACTIVE' THEN 'ACT'
    WHEN TRIM(UPPER(PROD_LOC_LOV.PROD_STAT_DESC)) IN ('NULL', 'SUPPRESSED (INACTIVE)') THEN 'INACT'
    ELSE PROD_LOC_LOV.PROD_STAT_DESC 
    END AS PROD_STAT,
   CASE WHEN TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_QTY),30,2) < 0 THEN 0 ELSE TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_QTY),30,2) END  AS PROD_QTY, 
   CASE WHEN TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_AMT),30,2) < 0 THEN 0 ELSE  TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_AMT),30,2) END  AS AMOUNT,
   CASE WHEN TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_QTY),30,2) <0 THEN 0 ELSE TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_QTY),30,2)* TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_AMT),30,2) END  AS EXTND_AMT,
    NULL                      AS TXN_ID,
    NULL                      AS TXN_DTE,
    NULL                      AS TXN_TM,
    NULL                       AS TXN_EFF_DTE,
    NULL                       AS TXN_GL_DTE,
    NULL                       AS TXN_TYP,
    INV.LOC_KEY               AS SITE_ID,
    INV.LOC_NAME              AS LOC_NAME,
    INV.WHSE_NBR              AS WHSE_NBR,
    INV.SLOC_ID               AS LOC_ID,
    INV.ETL_INS_DTE               AS ETL_INS_DTE,
    INV.CRNCY_KEY                 AS CRNCY_KEY,
    PRDLKP.PROD_BRAND             AS BRAND_UU40,
   CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
FROM {{source('INVENTORY', 'VW_BRZ_INVENTORY_ONHAND')}} INV --207424846
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT')}} PRD
ON (INV.SRC_SYS_KEY||'~'||INV.PROD_KEY) = UPPER(TRIM(PRD.PROD_KEY))
AND INV.GPP_DIVISION_ID=PRD.GPP_DIVISION_ID
AND PRD.SRC_SYS_KEY='INFORXA'
 LEFT JOIN   PROG
 ON TO_DATE(INV.ETL_INS_DTE) = TO_DATE(PROG.DY_DTE)
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}} PRDL
ON (INV.SRC_SYS_KEY||'~'||INV.PROD_KEY ||'~'|| INV.LOC_KEY) = (PRDL.PROD_LOC_KEY)
AND PRDL.SRC_SYS_KEY='INFORXA'
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION_LOV')}} PROD_LOC_LOV 
	 on CONCAT(PRDL.PROD_LOC_KEY,'~','E') = PROD_LOC_LOV.PROD_LOC_KEY
LEFT JOIN (SELECT DISTINCT PROD_KEY,PROD_HIER_LVL_7_KEY,PROD_HIER_LVL_4_DESC,BUS_DIV_ID,SRC_SYS_KEY,CURR_RCRD_FLAG,PROD_HIER_LVL_5_KEY
  FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}} WHERE SRC_SYS_KEY='INFORXA')  PRDH
ON INV.PROD_KEY = PRDH.PROD_KEY 
AND PRDH. CURR_RCRD_FLAG = 'Y' 
AND PRDH.BUS_DIV_ID = '1' -- 1 is US & 3 is CA
--AND PRD.PROD_HIER_LVL_7_ID=PRDH.PROD_HIER_LVL_7_ID
AND PRDH.SRC_SYS_KEY='INFORXA'
LEFT JOIN (SELECT DISTINCT PROD_FAMILY_NAME,PROD_FAMILY_LKEY,PROD_KEY,PROD_ID,SRC_SYS_KEY FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='BLUEYONDER') PROD_1
    -- ON (BILL.SRC_SYS_KEY || '~' || BILL.PROD_KEY) = PROD.PROD_KEY
    ON INV.PROD_KEY=PROD_1.PROD_ID
LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
  ON INV.PROD_KEY = EDW_PROD.PROD_KEY
    AND EDW_PROD.SRC_SYS_KEY = 'INFORXA'
    AND EDW_PROD.CURR_RCRD_FLAG='Y'
LEFT JOIN  PROD_EDW.CONSOLIDATED.VW_EDW_PRODUCT_LOOKUP PRDLKP
    ON UPPER(TRIM(INV.PROD_KEY))=UPPER(TRIM(PRDLKP.PROD_LKP_KEY))
    AND PRDLKP.SRC_SYS_KEY='INFORXA'
LEFT JOIN PL
    ON UPPER(TRIM(PL.PROD_KEY))=UPPER(TRIM(INV.PROD_KEY))
WHERE INV.SRC_SYS_KEY IN ('INFORXA') AND
(DATE(INV.EFF_DTE) <= DATE(SYSDATE()) and DATE(INV.EXPR_DTE) > DATE(SYSDATE())) AND
INV.LOC_KEY not in ('CRP','CTP','C73','C92','C93','I13','I31','I35','I40','I42','I43','I44','MEC','N07','N08','N09','N10',
'N11','N12','N13','N14','N15','N16','N17','N18','N19','N20','N21','N22','N23','WKC') 
AND INV.WHSE_NBR IN('21','21A','21D','21F','28E','33','33A','37','37A','37D','37E','29Z')
--  AND INV.SRC_TBL_NAME NOT LIKE '%_CORP'
--  AND INV.SRC_TBL_NAME NOT LIKE  'SLQNTY%' 
 AND INV.SLOC_ID<> 'ALL'
 GROUP BY ALL

UNION ALL

SELECT
    'EXCEL_QADDB'             AS SRC_SYS_KEY,
    'INVENTORY'               AS CTGY_ID,
    'INVENTORY'                  AS CTGY_TYP,
    'SALES_INVENTORY'          AS CTGY_SHORT_NAME,
    PRD.GPP_CATEGORY_DESC       AS PROD_CTGY,
    PROG.FYR_ID               AS FYR_ID,
    -- PROG.FMTH_ID              AS FMTH_ID,
   LTRIM(SUBSTR(PROG.FMTH_ID, 5, 2),'0') AS FMTH_ID,
    PROG.FWK_ID               AS FWK_ID,
    CAST(PROG.YEAR AS INTEGER) AS PROG_YR_ID,
    PROG.MONTH                AS PROG_MTH_ID,
    YEAR(PROG.DY_DTE)         AS CLNDR_YR_ID,
    MONTH(PROG.DY_DTE)        AS CLNDR_MTH_ID,
    NULL                      AS DIV_ID,
    EDW_PROD.PRODTN_LN_NBR         AS PRODTN_LN_NBR,
    PRD.Final_Brand   AS BRAND,
    --CASE WHEN INV.PROD_KEY = '181SAAY2739' THEN 'DEWALT' ELSE PRD.Final_Brand  END AS BRAND,
    PRD.PROD_FAMILY_LKEY      AS PROD_LN_KEY,
    --PRD.PROD_FAMILY_NAME      AS PROD_LN_DESC,
    INV.PROD_KEY              AS PROD_KEY,
    -- INV.PROD_DESC             AS PROD_DESC,
REGEXP_REPLACE(PRD.PROD_DESC, '~*EXCEL$', '') AS PROD_DESC,  
    ---CONCAT(PRD.PROD_FAMILY_NAME,substr( INV.PROD_DESC,8,2) ,'    ',substr( INV.PROD_DESC,10,9)) IR_DTL_SKU,
	CASE WHEN SUBSTR(INV.PROD_DESC,6,1)='R'
THEN CONCAT(PRD.PROD_FAMILY_NAME,' ',SUBSTR(INV.PROD_DESC,6,1),' ',SUBSTR(INV.PROD_DESC,8,2),' ',SUBSTR(INV.PROD_DESC,10,8))
ELSE CONCAT(PRD.PROD_FAMILY_NAME,' ',SUBSTR(INV.PROD_DESC,8,2),' ',SUBSTR(INV.PROD_DESC,10,8))
END AS IR_DTL_SKU,
    CASE 
        WHEN UPPER(PRD.PROD_STAT_TYP) = 'ACT' THEN 'ACT' 
             ELSE 'INACT' 
                                                                    END AS PROD_STAT, 
    CASE WHEN TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_QTY),30,2) < 0 THEN 0 ELSE TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_QTY),30,2) END  AS PROD_QTY, 
   CASE WHEN TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_AMT),30,2) < 0 THEN 0 ELSE  TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_AMT),30,2) END  AS AMOUNT,
   CASE WHEN TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_QTY),30,2) <0 THEN 0 ELSE TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_QTY),30,2)* TO_DECIMAL(SUM(INV.VALUATED_UNRSTR_STK_AMT),30,2) END  AS EXTND_AMT,
    NULL                       AS TXN_ID,
    NULL                       AS TXN_DTE,
    NULL                       AS TXN_TM,
    NULL                       AS TXN_EFF_DTE,
    NULL                       AS TXN_GL_DTE,
    NULL                       AS TXN_TYP,
    INV.LOC_KEY               AS SITE_ID,
    INV.LOC_NAME              AS LOC_NAME,
    INV.WHSE_NBR              AS WHSE_NBR,
    INV.SLOC_ID               AS LOC_ID,
    INV.ETL_INS_DTE               AS ETL_INS_DTE,
    INV.CRNCY_KEY                 AS CRNCY_KEY,
     NULL                         AS BRAND_UU40,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
FROM {{source('INVENTORY', 'VW_BRZ_INVENTORY_ONHAND')}} INV --207424846
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT')}} PRD
ON (INV.SRC_SYS_KEY||'~'||INV.PROD_KEY) = UPPER(TRIM(PRD.PROD_KEY))
AND PRD.SRC_SYS_KEY='EXCEL_QADDB'
LEFT JOIN  PROG
ON TO_DATE(INV.ETL_INS_DTE) = TO_DATE(PROG.DY_DTE)
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}} PRDL
ON (INV.SRC_SYS_KEY||'~'||INV.PROD_KEY ||'~'|| INV.LOC_KEY) = (PRDL.PROD_LOC_KEY)
AND PRDL.SRC_SYS_KEY='EXCEL_QADDB'
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION_LOV')}} PROD_LOC_LOV 
	 on CONCAT(PRDL.PROD_LOC_KEY,'~','E') = PROD_LOC_LOV.PROD_LOC_KEY
      LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
  ON INV.PROD_KEY = EDW_PROD.PROD_KEY
    AND EDW_PROD.SRC_SYS_KEY = 'EXCEL_QADDB'
    AND EDW_PROD.CURR_RCRD_FLAG='Y'   
WHERE INV.SRC_SYS_KEY IN ('EXCEL_QADDB') AND 
INV.LOC_KEY = 'BB' AND
(DATE(INV.EFF_DTE) <= DATE(SYSDATE()) and DATE(INV.EXPR_DTE) > DATE(SYSDATE())) GROUP BY ALL
