{{ config(
    materialized="table",
    schema='SALES',
post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (SERL_NBR,SRC_SYS_KEY,LOAN_ID,PROD_KEY,TXN_DTE,TRTRY_KEY,SBD_ENTY_NBR,SETTLEMENT_DTE,DLR_CNTRY,FL_PLN_AG,INVC_NBR)"]
) }}



WITH TOTAL AS(
WITH CAL
AS (
     SELECT DY_DTE,
        MONTH(DY_DTE),YEAR(DY_DTE),
         FYR_ID,
        FMTH_ID, 
        FWK_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN FYR_ID+1 ELSE FYR_ID END AS YEAR ,
       CASE WHEN AA >12 THEN ROUND(AA-12) else ROUND(LPAD(AA,2,0)) END AS MONTH   
FROM  {{source('DIMENSIONS', 'DIM_FISCAL_CALENDAR')}}
),
CUST_SALESFORCE AS (
    SELECT
        CUST.PDM_ID,
        CUST.SLS_DEV_SPCL,
        CUST.DIST_ID,
        CUST.SBD_ENTY_NBR,
        CUST.SBD_PRNT_ENTY,
        CUST.HUSTLER_DLR_NBR,
        CUST.DLR_NAME,
        CUST.DLR_LNAME,
        CUST.BILLING_STATE_CD,
	SRC_SYS_KEY,
        CUST.SLS_REGN_KEY,
        CUST.SLS_TRTRY_KEY,
        CUST.ACC_OWNER_NM,
	CUST.CNTRY_KEY,
	SHIPPING_STATE_CD
       FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}} CUST
       WHERE CUST.SRC_SYS_KEY='MTD_SALESFORCE' 
       ),
    PL AS(
select DISTINCT SETT.PROD_NUM,A.PROD_HIER_LVL_5_DESC
FROM (SELECT DISTINCT PROD_NUM,SRC_SYS_KEY FROM {{source('SALES_SOURCE', 'VW_BRZ_DEALER_SETTLEMENTS')}} WHERE UPPER(TRIM(SRC_SYS_KEY)) = 'INFORXA'
  AND SRC_IDENTIFIER = 'Settlements') SETT
LEFT JOIN
  (SELECT DISTINCT 
   PROD_KEY,PROD_HIER_LVL_5_DESC
   FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}}  where SRC_SYS_KEY  = 'MTD_IAMS') A
   ON UPPER(TRIM(SETT.PROD_NUM))= UPPER(TRIM(A.PROD_KEY)) --
WHERE SETT.SRC_SYS_KEY = 'INFORXA'  
    )
    SELECT 
    'RETAIL' AS CTGY_ID,
    'SETTLEMENTS' AS CTGY_TYP,
    'SALES_SETTLEMENTS' AS CTGY_SHORT_NAME,
    SETT.SRC_SYS_KEY AS SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC  AS PROD_CTGY,
  CAL.FYR_ID AS FYR_ID,
  LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
  CAL.FWK_ID AS FWK_ID,
  CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
  CAL.MONTH AS PROG_MTH_ID,
  YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
  MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
    SF.SLS_REGN_KEY  AS REGN_KEY,
    SF.SLS_TRTRY_KEY AS TRTRY_KEY,
    SF.ACC_OWNER_NM AS DLR_SLS_MGR,
    SF.PDM_ID AS PDM_ID,
    SF.SLS_DEV_SPCL AS SLS_DEV_SPCL,
    SF.DIST_ID AS DIST_ID,
    SF.SBD_ENTY_NBR AS SBD_ENTY_NBR,
    --   CASE 
    --     WHEN CUST.SBD_ENTY_NBR IS NULL THEN CUST.CUST_NBR 
    --     ELSE CUST.SBD_ENTY_NBR 
    -- END AS SBD_ENTY_NBR,
    SF.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
    SHIP.DIV_ID AS DIV_ID,
    SF.HUSTLER_DLR_NBR  AS HUSTLER_DLR_NBR,
    SF.DLR_NAME AS DLR_NAME,
    SF.DLR_LNAME AS DLR_LNAME,
    SETT.SHIPPING_STATE_CD AS DLR_STATE,
    SETT.COUNTRY AS DLR_CNTRY,
    EDW_PROD.PRODTN_LN_NBR  AS PRODTN_LN_NBR,
    --PROD.BRAND_LKEY AS BRAND,
    PROD.FINAL_BRAND AS BRAND,
    PL.PROD_HIER_LVL_5_DESC  AS PROD_LN_KEY,
    --PROD_1.PROD_FAMILY_NAME AS PROD_LN_DESC,
    SETT.PROD_NUM AS PROD_KEY,
    PROD.PROD_DESC AS PROD_DESC,
    PRDH.PROD_HIER_LVL_7_KEY AS IR_DTL_SKU,
    CASE WHEN PROD_LOC.PROD_STAT_LKEY='A' THEN 'ACT' ELSE 'INACT' END AS PROD_STAT,
    NULL AS SHIP_FROM,
    NULL AS ORD_TYP,
    CASE WHEN SETT.SETTLEMENT_FLAG = '2' THEN 1 ELSE NULL END AS PROD_QTY,
    TO_DECIMAL(SETT.SETTLEMENT_AMT,30,2) AS AMOUNT,
    TO_DECIMAL(SETT.SETTLEMENT_AMT,30,2) AS AMOUNT_USD,
    TO_DECIMAL((CASE WHEN SETT.SETTLEMENT_FLAG = '2' THEN 1 ELSE NULL END) * SETT.SETTLEMENT_AMT, 30, 2) AS EXTND_AMT,
   --SETT.LOAN_ID AS TXN_ID,
    DATE(SETT.GENERATION_DTE) AS TXN_DTE,
    SETT.GENERATION_DTE AS TXN_TM,
    NULL AS TXN_EFF_DTE,
    NULL AS TXN_GL_DTE,
    NULL AS TXN_TYP,
    SHIP.PO_NBR AS PO_NBR,
    SHIP.ORD_NBR AS ORD_NBR,
    CASE WHEN SETT.INV_NBR = '' THEN SHIP.INVC_NBR ELSE SETT.INV_NBR END AS INVC_NBR,
    SETT.SERIAL_NBR AS SERL_NBR,
    NULL AS SITE_ID,
    NULL AS LOC_ID,
    NULL AS ORD_DTE,
    NULL AS ORD_DUE_DTE,
    DATE(SETT.INV_DTE) AS INV_DTE,
    NULL AS INV_PO_DTE,
    NULL AS FULL_DUE_DTE,
    NULL AS SHIP_QTY,
    NULL AS SLS_ORD_QTY,
    SETT.AS_OF_DTE AS FL_PLN_AG,
    DATE(SETT.SETTLEMENT_DTE) AS SETTLEMENT_DTE,
    CASE WHEN SETT.SETTLEMENT_FLAG = '2' THEN 'Y' ELSE 'N' END AS SETLMT_FLAG,
    SETT.LOAN_ID AS LOAN_ID,
     NULL AS CASH_SETTLEMENT_FLAG, 
	SETT.CUST_NBR AS DLR_NBR,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
 FROM {{source('SALES_SOURCE', 'VW_BRZ_DEALER_SETTLEMENTS')}} SETT
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT')}}  PROD
    ON UPPER(TRIM(SETT.PROD_NUM)) = UPPER(TRIM(PROD.PROD_ID))
    AND UPPER(PROD.SRC_SYS_KEY) = 'INFORXA'
LEFT JOIN CUST_SALESFORCE SF
ON UPPER(TRIM(SF.SBD_ENTY_NBR))=UPPER(TRIM(SETT.CUST_NBR))
    LEFT JOIN
( Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,SRC_SYS_KEY from  {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}}
--PROD_EDW.DIMENSIONS.DIM_PRODUCT_LOCATION
 WHERE SRC_SYS_KEY='INFORXA'
	QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY))  ORDER BY PROD_KEY DESC) =1) PROD_LOC
      ON UPPER(TRIM(SETT.PROD_NUM)) = UPPER(TRIM(PROD_LOC.PROD_KEY))
  and PROD_LOC.SRC_SYS_KEY = 'INFORXA'
 LEFT JOIN   CAL
--     -- ON SETT.GENERATION_DTE = CAL.DY_DTE
     ON SETT.SETTLEMENT_DTE = CAL.DY_DTE
     LEFT JOIN
     (SELECT DISTINCT PROD_KEY,PROD_HIER_LVL_7_KEY,BUS_DIV_ID,SRC_SYS_KEY,CURR_RCRD_FLAG
  FROM  {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}}  WHERE SRC_SYS_KEY='INFORXA')  PRDH
ON SETT.PROD_NUM = PRDH.PROD_KEY 
AND  PRDH.CURR_RCRD_FLAG = 'Y' 
AND PRDH.BUS_DIV_ID = '1'
LEFT JOIN (SELECT DISTINCT PROD_FAMILY_NAME,PROD_FAMILY_LKEY,PROD_KEY,PROD_ID,SRC_SYS_KEY FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='BLUEYONDER') PROD_1
    -- ON (BILL.SRC_SYS_KEY || '~' || BILL.PROD_KEY) = PROD.PROD_KEY
    ON SETT.PROD_NUM=PROD_1.PROD_ID
	 LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
  ON SETT.PROD_NUM = EDW_PROD.PROD_KEY
    AND EDW_PROD.SRC_SYS_KEY = 'INFORXA'
    AND EDW_PROD.CURR_RCRD_FLAG='Y'
    LEFT JOIN PL
    ON UPPER(TRIM(PL.PROD_NUM))=UPPER(TRIM(SETT.PROD_NUM))
 LEFT JOIN (SELECT DISTINCT SERL_NBR,PROD_KEY,DIV_ID,INVC_NBR,PO_NBR,ORD_NBR 
 FROM {{source('SALES_BRZ', 'BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL')}} --TEST_MARTS.SALES.BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL 
 WHERE SRC_SYS_KEY='INFORXA'
QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY)),UPPER(TRIM(SERL_NBR))  ORDER BY PROD_KEY,SERL_NBR DESC) =1)SHIP
ON UPPER(TRIM(SHIP.SERL_NBR))=UPPER(TRIM(SETT.SERIAL_NBR))
AND UPPER(TRIM(SHIP.PROD_KEY))=UPPER(TRIM(SETT.PROD_NUM))
WHERE UPPER(TRIM(SETT.SRC_SYS_KEY)) = 'INFORXA'
  AND UPPER(SETT.SRC_IDENTIFIER) ='SETTLEMENTS' 
  AND UPPER(SETT.COUNTRY)='US'
  AND SETTLEMENT_FLAG = '2'

UNION ALL

  SELECT 
    'RETAIL' AS CTGY_ID,
    'SETTLEMENTS' AS CTGY_TYP,
    'SALES_SETTLEMENTS' AS CTGY_SHORT_NAME,
    SETT.SRC_SYS_KEY AS SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC AS PROD_CTGY,
  CAL.FYR_ID AS FYR_ID,
  -- CAL.FMTH_ID AS FMTH_ID,
 LTRIM(SUBSTR(CAL.FMTH_ID, 5, 2),'0') AS FMTH_ID,
  CAL.FWK_ID AS FWK_ID,
  CAST(CAL.YEAR AS INTEGER) AS PROG_YR_ID,
  CAL.MONTH AS PROG_MTH_ID,
  YEAR(CAL.DY_DTE) AS CLNDR_YR_ID,
  MONTH(CAL.DY_DTE) AS CLNDR_MTH_ID,
    -- CASE 
    --     WHEN UPPER(CUST_EXCEL.SLS_REGN_KEY) LIKE 'S%' 
    --     THEN SUBSTR(CUST_EXCEL.SLS_REGN_KEY, 2, 1) 
    --     ELSE SUBSTR(CUST_EXCEL.SLS_REGN_KEY, 1, 1) 
    -- END AS REGN_KEY,
    --  CASE 
    --     WHEN UPPER(CUST_EXCEL.SLS_REGN_KEY) LIKE 'S%' 
    --     THEN SUBSTR(CUST_EXCEL.SLS_REGN_KEY, 2) 
    --     ELSE UPPER(CUST_EXCEL.SLS_REGN_KEY) 
    -- END AS TRTRY_KEY,
   SF.SLS_REGN_KEY  AS REGN_KEY,
   SF.SLS_TRTRY_KEY  AS TRTRY_KEY,
    SF.ACC_OWNER_NM AS DLR_SLS_MGR,
    SF.PDM_ID AS PDM_ID,
    SF.SLS_DEV_SPCL AS SLS_DEV_SPCL,
    SF.DIST_ID AS DIST_ID,
    --CUST.SBD_ENTY_NBR AS SBD_ENTY_NBR,
    -- CASE 
    --     WHEN CUST.SBD_ENTY_NBR IS NULL THEN CUST.CUST_NBR 
    --     ELSE CUST.SBD_ENTY_NBR 
    -- END AS SBD_ENTY_NBR,
	SF.SBD_ENTY_NBR,
    SF.SBD_PRNT_ENTY  AS SBD_PRNT_ENTY,
    SHIP.DIV_ID AS DIV_ID,
    SF.HUSTLER_DLR_NBR  AS HUSTLER_DLR_NBR,
    SF.DLR_NAME AS DLR_NAME,
    SF.DLR_LNAME AS DLR_LNAME,
    --SETT.SHIPPING_STATE_CD AS DLR_STATE,
    SF.SHIPPING_STATE_CD AS  DLR_STATE,
    SETT.COUNTRY AS DLR_CNTRY,
    EDW_PROD.PRODTN_LN_NBR AS PRODTN_LN_NBR ,
   -- PROD.BRAND_LKEY AS BRAND,
     PROD.Final_Brand  AS BRAND,
     --CASE WHEN SETT.PROD_NUM = '181SAAY2739' THEN 'DEWALT' ELSE PROD.Final_Brand  END AS BRAND,
    PROD.PROD_FAMILY_LKEY   AS PROD_LN_KEY,
    --PROD.PROD_FAMILY_NAME  AS PROD_LN_DESC,
    SETT.PROD_NUM AS PROD_KEY,
    -- PROD.PROD_DESC AS PROD_DESC,
   REGEXP_REPLACE(PROD.PROD_DESC, '~~EXCEL', '') AS PROD_DESC,  
    -- CONCAT(PROD.PROD_FAMILY_NAME,substr( PROD.PROD_DESC,8,2) ,'    ',substr( PROD.PROD_DESC,10,9)) IR_DTL_SKU,
   CASE WHEN SUBSTR(PROD.PROD_DESC,6,1)='R'
   THEN CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,6,1),' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
   ELSE CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
   END AS IR_DTL_SKU,
     CASE 
        WHEN (PROD.PROD_STAT_TYP) = 'ACT' THEN 'ACT'
        ELSE 'INACT' 
    END AS PROD_STAT,
    NULL AS SHIP_FROM,
    NULL AS ORD_TYP,
    CASE WHEN SETT.SETTLEMENT_FLAG = '2' THEN 1 ELSE NULL END AS PROD_QTY,
    TO_DECIMAL(SETT.OUTSTANDING_AMT,30,2) AS AMOUNT,
    TO_DECIMAL(SETT.OUTSTANDING_AMT,30,2) AS AMOUNT_USD,
    TO_DECIMAL((CASE WHEN SETT.SETTLEMENT_FLAG = '2' THEN 1 ELSE NULL END) * SETT.OUTSTANDING_AMT, 30, 2) AS EXTND_AMT,
    --SETT.LOAN_ID AS TXN_ID,
    DATE(SETT.GENERATION_DTE) AS TXN_DTE,
    SETT.GENERATION_DTE AS TXN_TM,
    NULL AS TXN_EFF_DTE,
    NULL AS TXN_GL_DTE,
    NULL AS TXN_TYP,
    SHIP.PO_NBR AS PO_NBR,
    SHIP.ORD_NBR AS ORD_NBR,
    CASE WHEN SETT.INV_NBR = '' THEN SHIP.INVC_NBR ELSE SETT.INV_NBR END AS INVC_NBR,
    SETT.SERIAL_NBR AS SERL_NBR,
    NULL AS SITE_ID,
    NULL AS LOC_ID,
    NULL AS ORD_DTE,
    NULL AS ORD_DUE_DTE,
    DATE(SETT.INV_DTE) AS INV_DTE ,
    NULL AS INV_PO_DTE,
    NULL AS FULL_DUE_DTE,
    NULL AS SHIP_QTY,
    NULL AS SLS_ORD_QTY,
    SETT.AS_OF_DTE AS FL_PLN_AG,
    DATE(SETT.SETTLEMENT_DTE) AS SETTLEMENT_DTE,
    CASE WHEN SETT.SETTLEMENT_FLAG = '2' THEN 'Y' ELSE 'N' END AS SETLMT_FLAG,
     LOAN_ID,
    NULL AS CASH_SETTLEMENT_FLAG, 
	SETT.CUST_NBR AS DLR_NBR,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
FROM {{source('SALES_SOURCE', 'VW_BRZ_DEALER_SETTLEMENTS')}} SETT
LEFT JOIN  {{source('DIMENSIONS', 'DIM_PRODUCT')}} PROD
    ON UPPER(TRIM(SETT.PROD_NUM)) = UPPER(TRIM(PROD.PROD_ID))
    AND UPPER(PROD.SRC_SYS_KEY) = 'EXCEL_QADDB'
-- LEFT JOIN TEST_EDW.DIMENSIONS.DIM_CUSTOMER CUST
--       ON TRIM(CUST.CUST_NBR)=TRIM(SETT.CUST_NBR)
--     AND UPPER(TRIM(CUST.SRC_SYS_KEY)) = 'EXCEL_QADDB'
LEFT JOIN (
    SELECT DISTINCT CUST_NBR,HUSTLER_DLR_NBR,PDM_ID,SLS_DEV_SPCL,SBD_ENTY_NBR,SBD_PRNT_ENTY,DLR_NAME,DLR_LNAME,
	CNTRY_KEY,ACC_OWNER_NM,SLS_TRTRY_KEY,SLS_REGN_KEY,CNTRY_SUBDIV_KEY,DIST_ID
    FROM  {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}}
    WHERE SRC_SYS_KEY = 'MTD_SALESFORCE'
) CUST
	ON TRIM(SETT.CUST_NBR) = TRIM(CUST.HUSTLER_DLR_NBR)
LEFT JOIN CAL
    -- ON SETT.GENERATION_DTE = CAL.DY_DTE
    ON SETT.SETTLEMENT_DTE = CAL.DY_DTE
	 LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
    ON SETT.PROD_NUM = EDW_PROD.PROD_KEY
    AND EDW_PROD.SRC_SYS_KEY = 'EXCEL_QADDB'
    AND EDW_PROD.CURR_RCRD_FLAG='Y'
-- LEFT JOIN (SELECT DISTINCT * FROM PROD_EDW.DIMENSIONS.DIM_CUSTOMER) CUST_EXCEL
--    ON UPPER(SETT.CUST_NBR) = UPPER(CUST_EXCEL.CUST_NBR)
--     AND UPPER(CUST_EXCEL.SRC_SYS_KEY) = 'EXCEL_QADDB'
LEFT JOIN CUST_SALESFORCE SF
ON UPPER(TRIM(SF.HUSTLER_DLR_NBR))=UPPER(TRIM(SETT.CUST_NBR))
LEFT JOIN (SELECT DISTINCT SERL_NBR,PROD_KEY,DIV_ID,INVC_NBR,PO_NBR,ORD_NBR FROM {{source('SALES_BRZ', 'BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL')}} WHERE SRC_SYS_KEY='EXCEL_QADDB'
 QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY)), UPPER(TRIM(SERL_NBR)) ORDER BY SERL_NBR ,PROD_KEY DESC ) = 1) SHIP
ON SHIP.SERL_NBR=SETT.SERIAL_NBR
AND SHIP.PROD_KEY=SETT.PROD_NUM
WHERE UPPER(TRIM(SETT.SRC_SYS_KEY)) = 'EXCEL_QADDB'
    AND UPPER(SETT.COUNTRY)='US'
    AND SETTLEMENT_FLAG = '2'

UNION ALL

SELECT
    'RETAIL' AS CTGY_ID,
    'SETTLEMENTS' AS CTGY_TYP,
    'SALES_SETTLEMENTS' AS CTGY_SHORT_NAME,
    A.SRC_SYS_KEY AS SRC_SYS_KEY,
A.PROD_CTGY AS PROD_CTGY,
  A.FYR_ID AS FYR_ID,
   A.FMTH_ID AS FMTH_ID,
A.FWK_ID AS FWK_ID,
A.PROG_YR_ID AS PROG_YR_ID,
A.PROG_MTH_ID AS PROG_MTH_ID,
A.CLNDR_YR_ID AS CLNDR_YR_ID,
A.CLNDR_MTH_ID AS CLNDR_MTH_ID,
A.REGN_KEY AS REGN_KEY,
A.TRTRY_KEY AS TRTRY_KEY,
A.DLR_SLS_MGR AS DLR_SLS_MGR,
A.PDM_ID AS PDM_ID,
A.SLS_DEV_SPCL AS SLS_DEV_SPCL,
A.DIST_ID AS DIST_ID,
A.SBD_ENTY_NBR AS SBD_ENTY_NBR,
A.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
A.DIV_ID AS DIV_ID,
A.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
A.DLR_NAME AS DLR_NAME,
A.DLR_LNAME AS DLR_LNAME,
A.DLR_STATE AS DLR_STATE,
A.DLR_CNTRY AS DLR_CNTRY,
PRODTN_LN_NBR,
BRAND,
PROD_LN_KEY,
PROD_KEY,
PROD_DESC,
IR_DTL_SKU,
PROD_STAT,
SHIP_FROM,
ORD_TYP,
INV_QTY,
TO_DECIMAL(AMOUNT,30,2) AS AMOUNT,
TO_DECIMAL(AMOUNT_USD,30,2) AS AMOUNT_USD,
TO_DECIMAL(EXTND_AMT,30,2) AS EXTND_AMT,
TXN_DTE,
TXN_TM,
TXN_EFF_DTE,
TXN_GL_DTE,
TXN_TYP,
PO_NBR,
ORD_NBR,
INVC_NBR,
SERL_NBR,
SITE_ID,
LOC_ID,
ORD_DTE,
NULL AS ORD_DUE_DTE,
INV_DTE,
INV_PO_DTE,
FULL_DUE_DTE,
SHIP_QTY,
SLS_ORD_QTY,
NULL AS FL_PLN_AG,
INV_DTE AS SETTLEMENT_DTE,
'Y' AS SETLMT_FLAG,
LOAN_ID,
'Y' AS CASH_SETTLEMENT_FLAG, 
	NULL AS DLR_NBR,
BRZ_REF_DTE
FROM
 {{source('SALES_BRZ', 'BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL')}} A
INNER JOIN (SELECT DISTINCT SBD_ENTY_NBR,PYMT_TERMS,SRC_SYS_KEY FROM {{source('DIMENSIONS', 'DIM_CUSTOMER_TEST')}} ) B
ON TRIM(A.SBD_ENTY_NBR) = TRIM(B.SBD_ENTY_NBR)
AND B.PYMT_TERMS IN ('Open Account')
AND B.SRC_SYS_KEY= 'MTD_SALESFORCE'
WHERE  A.SRC_SYS_KEY = 'INFORXA'

UNION ALL
SELECT
    'RETAIL' AS CTGY_ID,
    'SETTLEMENTS' AS CTGY_TYP,
    'SALES_SETTLEMENTS' AS CTGY_SHORT_NAME,
    E.SRC_SYS_KEY AS SRC_SYS_KEY,
E.PROD_CTGY AS PROD_CTGY,
E.FYR_ID AS FYR_ID,
E.FMTH_ID AS FMTH_ID,
E.FWK_ID AS FWK_ID,
E.PROG_YR_ID AS PROG_YR_ID,
E.PROG_MTH_ID AS PROG_MTH_ID,
E.CLNDR_YR_ID AS CLNDR_YR_ID,
E.CLNDR_MTH_ID AS CLNDR_MTH_ID,
E.REGN_KEY AS REGN_KEY,
E.TRTRY_KEY AS TRTRY_KEY,
E.DLR_SLS_MGR AS DLR_SLS_MGR,
E.PDM_ID AS PDM_ID,
E.SLS_DEV_SPCL AS SLS_DEV_SPCL,
E.DIST_ID AS DIST_ID,
E.SBD_ENTY_NBR AS SBD_ENTY_NBR,
E.SBD_PRNT_ENTY AS SBD_PRNT_ENTY,
E.DIV_ID AS DIV_ID,
E.HUSTLER_DLR_NBR AS HUSTLER_DLR_NBR,
E.DLR_NAME AS DLR_NAME,
E.DLR_LNAME AS DLR_LNAME,
E.DLR_STATE AS DLR_STATE,
E.DLR_CNTRY AS DLR_CNTRY,
E.PRODTN_LN_NBR AS PRODTN_LN_NBR,
E.BRAND AS BRAND,
E.PROD_LN_KEY AS PROD_LN_KEY,
E.PROD_KEY AS PROD_KEY,
E.PROD_DESC AS PROD_DESC,
E.IR_DTL_SKU AS IR_DTL_SKU,
E.PROD_STAT AS PROD_STAT,
E.SHIP_FROM AS SHIP_FROM,
E.ORD_TYP AS ORD_TYP,
E.INV_QTY AS INV_QTY,
TO_DECIMAL(E.AMOUNT,30,2) AS AMOUNT,
TO_DECIMAL(E.AMOUNT_USD,30,2) AS AMOUNT_USD,
TO_DECIMAL(E.EXTND_AMT,30,2) AS EXTND_AMT,
E.TXN_DTE AS TXN_DTE,
E.TXN_TM AS TXN_TM,
E.TXN_EFF_DTE AS TXN_EFF_DTE,
E.TXN_GL_DTE AS TXN_GL_DTE,
E.TXN_TYP AS TXN_TYP,
E.PO_NBR AS PO_NBR,
E.ORD_NBR AS ORD_NBR,
E.INVC_NBR AS INVC_NBR,
E.SERL_NBR AS SERL_NBR,
E.SITE_ID AS SITE_ID,
E.LOC_ID AS LOC_ID,
E.ORD_DTE AS ORD_DTE,
NULL AS ORD_DUE_DTE,
E.INV_DTE AS INV_DTE,
E.INV_PO_DTE AS INV_PO_DTE,
E.FULL_DUE_DTE AS FULL_DUE_DTE,
E.SHIP_QTY AS SHIP_QTY,
E.SLS_ORD_QTY AS SLS_ORD_QTY,
NULL AS FL_PLN_AG,
E.INV_DTE AS SETTLEMENT_DTE,
'Y' AS SETLMT_FLAG,
E.LOAN_ID AS LOAN_ID,
'Y' AS CASH_SETTLEMENT_FLAG, 
NULL AS DLR_NBR,
E.BRZ_REF_DTE AS BRZ_REF_DTE
from {{source('SALES_BRZ', 'BRZ_SALES_SHIPMENT_INDEPENDENT_RETAIL')}} E
 WHERE FINANCE_TERMS_CD IN ('B10PROX' ,'B120','B2D10','B30','B60','B6090','B90','B90120','BDAUG19','BPP','C01','C0160','C1%60'
,'C10','C10150','C10PROX','C120','C15','C150','C15PROX','C180','C20','C210','C24','C240','C270','C2D10'
,'C30','C300','C3060','C306090','C30PROX','C33','C330','C360','C369','C36912','C36925','C45','C4575','C60'
,'C60120','C6090','C75','C90','C90120','C90150','C91215','CA2','CA3','CA4','CA5','CA6','CA7','CA8','CA9','CAC','CAC8'
,'CAPMYJN','CAPRIL','CAPRMA','CAPRMAY','CAUGUST','CHD','CJNJUAU','CJULY','CJUNE','CLP','CMAY','CMYJNJU','CNL','CPP','C903')
AND E.SRC_SYS_KEY='EXCEL_QADDB' 
	        )
        SELECT * FROM TOTAL WHERE  SETLMT_FLAG = 'Y' AND COALESCE(TRIM(TRTRY_KEY), '0') NOT IN ('93') 
QUALIFY  ROW_NUMBER() OVER (PARTITION BY  UPPER(TRIM(SERL_NBR)) ORDER BY FYR_ID ,FMTH_ID,FWK_ID DESC ) = 1



