{{ config(
    materialized="table",
    schema='SALES',
	post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (PROD_KEY,FMTH_ID,FWK_ID,FYR_ID,DIV_ID,FCST_TYP,SRC_SYS_KEY)"]
) }}

 WITH CALAENDER
AS (
     SELECT DISTINCT CALENDAR_DATE,fiscal_year AS FYR_ID,concat(fiscal_year, fiscal_month) AS FMTH_ID,
        MONTH(CALENDAR_DATE) AS CLNDR_MTH_ID,
        YEAR(CALENDAR_DATE) AS CLNDR_YR_ID,
        FMTH_ID+3 AS AA_1,
        SUBSTR(AA_1,5,6) AS AA,
       CASE WHEN AA >12 THEN YEAR(CALENDAR_DATE)+1 ELSE YEAR(CALENDAR_DATE) END AS PROG_YR_ID,
       case when AA >12 THEN ROUND(AA-12) else ROUND(AA) END AS PROG_MTH_ID
     FROM  {{source('JDA','vw_planning_calendar')}}
     ),
 PL AS(
select DISTINCT FCST.PROD_KEY,A.PROD_HIER_LVL_5_DESC
FROM (SELECT DISTINCT PROD_KEY,SRC_SYS_KEY FROM {{source('DEMAND', 'BRZ_GLOBAL_FORECAST_SNAPSHOT')}} WHERE UPPER(TRIM(SRC_SYS_KEY)) = 'BLUEYONDER'
  ) FCST
LEFT JOIN
  (SELECT DISTINCT 
   PROD_KEY,PROD_HIER_LVL_5_DESC
   FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}} where SRC_SYS_KEY  = 'MTD_IAMS') A
   ON UPPER(TRIM(FCST.PROD_KEY))= UPPER(TRIM(A.PROD_KEY)) 
WHERE FCST.SRC_SYS_KEY = 'BLUEYONDER'  
    )
SELECT 
   'SALES' AS CTGY_ID,
    'FORECAST' AS CTGY_TYP,
    'SALES_FORECAST' AS CTGY_SHORT_NAME,
    -- FCST.SRC_SYS_KEY AS SRC_SYS_KEY,
	'INFORXA' AS SRC_SYS_KEY,
    PROD_1.GPP_CATEGORY_DESC  AS PROD_CTGY,
    FCST.FYR_ID AS FYR_ID,
    -- FCST.FISCAL_PERIOD AS FMTH_ID,
    LTRIM(SUBSTR(FCST.FISCAL_PERIOD, 5, 2),'0') AS FMTH_ID,
    FCST.FWK_ID AS FWK_ID,
   CAST(CAL.PROG_YR_ID AS INTEGER) AS PROG_YR_ID,
    CAL.PROG_MTH_ID AS PROG_MTH_ID,
    CAL.CLNDR_YR_ID AS CLNDR_YR_ID, 
    CAL.CLNDR_MTH_ID AS CLNDR_MTH_ID, 
    -- NULL AS REGN_KEY, -- N/R
    -- NULL AS TRTRY_KEY, -- N/R
    -- NULL AS DLR_SLS_MGR, -- N/R
    -- NULL AS PDM_ID, -- N/R
    -- NULL AS SLS_DEV_SPCL, -- N/R
    -- NULL AS DIST_ID, -- N/R
    -- NULL AS SBD_ENTY_NBR, -- N/R
    -- NULL AS SBD_PRNT_ENTY, -- N/R
    FCST.DIV AS DIV_ID,
    -- NULL AS HUSTLER_DLR_NBR, -- N/R
    -- NULL AS DLR_NAME, -- N/R
    -- NULL AS DLR_LNAME, -- N/R
    -- NULL AS DLR_STATE, -- N/R
    -- NULL AS DLR_CNTRY, -- N/R
    -- PROD.PRODTN_LN_NBR AS PRODTN_LN_NBR,
    -- null AS PRODTN_LN_NBR,
    --PROD.BRAND_LKEY AS BRAND,
    PROD.Final_Brand AS BRAND,
    PL.PROD_HIER_LVL_5_DESC  AS PROD_LN_KEY,
    --PROD.PROD_FAMILY_NAME AS PROD_LN_DESC,
    FCST.PROD_KEY AS PROD_KEY,
    PROD_1.PROD_DESC AS PROD_DESC,
    PRDH.PROD_HIER_LVL_7_KEY AS IR_DTL_SKU,
    prd_loc.PROD_STAT_DESC as PROD_STAT, 
    -- NULL AS SHIP_FROM, -- N/R
    -- NULL AS ORD_TYP, -- N/R
    ROUND(FCST.FCST_QTY, 2) AS SLS_FCST_QTY,
    -- ROUND(FCST.CURRENT_STANDARD_COST, 2) AS AMOUNT_USD,
    TO_DECIMAL(STD_COST,30,2) AS AMOUNT,
    TO_DECIMAL(SLS_FCST_QTY * AMOUNT,30,2) AS EXTND_AMT,
    -- NULL AS TXN_ID, -- N/R
    -- NULL AS TXN_DTE, -- N/R
    -- NULL AS TXN_TM, -- N/R
    -- NULL AS TXN_EFF_DTE, -- N/R
    -- NULL AS TXN_GL_DTE, -- N/R
    -- NULL AS TXN_TYP, -- N/R
    -- NULL AS PO_NBR, -- N/R
    -- NULL AS INV_NBR, -- N/R
    -- NULL AS SERL_NBR, -- N/R
    -- NULL AS SITE_ID, -- N/R
    -- NULL AS LOC_ID, -- N/R
    -- NULL AS ORD_DTE, -- N/R
    -- NULL AS ORD_DUE_DTE, -- N/R
    -- NULL AS INV_DTE, -- N/R
    -- NULL AS INV_PO_DTE, -- N/R
    -- NULL AS FULL_DUE_DTE, -- N/R
    -- NULL AS SLS_ORD_QTY, -- N/R
    -- NULL AS SHIP_QTY, -- N/R
    -- NULL AS FL_PLN_AG, -- N/R
    -- NULL AS CAL_ON_TIME_FULL, -- N/R
    FCST.FCST_START_DTE,
	FCST.FCST_TYP,
     PROD_EDW.PRODTN_LN_NBR,
    FCST.CRNCY_KEY AS CRNCY_KEY,
    NULL AS LOAN_ID,
   PRDLKP.PROD_BRAND AS BRAND_UU40,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE
    FROM {{source('DEMAND', 'BRZ_GLOBAL_FORECAST_SNAPSHOT')}} AS FCST
LEFT JOIN (SELECT * FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='BLUEYONDER') PROD
    ON (FCST.SRC_SYS_KEY || '~' || FCST.PROD_KEY) = PROD.PROD_KEY
    -- AND PROD.SRC_SYS_KEY = 'BLUEYONDER'
LEFT JOIN (SELECT * FROM {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='INFORXA') PROD_1
    -- ON (FCST.SRC_SYS_KEY || '~' || FCST.PROD_KEY) = PROD_1.PROD_KEY
    ON FCST.PROD_KEY=PROD_1.PROD_ID
    -- AND PROD.SRC_SYS_KEY = 'INFORXA'
LEFT JOIN (SELECT * FROM CALAENDER) CAL
ON DATE(FCST.FCST_START_DTE) =DATE(CAL.calendar_date)
LEFT JOIN (
SELECT DISTINCT PROD_KEY,PROD_STAT_LKEY,PROD_STAT_DESC,PROD_LOC_LOV.PROD_LOC_KEY,LOC_KEY FROM 
(Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,LOC_KEY from {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}}
	where src_sys_key = 'INFORXA') PROD_LOC
	 LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION_LOV')}} PROD_LOC_LOV
	 on CONCAT(PROD_LOC.PROD_LOC_KEY,'~','E') = PROD_LOC_LOV.PROD_LOC_KEY
     ) PRD_LOC
 ON FCST.PROD_KEY=PRD_LOC.PROD_KEY
 AND FCST.LOC_KEY=PRD_LOC.LOC_KEY
 LEFT JOIN (SELECT DISTINCT PROD_KEY,PROD_HIER_LVL_7_KEY,PROD_HIER_LVL_4_DESC,BUS_DIV_ID,SRC_SYS_KEY,CURR_RCRD_FLAG,PROD_HIER_LVL_5_KEY
  FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}} WHERE SRC_SYS_KEY='INFORXA')  PRDH
ON FCST.PROD_KEY = PRDH.PROD_KEY 
AND  CURR_RCRD_FLAG = 'Y' 
AND BUS_DIV_ID = '1' -- 1 is US & 3 is CA
--AND PRD.PROD_HIER_LVL_7_ID=PRDH.PROD_HIER_LVL_7_ID
AND PRDH.SRC_SYS_KEY='INFORXA'
LEFT JOIN PROD_EDW.CONSOLIDATED.VW_EDW_PRODUCT_LOOKUP PRDLKP
    ON UPPER(TRIM(FCST.PROD_KEY))=UPPER(TRIM(PRDLKP.PROD_LKP_KEY))
    AND PRDLKP.SRC_SYS_KEY='INFORXA'
-- WHERE FCST.SRC_SYS_KEY = 'BLUEYONDER' 
LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS PROD_EDW
    ON FCST.PROD_KEY = PROD_EDW.PROD_KEY
    AND PROD_EDW.SRC_SYS_KEY = 'INFORXA'
    AND PROD_EDW.CURR_RCRD_FLAG='Y'
    LEFT JOIN PL
    ON UPPER(TRIM(PL.PROD_KEY))=UPPER(TRIM(FCST.PROD_KEY))
WHERE FCST.SRC_SYS_KEY = 'BLUEYONDER'


UNION ALL

SELECT 
    'SALES' AS CTGY_ID,
    'FORECAST' AS CTGY_TYP,
    'SALES_FORECAST' AS CTGY_SHORT_NAME,
    'EXCEL_QADDB' AS SRC_SYS_KEY,
    PROD.GPP_CATEGORY_DESC  AS PROD_CTGY, ----- mapping if needed, or remove the comment
    FCAST.FYR_ID AS FYR_ID,
    -- FCAST.FISCAL_PERIOD AS FMTH_ID,
   LTRIM(SUBSTR(FCAST.FISCAL_PERIOD, 5, 2),'0') AS FMTH_ID,
    FCAST.FWK_ID AS FWK_ID,
   CAST(CAL.PROG_YR_ID AS INTEGER) AS PROG_YR_ID,
   CAL.PROG_MTH_ID AS PROG_MTH_ID,  
   CAL.CLNDR_YR_ID AS CLNDR_YR_ID,
   CAL.CLNDR_MTH_ID AS CLNDR_MTH_ID,
    -- NULL AS REGN_KEY, -- N/R
    -- NULL AS TRTRY_KEY, -- N/R
    -- NULL AS DLR_SLS_MGR, -- N/R
    -- NULL AS PDM_ID, -- N/R
    -- NULL AS SLS_DEV_SPCL, -- N/R
    -- NULL AS DIST_ID, -- N/R
    -- NULL AS SBD_ENTY_NBR, -- N/R
    -- NULL AS SBD_PRNT_ENTY, -- N/R
       NULL  AS DIV_ID,
    -- NULL AS HUSTLER_DLR_NBR, -- N/R
    -- NULL AS DLR_NAME, -- N/R
    -- NULL AS DLR_LNAME, -- N/R
    -- NULL AS DLR_STATE, -- N/R
    -- NULL AS DLR_CNTRY, -- N/R
    -- PROD.PRODTN_LN_NBR AS PRODTN_LN_NBR,
    -- null AS PRODTN_LN_NBR,
    --PROD.BRAND_LKEY AS BRAND,
     PROD.Final_Brand  AS BRAND,
   -- CASE WHEN FCAST.PROD_KEY = '181SAAY2739' THEN 'DEWALT' ELSE PROD.Final_Brand  END AS BRAND,
    PROD.PROD_FAMILY_LKEY AS PROD_LN_KEY,
    --PROD.PROD_FAMILY_NAME AS PROD_LN_DESC,
    FCAST.PROD_KEY AS PROD_KEY,
    -- PROD.PROD_DESC AS PROD_DESC, --NULLS
REGEXP_REPLACE(PROD.PROD_DESC, '~*EXCEL$', '') AS PROD_DESC,  
    --CONCAT(PROD.PROD_FAMILY_NAME,substr( PROD.PROD_DESC,8,2) ,'    ',substr( PROD.PROD_DESC,10,9)) IR_DTL_SKU,
CASE WHEN SUBSTR(PROD.PROD_DESC,6,1)='R'
THEN CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,6,1),' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
ELSE CONCAT(PROD.PROD_FAMILY_NAME,' ',SUBSTR(PROD.PROD_DESC,8,2),' ',SUBSTR(PROD.PROD_DESC,10,8))
END AS IR_DTL_SKU,
  CASE 
        WHEN (PROD.PROD_STAT_TYP) = 'ACT' THEN 'ACT'
        ELSE 'INACT' 
    END AS PROD_STAT,
    -- NULL AS SHIP_FROM, -- N/R
    -- NULL AS ORD_TYP, -- N/R
    ROUND(FCAST.FCST_QTY, 2) AS SLS_FCST_QTY,
    -- ROUND(PC.CURR_STD_COST, 2) AS AMOUNT_USD,
    TO_DECIMAL(CASE 
              WHEN FCST_QTY > 0 THEN CURRENT_STANDARD_COST / FCST_QTY 
              ELSE 0 
           END, 30, 2) AS AMOUNT_USD,
    -- NET_DCRNCY_AMT AS NET_AMT_USD,
   TO_DECIMAL (CURRENT_STANDARD_COST ,30,2)AS EXTND_AMT,
    -- NULL AS TXN_ID, -- N/R
    -- NULL AS TXN_DTE, -- N/R
    -- NULL AS TXN_TM, -- N/R
    -- NULL AS TXN_EFF_DTE, -- N/R
    -- NULL AS TXN_GL_DTE, -- N/R
    -- NULL AS TXN_TYP, -- N/R
    -- NULL AS PO_NBR, -- N/R
    -- NULL AS INV_NBR, -- N/R
    -- NULL AS SERL_NBR, -- N/R
    -- NULL AS SITE_ID, -- N/R
    -- NULL AS LOC_ID, -- N/R
    -- NULL AS ORD_DTE, -- N/R
    -- NULL AS ORD_DUE_DTE, -- N/R
    -- NULL AS INV_DTE, -- N/R
    -- NULL AS INV_PO_DTE, -- N/R
    -- NULL AS FULL_DUE_DTE, -- N/R
    -- NULL AS SLS_ORD_QTY, -- N/R
    -- NULL AS SHIP_QTY, -- N/R
    -- NULL AS FL_PLN_AG, -- N/R
    -- NULL AS CAL_ON_TIME_FULL, -- N/R
    FCAST.FCST_START_DTE,
	FCAST.FCST_TYP,
    PROD_EDW.PRODTN_LN_NBR,
   FCAST.CRNCY_KEY AS CRNCY_KEY,
    NULL AS LOAN_ID,
   NULL AS BRAND_UU40,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ AS BRZ_REF_DTE

FROM {{source('DEMAND', 'BRZ_GLOBAL_FORECAST_SNAPSHOT')}} AS FCAST
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT')}} AS PROD
-- ON (FCAST.SRC_SYS_KEY || '~' || FCAST.PROD_KEY) = PROD.PROD_KEY
ON FCAST.PROD_KEY=PROD.PROD_ID
and prod.src_sys_key='EXCEL_QADDB'
LEFT JOIN (SELECT * FROM CALAENDER) CAL
ON FCAST.FCST_START_DTE =CAL.calendar_date
--AND PROD.SRC_SYS_KEY = 'EXCEL_QADDB'
-- LEFT JOIN (SELECT DISTINCT PC.PROD_KEY,PC.LOC_KEY,PC.CURR_STD_COST FROM PROD_EDW.CONSOLIDATED.EDW_PRODUCT_COST AS PC
--     WHERE PC.SRC_SYS_KEY = 'EXCEL_QADDB' AND  SUBSTR(PC.prod_cost_key, 1, 7) = 'CURRENT') PC
--     ON FCAST.PROD_KEY = PC.prod_key
--     AND FCAST.LOC_KEY = PC.LOC_KEY
LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS PROD_EDW
    ON FCAST.PROD_KEY = PROD_EDW.PROD_KEY
    AND PROD_EDW.SRC_SYS_KEY = 'EXCEL_QADDB'
    AND PROD_EDW.CURR_RCRD_FLAG='Y'
WHERE FCAST.SRC_SYS_KEY = 'EXCEL_ACCOUNTING' 


