
{{ config(
    materialized="table",
    schema='SALES',
     post_hook=["ALTER TABLE {{ this }} ADD PRIMARY KEY (SRC_SYS_KEY,PROD_KEY,SITE_ID,FWK_ID)"]
) }}

	WITH PL AS(
select DISTINCT 
     PRODTN.PROD_KEY,A.PROD_HIER_LVL_5_DESC,PRODTN.LOC_KEY,PRODTN.FWK_ID,PRODTN.FYR_ID,PRODTN.FISC_YR_MTH,PRODTN.STK_MVMNT_TYP_LKEY
FROM (SELECT DISTINCT PROD_KEY,SRC_SYS_KEY,LOC_KEY,FWK_ID,FYR_ID,FISC_YR_MTH,STK_MVMNT_TYP_LKEY FROM {{source('SUPPLY', 'BRZ_PRODUCTION_VOLUME')}} WHERE SRC_SYS_KEY='INFORXA') PRODTN 
LEFT JOIN
  (SELECT DISTINCT 
   PROD_KEY,PROD_HIER_LVL_5_DESC
   FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_PRODUCT_HIERARCHY')}} where SRC_SYS_KEY  = 'MTD_IAMS') A
   ON UPPER(TRIM(PRODTN.PROD_KEY))= UPPER(TRIM(A.PROD_KEY)) 
WHERE 
     PRODTN.SRC_SYS_KEY = 'INFORXA'  
    )
 
SELECT 
     PRODTN.SRC_SYS_KEY                       AS SRC_SYS_KEY,
    'ACTUAL'                                  AS CTGY_ID,
    'PRODUCTION'                              AS CTGY_TYP,
    'SALES_PRODUCTION_ACTUAL'                 AS CTGY_SHORT_NAME,
     PRD.GPP_CATEGORY_DESC                    AS PROD_CTGY,
     PRODTN.FYR_ID                            AS FYR_ID,
     LTRIM(SUBSTR(PRODTN.FISC_YR_MTH, 5, 2),'0') AS FMTH_ID,
     CASE WHEN TO_NUMBER(substring(PRODTN.FISC_YR_MTH,5,2),2,0)+3 >12  THEN TO_NUMBER(PRODTN.FYR_ID)+1 ELSE TO_NUMBER(PRODTN.FYR_ID) END AS PROG_YR_ID,
     CASE WHEN TO_NUMBER(substring(PRODTN.FISC_YR_MTH,5,2),2,0)+3 >12 THEN ROUND(TO_NUMBER(substring(PRODTN.FISC_YR_MTH,5,2),2,0)+3 -12) else ROUND(LPAD(TO_NUMBER(substring(PRODTN.FISC_YR_MTH,5,2),2,0)+3,2,0)) END   AS PROG_MTH_ID,
     YEAR(PRODTN.SRC_RCRD_CREATE_DTE)         AS CLNDR_YR_ID,
     MONTH(PRODTN.SRC_RCRD_CREATE_DTE)        AS CLNDR_MTH_ID,
     PRODTN.FWK_ID                            AS FWK_ID,  
    NULL                                      AS DIV_ID,
    EDW_PROD.PRODTN_LN_NBR                    AS PRODTN_LN_NBR,
    PRD.FINAL_BRAND                           AS BRAND,
    PL.PROD_HIER_LVL_5_DESC                   AS PROD_LN_KEY,
    --PROD.PROD_FAMILY_NAME                   AS PROD_LN_DESC,
    PRODTN.PROD_KEY                           AS PROD_KEY,
    PRD.PROD_DESC                             AS PROD_DESC,
    PRDH.PROD_HIER_LVL_7_KEY                  AS IR_DTL_SKU,
    -- PROD_LOC_LOV.PROD_STAT_DESC               AS PROD_STAT,
  CASE 
    WHEN TRIM(UPPER(PROD_LOC_LOV .PROD_STAT_DESC )) = 'ACTIVE' THEN 'ACT'
    WHEN TRIM(UPPER(PROD_LOC_LOV .PROD_STAT_DESC )) = 'SUPPRESSED (INACTIVE)' THEN 'INACT'
    ELSE  PROD_LOC_LOV .PROD_STAT_DESC 
  END AS PROD_STAT,
  TO_DECIMAL(PRODTN.GOODS_RCPT_ISS_PROD_QTY, 30, 2)           AS PROD_QTY, 
TO_DECIMAL(PRODTN.GOODS_RCPT_ISS_LCRNCY_AMT, 30, 2)         AS AMOUNT,
TO_DECIMAL(PRODTN.GOODS_RCPT_ISS_PROD_QTY * PRODTN.GOODS_RCPT_ISS_LCRNCY_AMT, 30, 2) AS EXTND_AMT,
    --NULL                                      AS TXN_ID,	
    NULL                                      AS TXN_DTE,
    NULL                                      AS TXN_TM,
    NULL                                      AS TXN_EFF_DTE,
    NULL                                      AS TXN_GL_DTE,
    NULL                                      AS TXN_TYP,
    PRODTN.LOC_KEY                            AS SITE_ID,
    PRDL.LOC_KEY                              AS LOC_NAME,
    PRODTN.CRNCY_KEY                          AS CRNCY_KEY,
     NULL                                      AS LOAN_ID,
     PRDLKP.PROD_BRAND                         AS BRAND_UU40,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ          AS BRZ_REF_DTE
FROM {{source('SUPPLY', 'BRZ_PRODUCTION_VOLUME')}} PRODTN 
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT')}} PRD
ON (PRODTN.SRC_SYS_KEY||'~'||PRODTN.PROD_KEY) = PRD.PROD_KEY 
AND PRD.SRC_SYS_KEY='INFORXA'
LEFT JOIN ( Select DISTINCT PROD_STAT_LKEY,PROD_LOC_KEY,LOC_KEY,CNTRY_OF_ORIG_KEY,PROD_KEY,SRC_SYS_KEY from {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION')}} WHERE SRC_SYS_KEY='INFORXA'
	QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PROD_KEY))  ORDER BY PROD_KEY,LOC_KEY DESC) =1) PRDL
      ON UPPER(TRIM(PRODTN.PROD_KEY)) = UPPER(TRIM(PRDL.PROD_KEY))      
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT_LOCATION_LOV')}} PROD_LOC_LOV 
ON CONCAT(PRDL.PROD_LOC_KEY,'~','E') = PROD_LOC_LOV.PROD_LOC_KEY
LEFT JOIN (SELECT DISTINCT PROD_KEY,PROD_HIER_LVL_7_KEY,BUS_DIV_ID,SRC_SYS_KEY,CURR_RCRD_FLAG,PROD_HIER_LVL_4_DESC,PROD_HIER_LVL_5_KEY
  FROM {{source('CONSOLIDATED_PROD', 'VW_EDW_IR_PRODUCT_HIERARCHY')}} WHERE SRC_SYS_KEY='INFORXA')  PRDH
ON PRODTN .PROD_KEY = PRDH.PROD_KEY 
AND  CURR_RCRD_FLAG = 'Y' 
AND BUS_DIV_ID = '1' -- 1 is US & 3 is CA
AND PRDH.SRC_SYS_KEY='INFORXA'
 LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
ON PRODTN.PROD_KEY = EDW_PROD.PROD_KEY
AND EDW_PROD.SRC_SYS_KEY = 'INFORXA'
AND EDW_PROD.CURR_RCRD_FLAG='Y'
LEFT JOIN ( SELECT * FROM  {{source('DIMENSIONS', 'DIM_PRODUCT')}} WHERE SRC_SYS_KEY='BLUEYONDER') PROD
ON UPPER(TRIM(PROD.PROD_ID))=UPPER(TRIM(PRODTN .PROD_KEY))
LEFT JOIN  PROD_EDW.CONSOLIDATED.VW_EDW_PRODUCT_LOOKUP PRDLKP
    ON UPPER(TRIM(PRODTN.PROD_KEY))=UPPER(TRIM(PRDLKP.PROD_LKP_KEY))
    AND PRDLKP.SRC_SYS_KEY='INFORXA'
LEFT JOIN (SELECT * FROM PL
        QUALIFY  ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(PL.PROD_KEY)) ORDER BY PL.PROD_KEY DESC ) = 1)PL
    ON UPPER(TRIM(PL.PROD_KEY))=UPPER(TRIM(PRODTN.PROD_KEY))
    AND UPPER(TRIM(PL.LOC_KEY))=UPPER(TRIM(PRODTN.LOC_KEY))
    AND PL.FWK_ID=PRODTN.FWK_ID
     AND PL.FYR_ID=PRODTN.FYR_ID
     AND PL.FISC_YR_MTH=PRODTN.FISC_YR_MTH
     AND UPPER(TRIM(PRODTN.STK_MVMNT_TYP_LKEY))=UPPER(TRIM(PL.STK_MVMNT_TYP_LKEY))
    WHERE PRODTN.SRC_SYS_KEY IN ('INFORXA')


UNION ALL

SELECT 
     PRODTN.SRC_SYS_KEY                      AS SRC_SYS_KEY,
    'ACTUAL'                                 AS CTGY_ID,
    'PRODUCTION'                             AS CTGY_TYP,
    'SALES_PRODUCTION_ACTUAL'                AS CTGY_SHORT_NAME,
    PRD.GPP_CATEGORY_DESC                    AS PROD_CTGY,
    PRODTN.FYR_ID                            AS FYR_ID,
    -- PRODTN.FISC_YR_MTH                       AS FMTH_ID,
     LTRIM(SUBSTR(PRODTN.FISC_YR_MTH, 5, 2),'0') AS FMTH_ID,
    CASE WHEN TO_NUMBER(substring(PRODTN.FISC_YR_MTH,5,2),2,0)+3 >12  THEN TO_NUMBER(PRODTN.FYR_ID)+1 ELSE TO_NUMBER(PRODTN.FYR_ID) END AS PROG_YR_ID,
    CASE WHEN TO_NUMBER(substring(PRODTN.FISC_YR_MTH,5,2),2,0)+3 >12 THEN ROUND(TO_NUMBER(substring(PRODTN.FISC_YR_MTH,5,2),2,0)+3 -12) else ROUND(LPAD(TO_NUMBER(substring(PRODTN.FISC_YR_MTH,5,2),2,0)+3,2,0)) END   AS PROG_MTH_ID,
    YEAR(PRODTN.SRC_RCRD_CREATE_DTE)         AS CLNDR_YR_ID,
    MONTH(PRODTN.SRC_RCRD_CREATE_DTE)        AS CLNDR_MTH_ID,
    PRODTN.FWK_ID                            AS FWK_ID,
    NULL                                     AS DIV_ID,
    EDW_PROD.PRODTN_LN_NBR                   AS PRODTN_LN_NBR,
    PRD.Final_Brand                          AS BRAND,
    --CASE WHEN PRODTN.PROD_KEY = '181SAAY2739' THEN 'DEWALT' ELSE PRD.Final_Brand  END AS BRAND,
    PRD.PROD_FAMILY_LKEY                    AS PROD_LN_KEY,
    --PRD.PROD_FAMILY_NAME                   AS PROD_LN_DESC,
    PRODTN.PROD_KEY                          AS PROD_KEY,
    -- PRD.PROD_DESC                            AS PROD_DESC,
   REGEXP_REPLACE(PRD.PROD_DESC, '~*EXCEL$', '') AS PROD_DESC,  
   --CONCAT(PRD.PROD_FAMILY_NAME,substr( PRD.PROD_DESC,8,2) ,'    ',substr( PRD.PROD_DESC,10,9)) IR_DTL_SKU,
	CASE WHEN SUBSTR(PRD.PROD_DESC,6,1)='R'
THEN CONCAT(PRD.PROD_FAMILY_NAME,' ',SUBSTR(PRD.PROD_DESC,6,1),' ',SUBSTR(PRD.PROD_DESC,8,2),' ',SUBSTR(PRD.PROD_DESC,10,8))
ELSE CONCAT(PRD.PROD_FAMILY_NAME,' ',SUBSTR(PRD.PROD_DESC,8,2),' ',SUBSTR(PRD.PROD_DESC,10,8))
END AS IR_DTL_SKU,
     CASE 
        WHEN (PRD.PROD_STAT_TYP) = 'ACT' THEN 'ACT'
        ELSE 'INACT' 
    END AS PROD_STAT,
  TO_DECIMAL(PRODTN.GOODS_RCPT_ISS_PROD_QTY, 30, 2) AS PROD_QTY, 
TO_DECIMAL(PRODTN.GOODS_RCPT_ISS_LCRNCY_AMT, 30, 2) AS AMOUNT,
TO_DECIMAL(PRODTN.GOODS_RCPT_ISS_PROD_QTY * PRODTN.GOODS_RCPT_ISS_LCRNCY_AMT, 30, 2) AS EXTND_AMT,
    --NULL                                     AS TXN_ID,
    NULL                                     AS TXN_DTE,
    NULL                                     AS TXN_TM,
    NULL                                     AS TXN_EFF_DTE,
    NULL                                     AS TXN_GL_DTE,
    NULL                                     AS TXN_TYP,
    PRODTN.LOC_KEY                           AS SITE_ID,
    LOC.LOC_NAME                             AS LOC_NAME,
    PRODTN.CRNCY_KEY                         AS CRNCY_KEY,
     NULL                                      AS LOAN_ID,
     NULL                                     AS BRAND_UU40,
    CURRENT_TIMESTAMP::TIMESTAMP_NTZ         AS BRZ_REF_DTE
FROM {{source('SUPPLY', 'BRZ_PRODUCTION_VOLUME')}} PRODTN 
LEFT JOIN {{source('DIMENSIONS', 'DIM_PRODUCT')}} PRD
ON TRIM(PRODTN.PROD_KEY)=TRIM(PRD.PROD_ID)
AND PRD.SRC_SYS_KEY='EXCEL_QADDB'
 LEFT JOIN {{source('CONSOLIDATED_PROD', 'VW_EDW_LOCATION')}} LOC
 ON PRODTN .LOC_KEY=LOC.LOC_KEY
 AND LOC.SRC_SYS_KEY='EXCEL_QADDB'
 LEFT JOIN {{source('CONSOLIDATED', 'EDW_PRODUCT')}} AS EDW_PROD
 ON PRODTN.PROD_KEY = EDW_PROD.PROD_KEY
 AND EDW_PROD.SRC_SYS_KEY = 'EXCEL_QADDB'
AND EDW_PROD.CURR_RCRD_FLAG='Y'
WHERE PRODTN.SRC_SYS_KEY IN ('EXCEL_QADDB')
