
create or replace view TEST_MARTS.SALES.VW_BRZ_SALES_INDEPENDENT_RETAIL(
CTGY_ID COMMENT 'Type of product transaction',
CTGY_TYP COMMENT 'Type of Category (PRODUCTION, Forecast, Etc.)',
CTGY_SHORT_NAME COMMENT 'Abbreviated Name of Category',
SRC_SYS_KEY COMMENT 'Source System Identifier',
PROD_CTGY COMMENT 'Product Type (Wholegoods, Parts, Dewalt, etc.)',
FYR_ID COMMENT 'Fiscal Year of Transaction',
FMTH_ID COMMENT 'Fiscal Period of Transaction (Jan=1, Feb=2, etc.)',
FWK_ID COMMENT 'Fiscal Week ID',
PROG_YR_ID COMMENT 'Program Year of Transaction (Starting Oct 1st)',
PROG_MTH_ID COMMENT 'Program Month of Transaction (Oct=1, Nov=2, etc.)',
CLNDR_YR_ID COMMENT 'Calendar Year of Transaction',
CLNDR_MTH_ID COMMENT 'Calendar Month of Transaction',
REGN_KEY COMMENT 'IR Region (Country is split into 4 RSDs)',
TRTRY_KEY COMMENT 'IR Territory (Dealer Sales Manager Territories)',
DLR_SLS_MGR COMMENT 'Dealer Sales Manager',
PDM_ID COMMENT 'Pro Development Manager',
SLS_DEV_SPCL COMMENT 'Inside Sales Rep',
DIST_ID COMMENT 'Distributor Identifier if applicable',
SBD_ENTY_NBR COMMENT 'Customer Number',
SBD_PRNT_ENTY COMMENT 'Customer Parent Number',
DIV_ID COMMENT 'Customer Division (e.g., Div 38, Div 52)',
HUSTLER_DLR_NBR COMMENT 'Legacy Hustler Dealer Number',
DLR_NAME COMMENT 'Customer Name',
DLR_LNAME COMMENT 'Customer Legal Name',
DLR_STATE COMMENT 'State of Customer',
DLR_CNTRY COMMENT 'Country of Customer',
PRODTN_LN_NBR COMMENT 'Line this production is produced on',
BRAND COMMENT 'Brand of Product',
PROD_LN_KEY COMMENT 'Type of Product (Item Family)',
PROD_KEY COMMENT 'SKU/Part Number',
PROD_DESC COMMENT 'Part Description',
IR_DTL_SKU COMMENT 'Simplified Part Detail',
PROD_STAT COMMENT 'Status of the Current Part',
SHIP_FROM COMMENT 'Warehouse Shipped From',
ORD_TYP COMMENT 'Type of Order (Order Prefix)',
QTY COMMENT 'Count of Serial #''s impacting this record',
AMOUNT COMMENT 'Sum of $ Value Serial #''s impacting this record',
AMOUNT_USD COMMENT 'Sum of Amount in USD',
EXTND_AMT COMMENT 'Units * Amount',
ORD_LN_NBR COMMENT 'Order Line',
TXN_DTE COMMENT 'Transaction Date',
TXN_TM COMMENT 'Transaction time',
PO_NBR COMMENT 'PO Number',
INVC_NBR COMMENT '# on Invoice',
INVC_LN_NBR COMMENT 'Invoice line',
SERL_NBR COMMENT 'Serial Number of product in this record',
SITE_ID COMMENT 'Site this unit was manufactured at',
LOC_ID COMMENT 'Location identifier',
LOC_KEY COMMENT 'Unique key for the location',
LOC_NAME COMMENT 'Full name of the location',
ORD_DTE COMMENT 'Date Serial was ordered',
ORD_DUE_DATE COMMENT 'Date Serial was due to ship to customer',
INV_DTE COMMENT 'Date serial was invoiced',
INV_PO_DTE COMMENT 'Date serial was purchased by FP company',
FULL_DUE_DTE COMMENT 'Date serial would flip to Dealer interest bearing',
SLS_ORD_QTY COMMENT 'Sales Order Quantity',
SHIP_QTY COMMENT 'Shiped quantity',
CAL_ON_TIME_FULL COMMENT 'Calculation of did the line item of the order get shipped on or before the order due date',
ORD_STAT_FLAG COMMENT 'Orders Status Flag',
OPEN_ORDER_FLAG COMMENT 'Indicates whether the order is still open (1 = Open, 0 = Closed)',
ORD_LN_KEY COMMENT 'Unique ID for the order line item',
ORD_NBR COMMENT 'Unique sales or purchase order number',
BRAND_UU40 COMMENT 'Brand identifier or code',
CRNCY_KEY COMMENT 'CRNCY KEY',
ORD_HOLD_FLAG COMMENT 'Order hold status flag (Y/N)',
MFG_DUE_DATE COMMENT 'Manufacturing due date',
QUOTE_ORDER_DATE COMMENT 'Date quote was converted to order',
ORD_APRV_STAT COMMENT 'Order approval status',
OPEN_UNITS COMMENT 'Open Units',
LOAN_ID COMMENT 'Loan identification number',
SUPPLY_PLND_ORD_KEY COMMENT 'SUPPLY_PLND_ORD_KEY',
CARTON_NBR COMMENT 'CARTON_NBR',
WHSE_NBR COMMENT 'WAREHOUSE NUMBER',
SETLMT_FLAG COMMENT 'Flag indicating whether the settlement limit has been reached',
REGISTRATION_FLAG COMMENT 'Flag indicating whether the registration is completed',
CASH_SETTLEMENT_FLAG COMMENT 'Indicator specifying whether the transaction is settled in cash',
REG_KEY COMMENT 'Reg key',
REG_DATE COMMENT 'Date Serial # Was Registered',
SETTLEMENT_DTE COMMENT 'The Settlement Date refers to the date on which a financial transaction is completed',
SHIPPED_USD COMMENT 'Shipment Dollars',
FCST_START_DTE COMMENT 'The start date of the forecast period',
FCST_TYP COMMENT 'The category or type of forecast (e.g., statistical, manual)',
INTEREST_START_DTE COMMENT 'The date from which interest calculation begins',
ETL_INS_DTE COMMENT 'The date the record was inserted via ETL process',
CUST_ACCT_GRP_DESC COMMENT 'Description of the customer account group',
DLR_NBR COMMENT 'Identifier number assigned to the dealer',
FREE_FLOORPLAN_END_DTE COMMENT 'Free Floorplan end date',
SLS_ORD_FROM_WHSE_KEY COMMENT 'Sales order originating warehouse key',
CREDIT_RESN_LN COMMENT 'Reason for credit line',
BRZ_REF_DTE COMMENT 'BRZ refresh date'
) as
SELECT
    CTGY_ID,
    CTGY_TYP,
    CTGY_SHORT_NAME,
    SRC_SYS_KEY,
    PROD_CTGY,
    CAST(FYR_ID AS INT),
    CAST(FMTH_ID AS INT),
    CAST(FWK_ID AS INT),
    CAST(PROG_YR_ID AS INT),
    CAST(PROG_MTH_ID AS INT),
    CAST(CLNDR_YR_ID AS INT),
    CAST(CLNDR_MTH_ID AS INT),
    REGN_KEY,
    TRTRY_KEY,
    DLR_SLS_MGR,
    PDM_ID,
    SLS_DEV_SPCL,
    DIST_ID,
    SBD_ENTY_NBR,
    SBD_PRNT_ENTY,
    DIV_ID,
    HUSTLER_DLR_NBR,
    DLR_NAME,
    DLR_LNAME,
    DLR_STATE,
    DLR_CNTRY,
    PRODTN_LN_NBR,
    BRAND,
    PROD_LN_KEY,
    PROD_KEY,
    PROD_DESC,
    IR_DTL_SKU,
    PROD_STAT,
    SHIP_FROM,
    ORD_TYP,
    TO_DECIMAL(QTY, 30, 2) AS QTY,
    TO_DECIMAL(AMOUNT,30,2) AS AMOUNT,
    TO_DECIMAL(AMOUNT_USD,30,2) AS AMOUNT_USD,
    TO_DECIMAL(EXTND_AMT,30,2) AS EXTND_AMT,
    -- TXN_ID,
    ORD_LN_NBR,
    TXN_DTE,
    TXN_TM,
    PO_NBR,
    INVC_NBR,
    INVC_LN_NBR,
    SERL_NBR,
    SITE_ID,
    LOC_ID,
    LOC_KEY,
    LOC_NAME,
    ORD_DTE,
    ORD_DUE_DATE,
    INV_DTE,
    INV_PO_DTE,
    FULL_DUE_DTE,
    TO_DECIMAL(SLS_ORD_QTY,30,2) AS SLS_ORD_QTY,
    TO_DECIMAL(SHIP_QTY, 30, 2) AS SHIP_QTY,
    CAL_ON_TIME_FULL,
    ORD_STAT_FLAG,
    OPEN_ORDER_FLAG,
    ORD_LN_KEY,
    ORD_NBR,
    BRAND_UU40,
    CRNCY_KEY,
    ORD_HOLD_FLAG,
    MFG_DUE_DATE,
    QUOTE_ORDER_DATE,
    ORD_APRV_STAT,
    OPEN_UNITS,
    LOAN_ID,
    SUPPLY_PLND_ORD_KEY,
    CARTON_NBR,
    WHSE_NBR,
    SETLMT_FLAG,
    REGISTRATION_FLAG,
    CASH_SETTLEMENT_FLAG,
    REG_KEY,
    REG_DATE,
    SETTLEMENT_DTE,
    SHIPPED_USD,
    FCST_START_DTE,
    FCST_TYP,
    INTEREST_START_DTE,
    ETL_INS_DTE,
    CUST_ACCT_GRP_DESC,
    DLR_NBR,
    FREE_FLOORPLAN_END_DTE,
    SLS_ORD_FROM_WHSE_KEY,
    CREDIT_RESN_LN,
    CAST(BRZ_REF_DTE AS VARCHAR) AS BRZ_REF_DTE
FROM
    TEST_MARTS.SALES.BRZ_SALES_INDEPENDENT_RETAIL;


